insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9C',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',0,null,0,'approver','erm.jkzb.approver',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,1,'tail','tail',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9D',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',0,null,0,'creator','erm.jkzb.creator',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,'用户,dpc=fi',null,null,'N',0,1,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9E',1,-1,null,null,0,0,null,-1,'N',null,-1,'shrq_show',0,'N',1,'N','N',0,null,0,'shrq_show','erm.jkzb.shrq_show',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,2,'tail','tail',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9F',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',0,null,0,'creationtime','erm.jkzb.creationtime',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,2,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9G',1,-1,null,null,0,0,null,-1,'N',null,-1,'shrq',0,'N',1,'N','N',0,null,0,'shrq','erm.jkzb.shrq',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,3,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9H',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',0,null,0,'modifier','erm.jkzb.modifier',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,3,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9I',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',0,null,0,'modifiedtime','erm.jkzb.modifiedtime',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,4,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9J',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsr',0,'N',1,'N','N',0,null,0,'jsr','erm.jkzb.jsr',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,4,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9K',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsrq',0,'N',1,'N','N',0,null,0,'jsrq','erm.jkzb.jsrq',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,5,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9L',1,-1,null,null,0,0,null,-1,'N',null,-1,'payman',0,'N',1,'N','N',0,null,0,'payman','erm.jkzb.payman',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,6,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9M',1,-1,null,null,0,0,null,-1,'N',null,-1,'paydate',0,'N',1,'N','N',0,null,0,'paydate','erm.jkzb.paydate',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,7,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9N',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintuser',0,'N',1,'N','N',0,null,0,'officialprintuser','erm.jkzb.officialprintuser',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,8,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005K9O',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintdate',0,'N',1,'N','N',0,null,0,'officialprintdate','erm.jkzb.officialprintdate',null,'N',0,null,'1001Z310000000005K3A','@@@@',2,null,null,null,'N',0,9,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEW',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_jkbx',0,'N',1,'N','N',0,null,0,'pk_jkbx','erm.jkzb.pk_jkbx',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',0,9,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEX',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',0,null,0,'pk_org','erm.jkzb.pk_org',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,3,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEY',1,-1,null,null,0,1,null,-1,'N',null,-1,'djlxbm',0,'N',1,'N','N',0,null,0,'djlxbm','erm.jkzb.djlxbm',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',0,10,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'zy',0,'N',1,'N','N',0,null,0,'zy','erm.jkzb.zy',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',0,6,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFF0',1,-1,null,null,0,1,null,-1,'N',null,-1,'deptid',0,'N',1,'N','Y',0,null,0,'deptid','erm.jkzb.deptid',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,8,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFF1',1,-1,null,null,0,1,null,-1,'N',null,-1,'ybje',0,'N',1,'N','Y',0,null,0,'ybje','erm.jkzb.ybje',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,4,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFF2',1,-1,null,null,0,1,null,-1,'N',null,-1,'djbh',0,'N',1,'N','Y',0,null,0,'djbh','erm.jkzb.djbh',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,1,'djbh','单据编号',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFF3',1,-1,null,null,0,1,null,-1,'N',null,-1,'djrq',0,'N',1,'N','Y',0,null,0,'djrq','erm.jkzb.djrq',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,2,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFF4',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkbxr',0,'N',1,'N','Y',0,null,0,'jkbxr','erm.jkzb.jkbxr',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,7,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFF5',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','Y',0,null,0,'bzbm','erm.jkzb.bzbm',null,'N',0,null,'1001Z310000000005K3A','@@@@',0,null,null,null,'N',1,5,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000IE1G',1,0,'事由',null,0,1,null,-1,'N',null,20,'zy2',null,'N',1,'N','Y',0,'zy2->zy_ID',0,null,null,null,'N',0,null,'1001Z310000000005K3A',null,0,null,null,null,'N',1,11,'djbh','单据编号',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

