/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.er.indauthorize;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-03-09 20:57:40
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class IndAuthorizeVO extends SuperVO {
	private java.lang.String pk_authorize;
	private java.lang.String pk_roler;
	private java.lang.String pk_user;
	private java.lang.String keyword;
	private java.lang.Integer type;
	private java.lang.String pk_operator;
	private nc.vo.pub.lang.UFDate startdate;
	private nc.vo.pub.lang.UFDate enddate;
	private java.lang.String billtype;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private java.lang.String pk_billtypeid;

	public static final String PK_AUTHORIZE = "pk_authorize";
	public static final String PK_ROLER = "pk_roler";
	public static final String PK_USER = "pk_user";
	public static final String KEYWORD = "keyword";
	public static final String PK_OPERATOR = "pk_operator";
	public static final String STARTDATE = "startdate";
	public static final String ENDDATE = "enddate";
	public static final String BILLTYPE = "billtype";
	public static final String PK_BILLTYPEID = "pk_billtypeid";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String TYPE = "type";
	
	public java.lang.String getPk_billtypeid() {
		return pk_billtypeid;
	}
	public void setPk_billtypeid(java.lang.String pkBilltypeid) {
		pk_billtypeid = pkBilltypeid;
	}
	
	/**
	 * 属性pk_authorize的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getPk_authorize () {
		return pk_authorize;
	}   
	/**
	 * 属性pk_authorize的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newPk_authorize java.lang.String
	 */
	public void setPk_authorize (java.lang.String newPk_authorize ) {
	 	this.pk_authorize = newPk_authorize;
	} 	  
	/**
	 * 属性pk_roler的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getPk_roler () {
		return pk_roler;
	}   
	/**
	 * 属性pk_roler的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newPk_roler java.lang.String
	 */
	public void setPk_roler (java.lang.String newPk_roler ) {
	 	this.pk_roler = newPk_roler;
	} 	  
	/**
	 * 属性pk_user的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getPk_user () {
		return pk_user;
	}   
	/**
	 * 属性pk_user的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newPk_user java.lang.String
	 */
	public void setPk_user (java.lang.String newPk_user ) {
	 	this.pk_user = newPk_user;
	} 	  
	/**
	 * 属性keyword的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getKeyword () {
		return keyword;
	}   
	/**
	 * 属性keyword的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newKeyword java.lang.String
	 */
	public void setKeyword (java.lang.String newKeyword ) {
	 	this.keyword = newKeyword;
	} 	  
	/**
	 * 属性type的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.Integer getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newType java.lang.String
	 */
	public void setType (java.lang.Integer newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性pk_operator的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getPk_operator () {
		return pk_operator;
	}   
	/**
	 * 属性pk_operator的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newPk_operator java.lang.String
	 */
	public void setPk_operator (java.lang.String newPk_operator ) {
	 	this.pk_operator = newPk_operator;
	} 	  
	/**
	 * 属性startdate的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getStartdate () {
		return startdate;
	}   
	/**
	 * 属性startdate的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newStartdate nc.vo.pub.lang.UFDate
	 */
	public void setStartdate (nc.vo.pub.lang.UFDate newStartdate ) {
	 	this.startdate = newStartdate;
	} 	  
	/**
	 * 属性enddate的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getEnddate () {
		return enddate;
	}   
	/**
	 * 属性enddate的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newEnddate nc.vo.pub.lang.UFDate
	 */
	public void setEnddate (nc.vo.pub.lang.UFDate newEnddate ) {
	 	this.enddate = newEnddate;
	} 	  
	/**
	 * 属性billtype的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getBilltype () {
		return billtype;
	}   
	/**
	 * 属性billtype的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newBilltype java.lang.String
	 */
	public void setBilltype (java.lang.String newBilltype ) {
	 	this.billtype = newBilltype;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-03-09 20:57:40
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-03-09 20:57:40
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-03-09 20:57:40
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_authorize";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-03-09 20:57:40
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_indauthorize";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-03-09 20:57:40
	  */
     public IndAuthorizeVO() {
		super();	
	}    
} 


