insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000CY1T',1,-1,null,null,0,1,null,-1,'N',null,-1,'type',0,'N',1,'N','N',0,null,0,'type','erm.IndAuthorize.type',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',0,13,'IndAuthorize','IndAuthorize',0,'2013-09-23 13:39:20','N',null,null,null,0,0,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000F04H',1,-1,'单据类型主键',null,0,1,null,-1,'N',null,-1,'billtype',0,'N',1,'N','N',0,null,0,'billtype','erm.IndAuthorize.billtype',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,'影响因素交 易类型,code=N,nl=N','UCMD1-000579',null,'N',0,11,'IndAuthorize','IndAuthorize',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS2',1,-1,'集团',null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,1,'pk_group','erm.IndAuthorize.pk_group',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,'UC001-0000072',null,'N',0,7,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS4',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','erm.IndAuthorize.ts',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',0,12,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS5',1,-1,null,null,0,1,null,-1,'N',null,-1,'enddate',0,'N',1,'N','Y',0,null,0,'enddate','erm.IndAuthorize.enddate',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',1,9,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS6',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_operator',0,'N',1,'N','Y',0,null,0,'pk_operator','erm.IndAuthorize.pk_operator',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,'用户,code=N',null,null,'N',1,5,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS7',1,-1,'所属组织',null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',0,null,0,'pk_org','erm.IndAuthorize.pk_org',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,'业务单元+集团,code=N','UCMD1-000129',null,'N',1,6,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS8',1,-1,null,null,0,1,null,-1,'N',null,-1,'startdate',0,'N',1,'N','Y',0,null,0,'startdate','erm.IndAuthorize.startdate',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',1,8,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQS9',1,-1,null,null,0,1,null,-1,'N',null,-1,'keyword',0,'N',1,'N','N',0,null,0,'keyword','erm.IndAuthorize.keyword',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',0,4,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQSA',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_user',0,'N',1,'N','N',0,null,0,'pk_user','erm.IndAuthorize.pk_user',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',0,3,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQSC',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_authorize',0,'N',1,'N','N',0,null,0,'pk_authorize','erm.IndAuthorize.pk_authorize',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',0,1,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GQSD',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_roler',0,'N',1,'N','N',0,null,0,'pk_roler','erm.IndAuthorize.pk_roler',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,null,null,null,'N',0,2,'IndAuthorize','授权代理设置',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000JWTM',1,-1,'交易类型',null,0,1,null,-1,'N',null,-1,'pk_billtypeid',0,'N',1,'N','Y',0,null,0,'pk_billtypeid','erm.IndAuthorize.pk_billtypeid',null,'N',0,null,'1001Z31000000000GQS1','@@@@',1,'影响因素交 易类型,code=N','UCMD1-000053',null,'N',1,10,'IndAuthorize','IndAuthorize',0,'2013-09-23 13:39:20','N',null,null,null,1,1,'N',1,null,100)
go

