/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.extendconfig;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ErmExtendConfigVO extends SuperVO {
	private java.lang.String pk_extendconfig;
	private java.lang.String busi_tabcode;
	private java.lang.String busi_tabname;
	private java.lang.String busi_tabname2;
	private java.lang.String busi_tabname3;
	private java.lang.String busi_tabname4;
	private java.lang.String busi_tabname5;
	private java.lang.String busi_tabname6;
	private java.lang.String cardclass;
	private java.lang.String listclass;
	private java.lang.String queryclass;
	private java.lang.String busi_sys;
	private java.lang.String cardlistenerclass;
	private java.lang.String listlistenerclass;
	private java.lang.Integer busitype = 0;
	private java.lang.String pk_tradetype;
	private java.lang.String pk_billtype;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private java.lang.String metadataclass;

	public static final String PK_EXTENDCONFIG = "pk_extendconfig";
	public static final String BUSI_TABCODE = "busi_tabcode";
	public static final String BUSI_TABNAME = "busi_tabname";
	public static final String BUSI_TABNAME2 = "busi_tabname2";
	public static final String BUSI_TABNAME3 = "busi_tabname3";
	public static final String BUSI_TABNAME4 = "busi_tabname4";
	public static final String BUSI_TABNAME5 = "busi_tabname5";
	public static final String BUSI_TABNAME6 = "busi_tabname6";
	public static final String CARDCLASS = "cardclass";
	public static final String LISTCLASS = "listclass";
	public static final String QUERYCLASS = "queryclass";
	public static final String BUSI_SYS = "busi_sys";
	public static final String CARDLISTENERCLASS = "cardlistenerclass";
	public static final String LISTLISTENERCLASS = "listlistenerclass";
	public static final String BUSITYPE = "busitype";
	public static final String PK_TRADETYPE = "pk_tradetype";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String METADATACLASS = "metadataclass";
			
	/**
	 * 属性pk_extendconfig的Getter方法.属性名：唯一标识
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_extendconfig () {
		return pk_extendconfig;
	}   
	/**
	 * 属性pk_extendconfig的Setter方法.属性名：唯一标识
	 * 创建日期:
	 * @param newPk_extendconfig java.lang.String
	 */
	public void setPk_extendconfig (java.lang.String newPk_extendconfig ) {
	 	this.pk_extendconfig = newPk_extendconfig;
	} 	  
	/**
	 * 属性busi_tabcode的Getter方法.属性名：业务页签编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabcode () {
		return busi_tabcode;
	}   
	/**
	 * 属性busi_tabcode的Setter方法.属性名：业务页签编码
	 * 创建日期:
	 * @param newBusi_tabcode java.lang.String
	 */
	public void setBusi_tabcode (java.lang.String newBusi_tabcode ) {
	 	this.busi_tabcode = newBusi_tabcode;
	} 	  
	/**
	 * 属性busi_tabname的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabname () {
		return busi_tabname;
	}   
	/**
	 * 属性busi_tabname的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newBusi_tabname java.lang.String
	 */
	public void setBusi_tabname (java.lang.String newBusi_tabname ) {
	 	this.busi_tabname = newBusi_tabname;
	} 	  
	/**
	 * 属性busi_tabname2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabname2 () {
		return busi_tabname2;
	}   
	/**
	 * 属性busi_tabname2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newBusi_tabname2 java.lang.String
	 */
	public void setBusi_tabname2 (java.lang.String newBusi_tabname2 ) {
	 	this.busi_tabname2 = newBusi_tabname2;
	} 	  
	/**
	 * 属性busi_tabname3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabname3 () {
		return busi_tabname3;
	}   
	/**
	 * 属性busi_tabname3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newBusi_tabname3 java.lang.String
	 */
	public void setBusi_tabname3 (java.lang.String newBusi_tabname3 ) {
	 	this.busi_tabname3 = newBusi_tabname3;
	} 	  
	/**
	 * 属性busi_tabname4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabname4 () {
		return busi_tabname4;
	}   
	/**
	 * 属性busi_tabname4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newBusi_tabname4 java.lang.String
	 */
	public void setBusi_tabname4 (java.lang.String newBusi_tabname4 ) {
	 	this.busi_tabname4 = newBusi_tabname4;
	} 	  
	/**
	 * 属性busi_tabname5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabname5 () {
		return busi_tabname5;
	}   
	/**
	 * 属性busi_tabname5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newBusi_tabname5 java.lang.String
	 */
	public void setBusi_tabname5 (java.lang.String newBusi_tabname5 ) {
	 	this.busi_tabname5 = newBusi_tabname5;
	} 	  
	/**
	 * 属性busi_tabname6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_tabname6 () {
		return busi_tabname6;
	}   
	/**
	 * 属性busi_tabname6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newBusi_tabname6 java.lang.String
	 */
	public void setBusi_tabname6 (java.lang.String newBusi_tabname6 ) {
	 	this.busi_tabname6 = newBusi_tabname6;
	} 	  
	/**
	 * 属性cardclass的Getter方法.属性名：卡片实现类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCardclass () {
		return cardclass;
	}   
	/**
	 * 属性cardclass的Setter方法.属性名：卡片实现类
	 * 创建日期:
	 * @param newCardclass java.lang.String
	 */
	public void setCardclass (java.lang.String newCardclass ) {
	 	this.cardclass = newCardclass;
	} 	  
	/**
	 * 属性listclass的Getter方法.属性名：列表实现类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getListclass () {
		return listclass;
	}   
	/**
	 * 属性listclass的Setter方法.属性名：列表实现类
	 * 创建日期:
	 * @param newListclass java.lang.String
	 */
	public void setListclass (java.lang.String newListclass ) {
	 	this.listclass = newListclass;
	} 	  
	/**
	 * 属性queryclass的Getter方法.属性名：查询实现类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQueryclass () {
		return queryclass;
	}   
	/**
	 * 属性queryclass的Setter方法.属性名：查询实现类
	 * 创建日期:
	 * @param newQueryclass java.lang.String
	 */
	public void setQueryclass (java.lang.String newQueryclass ) {
	 	this.queryclass = newQueryclass;
	} 	  
	/**
	 * 属性busi_sys的Getter方法.属性名：业务系统
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_sys () {
		return busi_sys;
	}   
	/**
	 * 属性busi_sys的Setter方法.属性名：业务系统
	 * 创建日期:
	 * @param newBusi_sys java.lang.String
	 */
	public void setBusi_sys (java.lang.String newBusi_sys ) {
	 	this.busi_sys = newBusi_sys;
	} 	  
	/**
	 * 属性cardlistenerclass的Getter方法.属性名：卡片事件监听器
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCardlistenerclass () {
		return cardlistenerclass;
	}   
	/**
	 * 属性cardlistenerclass的Setter方法.属性名：卡片事件监听器
	 * 创建日期:
	 * @param newCardlistenerclass java.lang.String
	 */
	public void setCardlistenerclass (java.lang.String newCardlistenerclass ) {
	 	this.cardlistenerclass = newCardlistenerclass;
	} 	  
	/**
	 * 属性listlistenerclass的Getter方法.属性名：列表事件监听器
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getListlistenerclass () {
		return listlistenerclass;
	}   
	/**
	 * 属性listlistenerclass的Setter方法.属性名：列表事件监听器
	 * 创建日期:
	 * @param newListlistenerclass java.lang.String
	 */
	public void setListlistenerclass (java.lang.String newListlistenerclass ) {
	 	this.listlistenerclass = newListlistenerclass;
	} 	  
	/**
	 * 属性busitype的Getter方法.属性名：费用单据业务类型
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getBusitype () {
		return busitype;
	}   
	/**
	 * 属性busitype的Setter方法.属性名：费用单据业务类型
	 * 创建日期:
	 * @param newBusitype java.lang.Integer
	 */
	public void setBusitype (java.lang.Integer newBusitype ) {
	 	this.busitype = newBusitype;
	} 	  
	/**
	 * 属性pk_tradetype的Getter方法.属性名：费用单据交易类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_tradetype () {
		return pk_tradetype;
	}   
	/**
	 * 属性pk_tradetype的Setter方法.属性名：费用单据交易类型
	 * 创建日期:
	 * @param newPk_tradetype java.lang.String
	 */
	public void setPk_tradetype (java.lang.String newPk_tradetype ) {
	 	this.pk_tradetype = newPk_tradetype;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.属性名：费用单据单据类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.属性名：费用单据单据类型
	 * 创建日期:
	 * @param newPk_billtype java.lang.String
	 */
	public void setPk_billtype (java.lang.String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_extendconfig";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_extendconfig";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_extendconfig";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ErmExtendConfigVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.erm.extendconfig.ErmExtendConfigVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
	public java.lang.String getMetadataclass() {
		return metadataclass;
	}
	public void setMetadataclass(java.lang.String metadataclass) {
		this.metadataclass = metadataclass;
	}
} 


