insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000SJ1R','-99',3,0,1,'0',null,'djrq','单据日期',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000SJ1I',null,'UC000-0000799',2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000SJ1V','组织单元',5,1,1,'0',null,'pk_org','借款单位',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000SJ1I',null,'120111LLA10001',2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000SJS5','人员基本信息',5,2,1,'0',null,'jkbxr','借款报销人',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000SJ1I',null,'120111LLA10002',2,null,null,'2013-09-23 13:40:05','N',null)
go

