insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbhl',null,'N',1,'N','N',null,0,'groupbbhl','erm.expamtinfo.groupbbhl',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,18,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SK',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','N',null,0,'creationtime','erm.expamtinfo.creationtime',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,28,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SL',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_orgamount',null,'N',1,'N','N',null,0,'accu_orgamount','erm.expamtinfo.accu_orgamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,34,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SM',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_amount',null,'N',1,'N','Y',null,0,'res_amount','erm.expamtinfo.res_amount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,10,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SN',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_orgamount',null,'N',1,'N','N',null,0,'res_orgamount','erm.expamtinfo.res_orgamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,22,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SO',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_groupamount',null,'N',1,'N','N',null,0,'accu_groupamount','erm.expamtinfo.accu_groupamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,35,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SP',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_expamtinfo',null,'N',1,'N','N',null,0,'pk_expamtinfo','erm.expamtinfo.pk_expamtinfo',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,3,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',null,'N',1,'N','N',null,0,'modifier','erm.expamtinfo.modifier',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,29,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SR',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_period',null,'N',1,'N','Y',null,0,'res_period','erm.expamtinfo.res_period',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,13,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SS',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_globalamount',null,'N',1,'N','N',null,0,'accu_globalamount','erm.expamtinfo.accu_globalamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,36,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5ST',1,-1,null,null,0,1,null,-1,'N',null,-1,'billstatus',null,'N',1,'N','N',null,0,'billstatus','erm.expamtinfo.billstatus',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,37,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SU',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_orgamount',null,'N',1,'N','N',null,0,'curr_orgamount','erm.expamtinfo.curr_orgamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,31,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SV',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbje',null,'N',1,'N','N',null,0,'groupbbje','erm.expamtinfo.groupbbje',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,21,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SW',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','erm.expamtinfo.pk_org',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,25,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SX',1,-1,null,null,0,1,null,-1,'N',null,-1,'bx_billno',null,'N',1,'N','Y',null,0,'bx_billno','erm.expamtinfo.bx_billno',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,4,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5SZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbhl',null,'N',1,'N','N',null,0,'bbhl','erm.expamtinfo.bbhl',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,16,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T1',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_amount',null,'N',1,'N','Y',null,0,'accu_amount','erm.expamtinfo.accu_amount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,9,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T2',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_globalamount',null,'N',1,'N','N',null,0,'curr_globalamount','erm.expamtinfo.curr_globalamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,33,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T3',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_jkbx',null,'N',1,'N','N',null,0,'pk_jkbx','erm.expamtinfo.pk_jkbx',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,5,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T4',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','N',null,0,'modifiedtime','erm.expamtinfo.modifiedtime',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,30,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T5',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','erm.expamtinfo.ts',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,38,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T6',1,-1,'本期摊销状态','false',0,1,null,-1,'N',null,-1,'amt_status',null,'N',1,'N','Y',null,0,'amt_status','erm.expamtinfo.amt_status',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,'12011erm0036',null,'N',1,40,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T7',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbje',null,'N',1,'N','N',null,0,'globalbbje','erm.expamtinfo.globalbbje',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,20,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T8',1,-1,null,null,0,1,null,-1,'N',null,-1,'start_period',null,'N',1,'N','N',null,0,'start_period','erm.expamtinfo.start_period',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,14,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5T9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','erm.expamtinfo.pk_group',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,26,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TB',1,-1,null,null,0,1,null,-1,'N',null,-1,'total_amount',null,'N',1,'N','Y',null,0,'total_amount','erm.expamtinfo.total_amount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,7,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TC',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_groupamount',null,'N',1,'N','N',null,0,'curr_groupamount','erm.expamtinfo.curr_groupamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,32,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TD',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',null,'N',1,'N','Y',null,0,'bzbm','erm.expamtinfo.bzbm',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,6,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TE',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',null,'N',1,'N','N',null,0,'creator','erm.expamtinfo.creator',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,27,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TG',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbje',null,'N',1,'N','N',null,0,'bbje','erm.expamtinfo.bbje',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,19,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TH',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_period',null,'N',1,'N','Y',null,0,'accu_period','erm.expamtinfo.accu_period',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,12,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TI',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_amount',null,'N',1,'N','Y',null,0,'curr_amount','erm.expamtinfo.curr_amount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,8,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_globalamount',null,'N',1,'N','N',null,0,'res_globalamount','erm.expamtinfo.res_globalamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,24,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TK',1,-1,null,null,0,1,null,-1,'N',null,-1,'end_period',null,'N',1,'N','N',null,0,'end_period','erm.expamtinfo.end_period',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,15,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TL',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_groupamount',null,'N',1,'N','N',null,0,'res_groupamount','erm.expamtinfo.res_groupamount',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,23,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TM',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbhl',null,'N',1,'N','N',null,0,'globalbbhl','erm.expamtinfo.globalbbhl',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,17,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D5TN',1,-1,null,null,0,1,null,-1,'N',null,-1,'total_period',null,'N',1,'N','Y',null,0,'total_period','erm.expamtinfo.total_period',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',1,11,'expamtinfo','费用待摊摊销信息',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002ICC8',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_billtype',null,'N',1,'N','N',null,0,'pk_billtype','erm.expamtinfo.pk_billtype',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,null,null,'N',0,39,'expamtinfo','expamtinfo',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002L664',1,-1,'交易类型',null,0,0,null,-1,'N','pk_jkbx',-1,'pk_jkbx.djlxbm',0,'N',1,'N','Y','pk_jkbx.djlxbm->getmlcvalue("bd_billtype","billtypename","pk_billtypecode",pk_jkbx.djlxbm)',0,'djlxbm','erm.bxzb.djlxbm',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,'12011erm0035',null,'N',1,2,'expamtinfo','expamtinfo',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000030Y2M',1,-1,'摘要',null,0,1,null,-1,'N',null,-1,'zy',null,'N',1,'N','Y',null,0,'zy','erm.expamtinfo.zy',null,'N',0,null,'1001Z310000000009SMZ',null,0,null,'12011erm0037',null,'N',1,1,'expamtinfo','expamtinfo',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,1)
go

