insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU7',1,-1,'审批日期',null,0,0,null,-1,'N',null,-1,'shrq',0,'N',1,'N','N',null,0,'shrq','erm.bxzb.shrq',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,'UC000-0001568',null,'N',0,3,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU8',1,-1,'最后修改人',null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','erm.bxzb.modifier',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,'UC001-0000116',null,'N',0,3,'audit',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU9',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsr',0,'N',1,'N','N',null,0,'jsr','erm.bxzb.jsr',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,4,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WUA',1,-1,'最后修改时间',null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','erm.bxzb.modifiedtime',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,'UC001-0000117',null,'N',0,4,'audit',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WUB',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsrq',0,'N',1,'N','N',null,0,'jsrq','erm.bxzb.jsrq',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,5,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WUC',1,-1,null,null,0,0,null,-1,'N',null,-1,'payman',0,'N',1,'N','N',null,0,'payman','erm.bxzb.payman',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,6,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WUD',1,-1,null,null,0,0,null,-1,'N',null,-1,'paydate',0,'N',1,'N','N',null,0,'paydate','erm.bxzb.paydate',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,7,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WUE',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintuser',0,'N',1,'N','N',null,0,'officialprintuser','erm.bxzb.officialprintuser',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,8,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WUF',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintdate',0,'N',1,'N','N',null,0,'officialprintdate','erm.bxzb.officialprintdate',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,9,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFDX',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','erm.bxzb.pk_org',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,3,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFDY',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_jkbx',0,'N',1,'N','N',null,0,'pk_jkbx','erm.bxzb.pk_jkbx',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',0,9,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFDZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'deptid',0,'N',1,'N','Y',null,0,'deptid','erm.bxzb.deptid',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,8,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE0',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkbxr',0,'N',1,'N','Y',null,0,'jkbxr','erm.bxzb.jkbxr',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,7,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE1',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','Y',null,0,'bzbm','erm.bxzb.bzbm',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,5,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE3',1,-1,null,null,0,1,null,-1,'N',null,-1,'djlxbm',0,'N',1,'N','N',null,0,'djlxbm','erm.bxzb.djlxbm',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',0,10,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE4',1,-1,null,null,0,1,null,-1,'N',null,-1,'zy',0,'N',1,'N','N',null,0,'zy','erm.bxzb.zy',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',0,6,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE5',1,-1,null,null,0,1,null,-1,'N',null,-1,'djbh',0,'N',1,'N','Y',null,0,'djbh','erm.bxzb.djbh',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,1,'djbh','单据编号',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE6',1,-1,null,null,0,1,null,-1,'N',null,-1,'djrq',0,'N',1,'N','Y',null,0,'djrq','erm.bxzb.djrq',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,2,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000IE4I',1,0,'事由',null,0,1,null,-1,'N',null,20,'zy2',0,'N',1,'N','Y','zy2->zy_ID',0,null,null,null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,11,'djbh','单据编号',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU3',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','erm.bxzb.creator',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,'用户,dpc=fi',null,null,'N',0,1,'audit',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU4',1,-1,null,null,0,0,null,-1,'N',null,-1,'shrq_show',0,'N',1,'N','N',null,0,'shrq_show','erm.bxzb.shrq_show',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,2,'tail','tail',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU5',1,5,'审批人',null,0,0,null,-1,'N',null,20,'approver',0,'N',1,'N','N',null,0,'approver','erm.bxzb.approver',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,'用户,dpc=fi','UC000-0001559',null,'N',0,1,'tail',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WU6',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','erm.bxzb.creationtime',null,'N',0,null,'1001Z310000000006WO4','@@@@',2,null,null,null,'N',0,2,'audit',null,0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFE2',1,-1,null,null,0,1,null,-1,'N',null,-1,'ybje',0,'N',1,'N','Y',null,0,'ybje','erm.bxzb.ybje',null,'N',0,null,'1001Z310000000006WO4','@@@@',0,null,null,null,'N',1,4,'djbh','djbh',0,'2013-09-23 13:39:21','N',null,null,null,1,1,'N',1,null,1)
go

