insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WW',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbhl',0,'N',1,'N','N',null,0,'globalbbhl','erm.expamtproc.globalbbhl',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,19,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WX',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbje',0,'N',1,'N','N',null,0,'globalbbje','erm.expamtproc.globalbbje',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,22,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','erm.expamtproc.modifiedtime',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,8,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','erm.expamtproc.pk_group',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,10,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X1',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_orgamount',0,'N',1,'N','N',null,0,'curr_orgamount','erm.expamtproc.curr_orgamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,29,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X2',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_expamtinfo',0,'N',1,'N','N',null,0,'pk_expamtinfo','erm.expamtproc.pk_expamtinfo',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,2,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X3',1,-1,null,null,0,1,null,-1,'N',null,-1,'end_period',0,'N',1,'N','N',null,0,'end_period','erm.expamtproc.end_period',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,16,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X4',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','erm.expamtproc.ts',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,37,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X5',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_globalamount',0,'N',1,'N','N',null,0,'curr_globalamount','erm.expamtproc.curr_globalamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,31,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X6',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_orgamount',0,'N',1,'N','N',null,0,'res_orgamount','erm.expamtproc.res_orgamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,24,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X7',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','erm.expamtproc.creator',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,5,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X8',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbje',0,'N',1,'N','N',null,0,'bbje','erm.expamtproc.bbje',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,21,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4X9',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbje',0,'N',1,'N','N',null,0,'groupbbje','erm.expamtproc.groupbbje',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,23,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XA',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbhl',0,'N',1,'N','N',null,0,'bbhl','erm.expamtproc.bbhl',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,18,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XB',1,-1,null,null,0,1,null,-1,'N',null,-1,'amortize_user',0,'N',1,'N','N',null,0,'amortize_user','erm.expamtproc.amortize_user',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,35,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XC',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_amount',0,'N',1,'N','N',null,0,'accu_amount','erm.expamtproc.accu_amount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,28,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XD',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbhl',0,'N',1,'N','N',null,0,'groupbbhl','erm.expamtproc.groupbbhl',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,20,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XE',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','erm.expamtproc.modifier',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,7,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XF',1,-1,'会计期间',null,0,1,null,-1,'N',null,-1,'accperiod',0,'N',1,'N','Y',null,0,'accperiod','erm.expamtproc.accperiod',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,'UC000-0000240',null,'N',1,1,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XG',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_amount',0,'N',1,'N','N',null,0,'res_amount','erm.expamtproc.res_amount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,14,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XH',1,-1,null,null,0,1,null,-1,'N',null,-1,'total_period',0,'N',1,'N','N',null,0,'total_period','erm.expamtproc.total_period',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,11,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XI',1,-1,null,null,0,1,null,-1,'N',null,-1,'start_period',0,'N',1,'N','N',null,0,'start_period','erm.expamtproc.start_period',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,15,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_orgamount',0,'N',1,'N','N',null,0,'accu_orgamount','erm.expamtproc.accu_orgamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,32,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XK',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_period',0,'N',1,'N','N',null,0,'res_period','erm.expamtproc.res_period',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,13,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XL',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_groupamount',0,'N',1,'N','N',null,0,'res_groupamount','erm.expamtproc.res_groupamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,25,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XM',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','erm.expamtproc.pk_org',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,9,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XN',1,-1,'摊销金额',null,0,1,null,-1,'N',null,-1,'curr_amount',0,'N',1,'N','Y',null,0,'curr_amount','erm.expamtproc.curr_amount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,'12011erm0002',null,'N',1,2,'expamtproc','费用摊销过程记录',1,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XP',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','erm.expamtproc.creationtime',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,6,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','N',null,0,'bzbm','erm.expamtproc.bzbm',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,0,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_globalamount',0,'N',1,'N','N',null,0,'accu_globalamount','erm.expamtproc.accu_globalamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,34,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WR',1,-1,null,null,0,1,null,-1,'N',null,-1,'curr_groupamount',0,'N',1,'N','N',null,0,'curr_groupamount','erm.expamtproc.curr_groupamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,30,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WY',1,-1,null,null,0,1,null,-1,'N',null,-1,'amortize_date',0,'N',1,'N','N',null,0,'amortize_date','erm.expamtproc.amortize_date',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,36,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WT',1,-1,null,null,0,1,null,-1,'N',null,-1,'res_globalamount',0,'N',1,'N','N',null,0,'res_globalamount','erm.expamtproc.res_globalamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,26,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WU',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_expamtproc',0,'N',1,'N','N',null,0,'pk_expamtproc','erm.expamtproc.pk_expamtproc',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,1,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WV',1,-1,null,null,0,1,null,-1,'N',null,-1,'total_amount',0,'N',1,'N','N',null,0,'total_amount','erm.expamtproc.total_amount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,12,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4WS',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_period',0,'N',1,'N','N',null,0,'accu_period','erm.expamtproc.accu_period',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,27,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000R4XO',1,-1,null,null,0,1,null,-1,'N',null,-1,'accu_groupamount',0,'N',1,'N','N',null,0,'accu_groupamount','erm.expamtproc.accu_groupamount',null,'N',0,null,'1001Z31000000000R4WP','@@@@',0,null,null,null,'N',0,33,'expamtproc','费用摊销过程记录',0,'2013-09-23 13:39:45','N',null,null,null,1,1,'N',1,null,1)
go

