insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSH','-99',0,7,0,'0',0,'mngaccid','管理账户',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSI','2',2,8,0,'0',0,'total','合计金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSJ','-99',3,9,0,'0',0,'paydate','支付日期',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSK','用户',5,10,0,'0',0,'payman','支付人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSL','IM,ce225279-a5be-431e-864a-746747c8a7bb',6,11,0,'0',0,'payflag','支付状态',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=@<>@','等于@不等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSM','资金计划项目',5,12,0,'0',0,'cashproj','资金计划项目',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSN','业务单元',5,13,0,'0',0,'fydwbm','费用承担单位',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSO','行政组织',5,14,0,'0',0,'dwbm','报销人单位',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSP','-99',0,15,0,'0',0,'pk_jkbx','报销单标识',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSQ','-99',0,16,0,'0',0,'djdl','单据大类',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSR','费用交易类型',5,17,1,'0',0,'djlxbm','交易类型',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,'2UC000-000035',0,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTS','-99',0,54,0,'0',0,'zyx2','自定义项2',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUF','-99',0,77,0,'0',0,'zyx14','自定义项14',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUG','-99',0,78,0,'0',0,'zyx13','自定义项13',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUH','-99',0,79,0,'0',0,'zyx12','自定义项12',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUI','-99',0,80,0,'0',0,'zyx11','自定义项11',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUJ','-99',0,81,0,'0',0,'zyx10','自定义项10',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUK','-99',0,82,0,'0',0,'zyx9','自定义项9',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUL','IM,6d3eb44c-db5a-45a5-812a-3a040a3746af',6,83,0,'0',0,'spzt','审批状态',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=@<>@','等于@不等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUM','-99',4,84,0,'0',0,'qcbz','期初标志',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=@','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUE','-99',0,76,0,'0',0,'zyx15','自定义项15',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTI','2',2,44,0,'0',0,'bbhl','本币汇率',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTJ','2',2,45,0,'0',0,'ybje','报销原币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTK','2',2,46,0,'0',0,'bbje','报销本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTL','-99',0,47,0,'0',0,'zy','事由',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','N',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTM','供应商档案',5,48,0,'0',0,'hbbm','供应商',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTN','-99',1,49,0,'0',0,'fjzs','附件张数',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTO','IM,aed2a08a-03a0-4db7-9ab1-c30e1dc1ca17',6,50,0,'0',0,'djzt','单据状态',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=@<>@','等于@不等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTP','-99',0,51,0,'0',0,'jsh','结算号',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTQ','-99',4,52,0,'0',0,'ischeck','是否限额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=@','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTR','-99',0,53,0,'0',0,'zyx1','自定义项1',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTT','-99',0,55,0,'0',0,'zyx3','自定义项3',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTU','-99',0,56,0,'0',0,'zyx4','自定义项4',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTV','-99',0,57,0,'0',0,'zyx5','自定义项5',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTW','-99',0,58,0,'0',0,'zyx6','自定义项6',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTX','-99',0,59,0,'0',0,'zyx7','自定义项7',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTY','-99',0,60,0,'0',0,'zyx8','自定义项8',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTZ','-99',0,61,0,'0',0,'zyx30','自定义项30',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU0','-99',0,62,0,'0',0,'zyx29','自定义项29',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU1','-99',0,63,0,'0',0,'zyx28','自定义项28',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT1','用户',5,27,0,'0',0,'modifier','最终修改人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU3','-99',0,65,0,'0',0,'zyx26','自定义项26',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU4','-99',0,66,0,'0',0,'zyx25','自定义项25',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU5','-99',0,67,0,'0',0,'zyx24','自定义项24',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU6','-99',0,68,0,'0',0,'zyx23','自定义项23',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU7','-99',0,69,0,'0',0,'zyx22','自定义项22',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU8','-99',0,70,0,'0',0,'zyx21','自定义项21',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU9','-99',0,71,0,'0',0,'zyx20','自定义项20',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUA','-99',0,72,0,'0',0,'zyx19','自定义项19',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSA','财务组织',5,0,0,'0',null,'pk_org','报销单位',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSB','集团',5,1,0,'0',null,'pk_group','集团',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSC','-99',0,2,0,'0',0,'pk_org_v','业务单元版本',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','N',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSD','财务组织',5,3,0,'0',0,'pk_fiorg','财务组织',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTD','-99',0,39,0,'0',0,'szxmid','收支项目',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSE','利润中心',5,4,0,'0',0,'pk_pcorg','利润中心',null,'N','Y','N','N','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSF','-99',0,5,0,'0',0,'pk_checkele','核算要素',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSG','-99',0,6,0,'0',0,'reimrule','报销规则',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUX','2',2,95,0,'0',0,'globalcjkbbje','全局冲借款本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUY','2',2,96,0,'0',0,'globalhkbbje','全局还款本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUZ','2',2,97,0,'0',0,'globalzfbbje','全局支付本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV0','2',2,98,0,'0',0,'globalbbje','全局报销本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLU2','-99',0,64,0,'0',0,'zyx27','自定义项27',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSZ','用户',5,25,0,'0',0,'operator','录入人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV2','2',2,100,0,'0',0,'grouphkbbje','集团还款本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV3','2',2,101,0,'0',0,'groupzfbbje','集团支付本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV4','2',2,102,0,'0',0,'groupbbje','集团报销本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV5','2',2,103,0,'0',0,'globalbbhl','全局本币汇率',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV6','2',2,104,0,'0',0,'groupbbhl','集团本币汇率',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV7','-99',3,105,0,'0',0,'creationtime','创建时间',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV8','-99',3,106,0,'0',0,'modifiedtime','修改时间',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV9','用户',5,107,0,'0',0,'creator','创建人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLVA','-99',0,108,0,'0',0,'custaccount','客商银行账号',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLVB','-99',0,109,0,'0',0,'freecust','散户',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLV1','2',2,99,0,'0',0,'groupcjkbbje','集团冲借款本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTB','2',2,37,0,'0',0,'zfbbje','支付本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTC','项目',5,38,0,'0',0,'jobid','项目',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTE','现金流量项目',5,40,0,'0',0,'cashitem','现金流量项目',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTF','部门',5,41,0,'0',0,'fydeptid','费用承担部门',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTG','-99',0,42,0,'0',0,'pk_item','事项审批单',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTH','币种档案',5,43,0,'0',0,'bzbm','币种',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSS','-99',0,18,0,'0',0,'djbh','单据编号',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLST','-99',3,19,0,'0',0,'djrq','单据日期',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSU','-99',3,20,0,'0',0,'shrq','审核日期',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSV','-99',3,21,0,'0',0,'jsrq','结算日期',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSW','部门',5,22,0,'0',0,'deptid','报销部门',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSX','人员',5,23,0,'0',0,'receiver','收款人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLSY','人员',5,24,0,'0',0,'jkbxr','借款报销人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT0','用户',5,26,0,'0',0,'approver','审批人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT2','结算方式',5,28,0,'0',0,'jsfs','结算方式',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT3','-99',0,29,0,'0',0,'pjh','票据号',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT4','个人银行账户',5,30,0,'0',0,'skyhzh','个人银行账号',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT5','银行账户',5,31,0,'0',0,'fkyhzh','单位银行账号',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT6','2',2,32,0,'0',0,'cjkybje','冲借款原币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT7','2',2,33,0,'0',0,'cjkbbje','冲借款本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT8','2',2,34,0,'0',0,'hkybje','还款原币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLT9','2',2,35,0,'0',0,'hkbbje','还款本币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLTA','2',2,36,0,'0',0,'zfybje','支付原币金额',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUB','-99',0,73,0,'0',0,'zyx18','自定义项18',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUC','-99',0,74,0,'0',0,'zyx17','自定义项17',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUD','-99',0,75,0,'0',0,'zyx16','自定义项16',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUO','-99',0,86,0,'0',0,'kjnd','会计年度',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUP','用户',5,87,0,'0',0,'jsr','结算人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUQ','-99',3,88,0,'0',0,'officialprintdate','正式打印日期',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','Y','Y',null,'Y',null,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUR','用户',5,89,0,'0',0,'officialprintuser','正式打印人',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUS','-99',0,90,0,'0',0,'busitype','业务类型',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUT','-99',0,91,0,'0',0,'er_bxcontrast','报销单冲销对照行',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUU','-99',0,92,0,'0',0,'er_busitem','报销单业务行',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUW','IM,f61cd296-3d55-4b1d-8428-bda54ae64d6a',6,94,0,'0',0,'sxbz','生效状态',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'=@<>@','等于@不等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000LLUN','-99',0,85,0,'0',0,'kjqj','会计期间',null,'N','Y','N','Y','N','N','N',null,'N',null,'N','N','N','N','Y',null,'Y',null,null,'like@=@>@>=@<@<=@','包含@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000LLS9',null,null,2,null,null,'2013-09-23 13:40:05','N',null)
go

