insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZB',1,-1,null,null,0,0,null,-1,'N',null,-1,'bxdjbh',0,'N',1,'N','N',null,0,'bxdjbh','erm.contrast.bxdjbh',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,20,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZD',1,-1,null,null,0,0,null,-1,'N',null,-1,'sxbz',0,'N',1,'N','N',null,0,'sxbz','erm.contrast.sxbz',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,21,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZF',1,-1,null,null,0,0,null,-1,'N',null,-1,'groupfybbje',0,'N',1,'N','N',null,0,'groupfybbje','erm.contrast.groupfybbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,22,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZH',1,-1,null,null,0,0,null,-1,'N',null,-1,'groupbbje',0,'N',1,'N','N',null,0,'groupbbje','erm.contrast.groupbbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,23,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZI',1,-1,null,null,0,0,null,-1,'N',null,-1,'groupcjkbbje',0,'N',1,'N','N',null,0,'groupcjkbbje','erm.contrast.groupcjkbbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,24,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZK',1,-1,null,null,0,0,null,-1,'N',null,-1,'globalfybbje',0,'N',1,'N','N',null,0,'globalfybbje','erm.contrast.globalfybbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,25,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZM',1,-1,null,null,0,0,null,-1,'N',null,-1,'globalbbje',0,'N',1,'N','N',null,0,'globalbbje','erm.contrast.globalbbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,26,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZO',1,-1,null,null,0,0,null,-1,'N',null,-1,'globalcjkbbje',0,'N',1,'N','N',null,0,'globalcjkbbje','erm.contrast.globalcjkbbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,27,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZR',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','erm.contrast.ts',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,28,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZS',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_finitem',0,'N',1,'N','N',null,0,'pk_finitem','erm.contrast.pk_finitem',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,29,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZV',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_bxcontrast',0,'N',1,'N','N',null,0,'pk_bxcontrast','erm.contrast.pk_bxcontrast',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,30,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X14',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','erm.bxzb.creator',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,'用户,dpc=fi',null,null,'N',0,1,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X15',1,-1,null,null,0,0,null,-1,'N',null,-1,'shrq_show',0,'N',1,'N','Y',null,0,'shrq_show','erm.bxzb.shrq_show',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,2,'tail','tail',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X16',1,5,null,null,0,0,null,-1,'N',null,20,'approver',0,'N',1,'N','Y',null,0,'approver','erm.bxzb.approver',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,'用户,dpc=fi',null,null,'N',0,1,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X17',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','erm.bxzb.creationtime',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,2,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X18',1,-1,null,null,0,0,null,-1,'N',null,-1,'shrq',0,'N',1,'N','N',null,0,'shrq','erm.bxzb.shrq',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,3,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X19',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','erm.bxzb.modifier',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,3,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1A',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsr',0,'N',1,'N','N',null,0,'jsr','erm.bxzb.jsr',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,4,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1B',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','erm.bxzb.modifiedtime',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,4,'audit',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1C',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsrq',0,'N',1,'N','N',null,0,'jsrq','erm.bxzb.jsrq',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,5,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1G',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintdate',0,'N',1,'N','N',null,0,'officialprintdate','erm.bxzb.officialprintdate',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,9,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1D',1,-1,null,null,0,0,null,-1,'N',null,-1,'payman',0,'N',1,'N','N',null,0,'payman','erm.bxzb.payman',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,6,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1E',1,-1,null,null,0,0,null,-1,'N',null,-1,'paydate',0,'N',1,'N','N',null,0,'paydate','erm.bxzb.paydate',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,7,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006X1F',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintuser',0,'N',1,'N','N',null,0,'officialprintuser','erm.bxzb.officialprintuser',null,'N',0,null,'1001Z310000000006WV5','@@@@',2,null,null,null,'N',0,8,'tail',null,0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEE',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','erm.bxzb.pk_org',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,3,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEF',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_jkbx',0,'N',1,'N','N',null,0,'pk_jkbx','erm.bxzb.pk_jkbx',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',0,9,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEG',1,-1,null,null,0,1,null,-1,'N',null,-1,'djlxbm',0,'N',1,'N','N',null,0,'djlxbm','erm.bxzb.djlxbm',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',0,10,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEH',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkbxr',0,'N',1,'N','Y',null,0,'jkbxr','erm.bxzb.jkbxr',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,7,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEI',1,-1,null,null,0,1,null,-1,'N',null,-1,'zy',0,'N',1,'N','N',null,0,'zy','erm.bxzb.zy',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',0,6,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','Y',null,0,'bzbm','erm.bxzb.bzbm',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,5,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEK',1,-1,null,null,0,1,null,-1,'N',null,-1,'ybje',0,'N',1,'N','Y',null,0,'ybje','erm.bxzb.ybje',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,4,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEL',1,-1,null,null,0,1,null,-1,'N',null,-1,'djrq',0,'N',1,'N','Y',null,0,'djrq','erm.bxzb.djrq',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,2,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEM',1,-1,null,null,0,1,null,-1,'N',null,-1,'deptid',0,'N',1,'N','Y',null,0,'deptid','erm.bxzb.deptid',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,8,'djbh','djbh',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000HFEN',1,-1,null,null,0,1,null,-1,'N',null,-1,'djbh',0,'N',1,'N','Y',null,0,'djbh','erm.bxzb.djbh',null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,null,null,'N',1,1,'djbh','单据编号',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000IE4R',1,0,'事由',null,0,1,null,-1,'N',null,20,'zy2',0,'N',1,'N','Y','zy2->zy_ID',0,null,null,null,'N',0,null,'1001Z310000000006WV5','@@@@',0,null,'120110tea0003',null,'N',1,11,'djbh','单据编号',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WY9',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkdjbh',0,'N',1,'N','N',null,0,'jkdjbh','erm.contrast.jkdjbh',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,1,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYB',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkbxr',0,'N',1,'N','N',null,0,'jkbxr','erm.contrast.jkbxr',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,'人员,code=N',null,null,'N',0,2,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYD',1,-1,null,null,0,1,null,-1,'N',null,-1,'deptid',0,'N',1,'N','N',null,0,'deptid','erm.contrast.deptid',null,'N',1,null,'1001Z310000000006WV5','@@@@',1,'部门,code=N',null,null,'N',0,3,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYF',1,-1,null,null,0,1,null,-1,'N',null,-1,'cjkybje',0,'N',1,'N','N',null,0,'cjkybje','erm.contrast.cjkybje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,4,'er_bxcontrast','er_bxcontrast',1,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYH',1,-1,null,null,0,1,null,-1,'N',null,-1,'fyybje',0,'N',1,'N','N',null,0,'fyybje','erm.contrast.fyybje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,5,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYI',1,-1,null,null,0,1,null,-1,'N',null,-1,'cxrq',0,'N',1,'N','N',null,0,'cxrq','erm.contrast.cxrq',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,6,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYK',1,-1,null,null,0,1,null,-1,'N',null,-1,'sxrq',0,'N',1,'N','N',null,0,'sxrq','erm.contrast.sxrq',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,7,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYM',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_bxd',0,'N',1,'N','N',null,0,'pk_bxd','erm.contrast.pk_bxd',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,8,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYP',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_jkd',0,'N',1,'N','N',null,0,'pk_jkd','erm.contrast.pk_jkd',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,9,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'fybbje',0,'N',1,'N','N',null,0,'fybbje','erm.contrast.fybbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,10,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYT',1,-1,null,null,0,0,null,-1,'N',null,-1,'cxnd',0,'N',1,'N','N',null,0,'cxnd','erm.contrast.cxnd',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,11,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYU',1,-1,null,null,0,0,null,-1,'N',null,-1,'cxqj',0,'N',1,'N','N',null,0,'cxqj','erm.contrast.cxqj',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,12,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYX',1,-1,null,null,0,0,null,-1,'N',null,-1,'ybje',0,'N',1,'N','N',null,0,'ybje','erm.contrast.ybje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,13,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WYY',1,-1,null,null,0,0,null,-1,'N',null,-1,'bbje',0,'N',1,'N','N',null,0,'bbje','erm.contrast.bbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,14,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZ0',1,-1,null,null,0,0,null,-1,'N',null,-1,'djlxbm',0,'N',1,'N','N',null,0,'djlxbm','erm.contrast.djlxbm',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,15,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZ3',1,-1,null,null,0,0,null,-1,'N',null,-1,'jobid',0,'N',1,'N','N',null,0,'jobid','erm.contrast.jobid',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,16,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZ5',1,-1,null,null,0,0,null,-1,'N',null,-1,'szxmid',0,'N',1,'N','N',null,0,'szxmid','erm.contrast.szxmid',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,17,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZ6',1,-1,null,null,0,0,null,-1,'N',null,-1,'cjkbbje',0,'N',1,'N','N',null,0,'cjkbbje','erm.contrast.cjkbbje',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,18,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006WZ9',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_pc',0,'N',1,'N','N',null,0,'pk_pc','erm.contrast.pk_pc',null,'N',0,null,'1001Z310000000006WV5','@@@@',1,null,null,null,'N',0,19,'er_bxcontrast','er_bxcontrast',0,'2013-09-23 13:39:30','N',null,null,null,1,1,'N',1,null,100)
go

