insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010016',null,'code','40d39c26-a2b6-4f16-a018-45664cac1a1f','name','pk_psndoc','人员','bd_psndoc',null,null,null,0,'billmaker','申请人','er_mtapp_detail',1,null,null,null,null,'erm','1','billmaker','zb',null,'qryobj_billmaker',null,'billmaker','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010017',null,'code','b26fa3cb-4087-4027-a3b6-c83ab2a086a9','name','pk_dept','部门','org_dept',null,null,null,0,'apply_dept','申请部门','er_mtapp_detail',1,null,null,null,null,'erm','1','apply_dept','zb',null,'qryobj_apply_dept',null,'apply_dept','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM1Z310000000015UYB',null,'cccode','de9796b5-bccd-42a1-97dd-808847bfddbd','ccname','pk_costcenter','管会成本中心','resa_costcenter','costcenter',null,null,0,'PK_RESACOSTCENTER','成本中心','zb',12,'N','Y',null,null,'erm',null,'PK_RESACOSTCENTER','zb',null,'qryobj_PK_RESACOSTCENTER',null,'pk_resacostcenter','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2000008',null,'code','b26fa3cb-4087-4027-a3b6-c83ab2a086a9','name','pk_dept','部门','org_dept',null,null,null,1,'deptid','报销人部门','zb',1,null,null,null,null,'erm','1','deptid','zb',null,'qryobj_bxrdeptid',null,'er_bxzb.deptid','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010001',null,'code','40d39c26-a2b6-4f16-a018-45664cac1a1f','name','pk_psndoc','人员','bd_psndoc',null,null,null,0,'jkbxr','借款人','zb',1,null,null,null,null,'erm','1','jkbxr','zb',null,'qryobj_jkr',null,'er_jkzb.jkbxr','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010002',null,'project_code','2ee58f9b-781b-469f-b1d8-1816842515c3','project_name','pk_project','项目','bd_project',null,null,null,0,'jobid','项目','zb',1,null,null,null,null,'erm','1','jobid','zb',null,'qryobj_jobid',null,'jobid','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010003',null,'code','b26fa3cb-4087-4027-a3b6-c83ab2a086a9','name','pk_dept','部门','org_dept',null,null,null,0,'deptid','借款人部门','zb',1,null,null,null,null,'erm','1','deptid','zb',null,'qryobj_jkrdeptid',null,'er_jkzb.deptid','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010004',null,'code','b26fa3cb-4087-4027-a3b6-c83ab2a086a9','name','pk_dept','部门','org_dept',null,null,null,0,'fydeptid','费用承担部门','zb',1,null,null,null,null,'erm','1','fydeptid','zb',null,'qryobj_fydeptid',null,'fydeptid','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010005',null,'code','283d91a4-a8f4-4763-ac44-aae7401fa09a','name','pk_inoutbusiclass','收支项目','bd_inoutbusiclass',null,null,null,0,'szxmid','收支项目','zb',1,null,null,null,null,'erm','1','szxmid','zb',null,'qryobj_szxmid',null,'szxmid','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010007',null,'code','985be8a4-3a36-4778-8afe-2d8ed3902659','name','pk_financeorg','业务单元','org_financeorg',null,null,null,0,'fydwbm','费用承担单位','zb',1,null,null,null,null,'erm','1','fydwbm','zb',null,'qryobj_fydwbm',null,'fydwbm','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010009',null,'code','7016ec17-4116-4b3c-abf1-37e3b5d815ef','name','pk_balatype','结算方式','bd_balatype',null,null,null,0,'jsfs','结算方式','zb',1,null,null,null,null,'erm','1','jsfs','zb',null,'qryobj_jsfs',null,'jsfs','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3PEDET201000001',null,'code','40d39c26-a2b6-4f16-a018-45664cac1a1f','name','pk_psndoc','人员','bd_psndoc',null,null,null,1,'jkbxr','报销人','zb',1,null,null,null,null,'erm','1','jkbxr','zb',null,'qryobj_bxr',null,'er_bxzb.jkbxr','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010010',null,'cccode','de9796b5-bccd-42a1-97dd-808847bfddbd','ccname','pk_costcenter','管会成本中心','resa_costcenter','costcenter',null,null,1,'PK_RESACOSTCENTER','成本中心','er_mtapp_detail',12,'N','Y',null,null,'erm',null,'PK_RESACOSTCENTER','zb',null,'qryobj_PK_RESACOSTCENTER',null,'pk_resacostcenter','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010011',null,'project_code','2ee58f9b-781b-469f-b1d8-1816842515c3','project_name','pk_project','项目','bd_project',null,null,null,1,'jobid','项目','er_mtapp_detail',1,null,null,null,null,'erm','1','pk_project','zb',null,'qryobj_jobid',null,'jobid','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010014',null,'code','283d91a4-a8f4-4763-ac44-aae7401fa09a','name','pk_inoutbusiclass','收支项目','bd_inoutbusiclass',null,null,null,1,'szxmid','收支项目','er_mtapp_detail',1,null,null,null,null,'erm','1','pk_iobsclass','zb',null,'qryobj_szxmid',null,'szxmid','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM1Z310000000015UYD',null,'cccode','de9796b5-bccd-42a1-97dd-808847bfddbd','ccname','pk_costcenter','管会成本中心','resa_costcenter','costcenter',null,null,0,'PK_RESACOSTCENTER','成本中心','cs',12,'N','Y',null,null,'erm',null,'PK_RESACOSTCENTER','zb',null,'qryobj_PK_RESACOSTCENTER',null,'pk_resacostcenter','2014-04-29 09:52:01')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2000010',null,'code','b26fa3cb-4087-4027-a3b6-c83ab2a086a9','name','pk_dept','部门','org_dept',null,null,null,0,'deptid','报销人部门','cs',1,null,null,null,null,'erm','1','bx_deptid','zb',null,'qryobj_bxrdeptid',null,'er_expenseaccount.bx_deptid','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010012',null,'project_code','2ee58f9b-781b-469f-b1d8-1816842515c3','project_name','pk_project','项目','bd_project',null,null,null,0,'jobid','项目','cs',1,null,null,null,null,'erm','1','pk_project','zb',null,'qryobj_jobid',null,'er_expenseaccount.pk_project','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010018',null,'code','b26fa3cb-4087-4027-a3b6-c83ab2a086a9','name','pk_dept','部门','org_dept',null,null,null,0,'fydeptid','费用承担部门','cs',1,null,null,null,null,'erm','1','assume_dept','zb',null,'qryobj_fydeptid',null,'er_expenseaccount.assume_dept','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010019',null,'code','283d91a4-a8f4-4763-ac44-aae7401fa09a','name','pk_inoutbusiclass','收支项目','bd_inoutbusiclass',null,null,null,0,'szxmid','收支项目','cs',1,null,null,null,null,'erm','1','pk_iobsclass','zb',null,'qryobj_szxmid',null,'er_expenseaccount.pk_iobsclass','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010020',null,'code','985be8a4-3a36-4778-8afe-2d8ed3902659','name','pk_financeorg','业务单元','org_financeorg',null,null,null,0,'fydwbm','费用承担单位','cs',1,null,null,null,null,'erm','1','assume_org','zb',null,'qryobj_fydwbm',null,'er_expenseaccount.assume_org','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3LOANDET2010022',null,'code','7016ec17-4116-4b3c-abf1-37e3b5d815ef','name','pk_balatype','结算方式','bd_balatype',null,null,null,0,'jsfs','结算方式','cs',1,null,null,null,null,'erm','1','bx_jsfs','zb',null,'qryobj_jsfs',null,'er_expenseaccount.bx_jsfs','2014-04-29 09:53:17')
go

insert into fipub_queryobj(pk_queryobj,balfieldname,bd_codefield,bd_mdid,bd_namefield,bd_pkfield,bd_refname,bd_tablename,billfieldname,creator,description,dr,dsp_objfieldname,dsp_objname,dsp_objtablename,dsp_order,iscreatebal,isqryobj,originfield,origintable,ownmodule,qry_objdatatype,qry_objfieldname,qry_objtablename,reporttype,resid,returntype,tallyfieldname,ts) values('ERM0Z3PEDET201000021',null,'code','40d39c26-a2b6-4f16-a018-45664cac1a1f','name','pk_psndoc','人员','bd_psndoc',null,null,null,0,'jkbxr','报销人','cs',1,null,null,null,null,'erm','1','bx_jkbxr','zb',null,'qryobj_bxr',null,'er_expenseaccount.bx_jkbxr','2014-04-29 09:53:17')
go

