insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001BB5G',1,-1,null,null,0,0,null,-1,'N',null,-1,'apply_org',0,'N',1,'N','Y',null,0,'apply_org','erm.mtapp_bill.apply_org',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,15,'mtapp_bill','mtapp_bill',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNCU',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem25',0,'N',1,'N','N',null,0,'defitem25','erm.mtapp_bill.defitem25',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,56,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNCX',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem12',0,'N',1,'N','N',null,0,'defitem12','erm.mtapp_bill.defitem12',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,69,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNCY',1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',null,0,'approver','erm.mtapp_bill.approver',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,28,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNCZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'global_exe_amount',0,'N',1,'N','N',null,0,'global_exe_amount','erm.mtapp_bill.global_exe_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,45,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_customer',0,'N',1,'N','N',null,0,'pk_customer','erm.mtapp_bill.pk_customer',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,25,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND2',1,-1,null,null,0,1,null,-1,'N',null,-1,'org_currinfo',0,'N',1,'N','N',null,0,'org_currinfo','erm.mtapp_bill.org_currinfo',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,17,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND3',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','erm.mtapp_bill.creationtime',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,31,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND5',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem13',0,'N',1,'N','N',null,0,'defitem13','erm.mtapp_bill.defitem13',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,68,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND6',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_tradetype',0,'N',1,'N','Y',null,0,'pk_tradetype','erm.mtapp_bill.pk_tradetype',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,4,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND8',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem16',0,'N',1,'N','N',null,0,'defitem16','erm.mtapp_bill.defitem16',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,65,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DND9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_supplier',0,'N',1,'N','N',null,0,'pk_supplier','erm.mtapp_bill.pk_supplier',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,84,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDA',1,-1,null,null,0,1,null,-1,'N',null,-1,'org_pre_amount',0,'N',1,'N','N',null,0,'org_pre_amount','erm.mtapp_bill.org_pre_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,47,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDH',1,-1,null,null,0,1,null,-1,'N',null,-1,'org_amount',0,'N',1,'N','N',null,0,'org_amount','erm.mtapp_bill.org_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,20,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','erm.mtapp_bill.modifiedtime',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,33,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDN',1,-1,null,null,0,1,null,-1,'N',null,-1,'reason',0,'N',1,'N','N',null,0,'reason','erm.mtapp_bill.reason',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,23,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDO',1,-1,null,null,0,1,null,-1,'N',null,-1,'pre_amount',0,'N',1,'N','N',null,0,'pre_amount','erm.mtapp_bill.pre_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,46,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDT',1,-1,null,null,0,1,null,-1,'N',null,-1,'billstatus',0,'N',1,'N','N',null,0,'billstatus','erm.mtapp_bill.billstatus',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,10,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDV',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem14',0,'N',1,'N','N',null,0,'defitem14','erm.mtapp_bill.defitem14',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,67,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDY',1,-1,null,null,0,1,null,-1,'N',null,-1,'closeman',0,'N',1,'N','N',null,0,'closeman','erm.mtapp_bill.closeman',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,26,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNDZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'close_status',0,'N',1,'N','N',null,0,'close_status','erm.mtapp_bill.close_status',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,16,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNE0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_billtype',0,'N',1,'N','N',null,0,'pk_billtype','erm.mtapp_bill.pk_billtype',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,3,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNE1',1,-1,null,null,0,1,null,-1,'N',null,-1,'printdate',0,'N',1,'N','N',null,0,'printdate','erm.mtapp_bill.printdate',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,35,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNE7',1,-1,null,null,0,1,null,-1,'N',null,-1,'orig_amount',0,'N',1,'N','Y',null,0,'orig_amount','erm.mtapp_bill.orig_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,9,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEA',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem11',0,'N',1,'N','N',null,0,'defitem11','erm.mtapp_bill.defitem11',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,70,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEB',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem20',0,'N',1,'N','N',null,0,'defitem20','erm.mtapp_bill.defitem20',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,61,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEC',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','erm.mtapp_bill.pk_org_v',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,83,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEE',1,-1,null,null,0,1,null,-1,'N',null,-1,'billno',0,'N',1,'N','Y',null,0,'billno','erm.mtapp_bill.billno',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,6,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEF',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem3',0,'N',1,'N','N',null,0,'defitem3','erm.mtapp_bill.defitem3',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,78,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEG',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem7',0,'N',1,'N','N',null,0,'defitem7','erm.mtapp_bill.defitem7',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,74,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEK',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem5',0,'N',1,'N','N',null,0,'defitem5','erm.mtapp_bill.defitem5',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,76,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEL',1,-1,null,null,0,1,null,-1,'N',null,-1,'org_rest_amount',0,'N',1,'N','N',null,0,'org_rest_amount','erm.mtapp_bill.org_rest_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,40,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEM',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem1',0,'N',1,'N','N',null,0,'defitem1','erm.mtapp_bill.defitem1',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,80,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEP',1,-1,null,null,0,1,null,-1,'N',null,-1,'group_currinfo',0,'N',1,'N','N',null,0,'group_currinfo','erm.mtapp_bill.group_currinfo',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,18,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNES',1,-1,null,null,0,1,null,-1,'N',null,-1,'global_pre_amount',0,'N',1,'N','N',null,0,'global_pre_amount','erm.mtapp_bill.global_pre_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,49,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNET',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem29',0,'N',1,'N','N',null,0,'defitem29','erm.mtapp_bill.defitem29',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,52,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEU',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem4',0,'N',1,'N','N',null,0,'defitem4','erm.mtapp_bill.defitem4',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,77,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEV',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem18',0,'N',1,'N','N',null,0,'defitem18','erm.mtapp_bill.defitem18',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,63,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEX',1,-1,null,null,0,1,null,-1,'N',null,-1,'group_pre_amount',0,'N',1,'N','N',null,0,'group_pre_amount','erm.mtapp_bill.group_pre_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,48,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNEY',1,-1,null,null,0,1,null,-1,'N',null,-1,'global_currinfo',0,'N',1,'N','N',null,0,'global_currinfo','erm.mtapp_bill.global_currinfo',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,19,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF1',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_currtype',0,'N',1,'N','Y',null,0,'pk_currtype','erm.mtapp_bill.pk_currtype',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,8,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF2',1,-1,null,null,0,1,null,-1,'N',null,-1,'closedate',0,'N',1,'N','N',null,0,'closedate','erm.mtapp_bill.closedate',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,27,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF4',1,-1,null,null,0,1,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','erm.mtapp_bill.billmaker',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,87,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF5',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem22',0,'N',1,'N','N',null,0,'defitem22','erm.mtapp_bill.defitem22',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,59,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF6',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem19',0,'N',1,'N','N',null,0,'defitem19','erm.mtapp_bill.defitem19',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,62,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF7',1,-1,null,'false',0,1,null,-1,'N',null,-1,'hasntbcheck',0,'N',1,'N','N',null,0,'hasntbcheck','erm.mtapp_bill.hasntbcheck',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,38,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNF9',1,-1,null,null,0,1,null,-1,'N',null,-1,'org_exe_amount',0,'N',1,'N','N',null,0,'org_exe_amount','erm.mtapp_bill.org_exe_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,43,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFA',1,-1,null,null,0,1,null,-1,'N',null,-1,'global_rest_amount',0,'N',1,'N','N',null,0,'global_rest_amount','erm.mtapp_bill.global_rest_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,42,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFC',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem6',0,'N',1,'N','N',null,0,'defitem6','erm.mtapp_bill.defitem6',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,75,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFD',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem27',0,'N',1,'N','N',null,0,'defitem27','erm.mtapp_bill.defitem27',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,54,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFF',1,-1,null,null,0,1,null,-1,'N',null,-1,'attach_amount',0,'N',1,'N','N',null,0,'attach_amount','erm.mtapp_bill.attach_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,24,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFH',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem9',0,'N',1,'N','N',null,0,'defitem9','erm.mtapp_bill.defitem9',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,72,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','erm.mtapp_bill.creator',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,30,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFK',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem17',0,'N',1,'N','N',null,0,'defitem17','erm.mtapp_bill.defitem17',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,64,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFM',1,-1,null,null,0,1,null,-1,'N',null,-1,'group_rest_amount',0,'N',1,'N','N',null,0,'group_rest_amount','erm.mtapp_bill.group_rest_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,41,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFN',1,-1,null,null,0,1,null,-1,'N',null,-1,'group_exe_amount',0,'N',1,'N','N',null,0,'group_exe_amount','erm.mtapp_bill.group_exe_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,44,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFO',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_mtapp_bill',0,'N',1,'N','N',null,0,'pk_mtapp_bill','erm.mtapp_bill.pk_mtapp_bill',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,1,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'approvetime',0,'N',1,'N','N',null,0,'approvetime','erm.mtapp_bill.approvetime',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,29,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFT',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','erm.mtapp_bill.modifier',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,32,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFV',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem15',0,'N',1,'N','N',null,0,'defitem15','erm.mtapp_bill.defitem15',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,66,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFW',1,-1,null,'ma',0,1,null,-1,'N',null,-1,'djdl',0,'N',1,'N','N',null,0,'djdl','erm.mtapp_bill.djdl',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,81,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNFX',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','erm.mtapp_bill.ts',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,85,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNG3',1,-1,null,null,0,1,null,-1,'N',null,-1,'autoclosedate',0,'N',1,'N','N',null,0,'autoclosedate','erm.mtapp_bill.autoclosedate',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,50,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNG5',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem28',0,'N',1,'N','N',null,0,'defitem28','erm.mtapp_bill.defitem28',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,53,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNG7',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem30',0,'N',1,'N','N',null,0,'defitem30','erm.mtapp_bill.defitem30',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,51,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNG8',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem24',0,'N',1,'N','N',null,0,'defitem24','erm.mtapp_bill.defitem24',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,57,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNG9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','erm.mtapp_bill.pk_group',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,37,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGB',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem21',0,'N',1,'N','N',null,0,'defitem21','erm.mtapp_bill.defitem21',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,60,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGC',1,-1,null,null,0,1,null,-1,'N',null,-1,'warningmsg',0,'N',1,'N','N',null,0,'warningmsg','erm.mtapp_bill.warningmsg',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,39,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGE',1,-1,null,null,0,1,null,-1,'N',null,-1,'group_amount',0,'N',1,'N','N',null,0,'group_amount','erm.mtapp_bill.group_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,21,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGG',1,-1,null,null,0,1,null,-1,'N',null,-1,'apply_dept',0,'N',1,'N','Y',null,0,'apply_dept','erm.mtapp_bill.apply_dept',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,36,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGH',1,-1,null,null,0,1,null,-1,'N',null,-1,'rest_amount',0,'N',1,'N','Y',null,0,'rest_amount','erm.mtapp_bill.rest_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,13,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGK',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem2',0,'N',1,'N','N',null,0,'defitem2','erm.mtapp_bill.defitem2',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,79,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGL',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem26',0,'N',1,'N','N',null,0,'defitem26','erm.mtapp_bill.defitem26',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,55,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGN',1,-1,null,null,0,1,null,-1,'N',null,-1,'printer',0,'N',1,'N','N',null,0,'printer','erm.mtapp_bill.printer',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,34,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGO',1,-1,null,null,0,1,null,-1,'N',null,-1,'apprstatus',0,'N',1,'N','N',null,0,'apprstatus','erm.mtapp_bill.apprstatus',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,11,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGP',1,-1,null,null,0,1,null,-1,'N',null,-1,'global_amount',0,'N',1,'N','N',null,0,'global_amount','erm.mtapp_bill.global_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,22,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGS',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem8',0,'N',1,'N','N',null,0,'defitem8','erm.mtapp_bill.defitem8',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,73,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGV',1,-1,'财务组织',null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','erm.mtapp_bill.pk_org',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',1,2,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGW',1,-1,null,null,0,1,null,-1,'N',null,-1,'effectstatus',0,'N',1,'N','N',null,0,'effectstatus','erm.mtapp_bill.effectstatus',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,14,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNGZ',1,-1,'单据日期',null,0,1,null,-1,'N',null,-1,'billdate',0,'N',1,'N','Y',null,0,'billdate','erm.mtapp_bill.billdate',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,5,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNH0',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem10',0,'N',1,'N','N',null,0,'defitem10','erm.mtapp_bill.defitem10',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,71,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNH4',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_mtapp_detail',0,'N',1,'N','N',null,0,'pk_mtapp_detail','erm.mtapp_detail.pk_mtapp_detail',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,86,'mtapp_bill','mtapp_bill',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNH8',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem23',0,'N',1,'N','N',null,0,'defitem23','erm.mtapp_bill.defitem23',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,58,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNHC',1,-1,null,null,0,1,null,-1,'N',null,-1,'exe_amount',0,'N',1,'N','Y',null,0,'exe_amount','erm.mtapp_bill.exe_amount',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,12,'mtapp_bill','费用申请单',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002DNIE',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_iobsclass',0,'N',1,'N','Y',null,0,'pk_iobsclass','erm.mtapp_detail.pk_iobsclass',null,'N',0,null,'1001Z31000000002DNCT','@@@@',0,null,null,null,'N',0,7,'mtapp_bill','mtapp_bill',0,'2014-01-16 15:30:57','N',null,null,null,1,1,'N',1,null,1)
go

