/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
 \***************************************************************/
package nc.vo.ep.bx;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import nc.vo.arap.bx.util.BXVOUtils;
import nc.vo.er.util.StringUtils;
import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;


/**
 * @author twei
 *
 * nc.vo.ep.bx.BxcontrastVO
 *
 * 借款报销冲销VO
 */
public class BxcontrastVO extends SuperVO {

	private static final long serialVersionUID = 2471736148044023351L;

	// 借款单业务行PK
	public String pk_busitem;
	
	public String pk_jkd;

	public String pk_org;
	
	public String pk_payorg;

	public String djlxbm;

	public String pk_bxd;

	public UFDouble bbje;

	public UFDate sxrq;

	public UFDate cxrq;
	private String cxnd;
	private String cxqj;

	public String deptid;

	public Integer sxbz;

	public String jkbxr;

	public String pk_bxcontrast;

	public UFDouble ybje;

	public UFDouble ybye;

	public UFDouble cjkbbje;
	
	public UFDouble cjkybje;

	public String jobid;

	public String szxmid;

	public UFDouble fybbje;
	public UFDouble fyybje;
	
	public UFDouble hkbbje;
	public UFDouble hkybje;

	public String bxdjbh; 
	public String jkdjbh; 
	//v6.0 全局，集团本币金额
	public UFDouble groupfybbje;  //集团费用本币金额
	public UFDouble groupbbje;  //集团本币金额
	public UFDouble groupcjkbbje;  //集团冲销本币金额
	public UFDouble globalfybbje;  //全局本币金额
	public UFDouble globalbbje;  //全局本币金额
	public UFDouble globalcjkbbje; //全局冲销本币金额 
	
	private UFBoolean selected = UFBoolean.FALSE;
	
	public String bzbm;
	

	public UFDateTime ts;
	public UFDateTime getTs() {
		return ts;
	}
	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}
	public UFBoolean getSelected() {
		return selected;
	}
	public void setSelected(UFBoolean selected) {
		this.selected = selected;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 * 比较主键是否相同
	 */
	public boolean equals(Object obj) {

		if (! (obj instanceof BxcontrastVO)) {
			return false;
		}
		BxcontrastVO vo=(BxcontrastVO)obj;

		if(StringUtils.isNullWithTrim(vo.getPrimaryKey()) || StringUtils.isNullWithTrim(getPrimaryKey())){
			return super.equals(obj);
		}

		return getPrimaryKey().equals(vo.getPrimaryKey());
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pk_bxcontrast == null) ? 0 : pk_bxcontrast.hashCode());
		return result;
	}
	
	// 借款单业务行PK
	public static final String PK_BUSITEM = "pk_busitem";
	public static final String PK_JKD = "pk_jkd";

	public static final String PK_ORG = "pk_org";
	
	public static final String PK_PAYORG = "pk_payorg";

	public static final String DJLXBM = "djlxbm";

	public static final String PK_BXD = "pk_bxd";

	public static final String BBJE = "bbje";

	public static final String SXRQ = "sxrq";

	public static final String CXRQ = "cxrq";

	public static final String DEPTID = "deptid";

	public static final String SXBZ = "sxbz";

	public static final String JKBXR = "jkbxr";

	public static final String PK_BXCONTRAST = "pk_bxcontrast";


	public static final String YBJE = "ybje";
	
	public static final String YBYE = "ybye";

	public static final String JOBID = "jobid";

	public static final String SZXMID = "szxmid";

	public static final String CJKBBJE = "cjkbbje";
	public static final String CJKYBJE = "cjkybje";
	public static final String FYYBJE = "fyybje";
	public static final String PK_PC = "pk_pc";
	public static final String HKYBJE = "hkybje";
	//v6.0 全局，集团本币金额
	public static final String GROUPFYBBJE = "groupfybbje";
	public static final String GROUPBBJE = "groupbbje";
	public static final String GROUPCJKBBJE = "groupcjkbbje";
	public static final String GLOBALFYBBJE = "globalfybbje";
	public static final String GLOBALBBJE = "globalbbje";
	public static final String GLOBALCJKBBJE = "globalcjkbbje";
	

	public String pk_finitem;
	public String pk_pc;


	public String getPk_pc() {
		return pk_pc;
	}

	public void setPk_pc(String pk_pc) {
		this.pk_pc = pk_pc;
	}

	/**
	 * 属性pk_jkd的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getPk_jkd() {
		return pk_jkd;
	}

	/**
	 * 属性pk_jkd的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newPk_jkd
	 *            String
	 */
	public void setPk_jkd(String newPk_jkd) {

		pk_jkd = newPk_jkd;
	}

	/**
	 * 属性pk_org的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newPk_org
	 *            String
	 */
	public void setPk_org(String newPk_org) {

		pk_org = newPk_org;
	}

	/**
	 * 属性djlxbm的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getDjlxbm() {
		return djlxbm;
	}

	/**
	 * 属性djlxbm的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newDjlxbm
	 *            String
	 */
	public void setDjlxbm(String newDjlxbm) {

		djlxbm = newDjlxbm;
	}

	/**
	 * 属性pk_bxd的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getPk_bxd() {
		return pk_bxd;
	}

	/**
	 * 属性pk_bxd的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newPk_bxd
	 *            String
	 */
	public void setPk_bxd(String newPk_bxd) {

		pk_bxd = newPk_bxd;
	}

	/**
	 * 属性bbje的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return UFDouble
	 */
	public UFDouble getBbje() {
		return bbje;
	}

	/**
	 * 属性bbje的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newBbje
	 *            UFDouble
	 */
	public void setBbje(UFDouble newBbje) {

		bbje = newBbje;
	}

	/**
	 * 属性sxrq的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return UFDate
	 */
	public UFDate getSxrq() {
		return sxrq;
	}

	/**
	 * 属性sxrq的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newSxrq
	 *            UFDate
	 */
	public void setSxrq(UFDate newSxrq) {

		sxrq = newSxrq;
	}

	/**
	 * 属性cxrq的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return UFDate
	 */
	public UFDate getCxrq() {
		return cxrq;
	}

	/**
	 * 属性cxrq的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newCxrq
	 *            UFDate
	 */
	public void setCxrq(UFDate newCxrq) {

		cxrq = newCxrq;
	}

	/**
	 * 属性deptid的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getDeptid() {
		return deptid;
	}

	/**
	 * 属性deptid的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newDeptid
	 *            String
	 */
	public void setDeptid(String newDeptid) {

		deptid = newDeptid;
	}

	/**
	 * 属性sxbz的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return Integer
	 */
	public Integer getSxbz() {
		return sxbz;
	}

	/**
	 * 属性sxbz的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newSxbz
	 *            Integer
	 */
	public void setSxbz(Integer newSxbz) {

		sxbz = newSxbz;
	}

	/**
	 * 属性jkbxr的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getJkbxr() {
		return jkbxr;
	}

	/**
	 * 属性jkbxr的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newJkbxr
	 *            String
	 */
	public void setJkbxr(String newJkbxr) {

		jkbxr = newJkbxr;
	}

	/**
	 * 属性pk_bxcontrast的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getPk_bxcontrast() {
		return pk_bxcontrast;
	}

	/**
	 * 属性pk_bxcontrast的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newPk_bxcontrast
	 *            String
	 */
	public void setPk_bxcontrast(String newPk_bxcontrast) {

		pk_bxcontrast = newPk_bxcontrast;
	}

	/**
	 * 属性ybje的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return UFDouble
	 */
	public UFDouble getYbje() {
		return ybje;
	}

	/**
	 * 属性ybje的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newYbje
	 *            UFDouble
	 */
	public void setYbje(UFDouble newYbje) {

		ybje = newYbje;
	}
	
	public void setYbye(UFDouble ybye) {
		this.ybye = ybye;
	}
	
	public UFDouble getYbye() {
		return ybye;
	}
	
	/**
	 * 属性jobid的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getJobid() {
		return jobid;
	}

	/**
	 * 属性jobid的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newJobid
	 *            String
	 */
	public void setJobid(String newJobid) {

		jobid = newJobid;
	}

	/**
	 * 属性szxmid的Getter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getSzxmid() {
		return szxmid;
	}

	/**
	 * 属性szxmid的Setter方法.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newSzxmid
	 *            String
	 */
	public void setSzxmid(String newSzxmid) {

		szxmid = newSzxmid;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		validateNullField();
	}

	private void validateNullField() throws NullFieldException {
		ArrayList<String> errFields = new ArrayList<String>(); // errFields record those null
		List<String> notNullFields = null; // errFields record those null
		String[] str={
				BxcontrastVO.PK_JKD,
				BxcontrastVO.CJKYBJE,
				};
		notNullFields=Arrays.asList(str);

		for (String field : notNullFields) {
			if (getAttributeValue(field) == null)
				errFields.add(getFieldName(field));
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("2011","UPP2011-000282")/*@res "冲销信息表头下列字段不能为空:\n"*/);
		if (errFields.size() > 0) {
			String[] temp = errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	public String getFieldName(String field) {
		if(field.equals(PK_JKD))
			return nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("2011","UPP2011-000283")/*@res "借款单主键"*/;
		else if (field.equals(PK_BXD))
			return nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("2011","UPP2011-000284")/*@res "报销单主键"*/;
		else if (field.equals(CJKYBJE))
			return nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("2011","UPP2011-000280")/*@res "原币金额"*/;
		else
			return field;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2007-6-13
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2007-6-13
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_bxcontrast";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2007-6-13
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "er_bxcontrast";
	}

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2007-6-13
	 */
	public BxcontrastVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newPk_bxcontrast
	 *            主键值
	 */
	public BxcontrastVO(String newPk_bxcontrast) {

		// 为主键字段赋值:
		pk_bxcontrast = newPk_bxcontrast;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_bxcontrast;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @param newPk_bxcontrast
	 *            String
	 */
	public void setPrimaryKey(String newPk_bxcontrast) {

		pk_bxcontrast = newPk_bxcontrast;

	}

	/**
	 * 返回数值对象的显示名称.
	 *
	 * 创建日期:2007-6-13
	 *
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "er_bxcontrast";

	}

	public UFDouble getCjkbbje() {
		return cjkbbje;
	}

	public void setCjkbbje(UFDouble cjkbbje) {
		this.cjkbbje = cjkbbje;
	}
	public UFDouble getCjkybje() {
		return cjkybje;
	}

	public void setCjkybje(UFDouble cjkybje) {
		this.cjkybje = cjkybje;
	}

	private String sxbzmc;
	public String getSxbzmc() {
		if(sxbzmc!=null)
			return sxbzmc;
		return BXVOUtils.getSxbzmc(sxbz);
	}
	public void setSxbzmc(String sxbzmc) {
		this.sxbzmc = sxbzmc;
	}

	public String getBxdjbh() {
		return bxdjbh;
	}

	public void setBxdjbh(String bxdjbh) {
		this.bxdjbh = bxdjbh;
	}

	public String getJkdjbh() {
		return jkdjbh;
	}

	public void setJkdjbh(String jkdjbh) {
		this.jkdjbh = jkdjbh;
	}
	public UFDouble getFybbje() {
		return fybbje;
	}
	public void setFybbje(UFDouble fybbje) {
		this.fybbje = fybbje;
	}
	public UFDouble getFyybje() {
		return fyybje;
	}
	public void setFyybje(UFDouble fyybje) {
		this.fyybje = fyybje;
	}
	public String getPk_finitem() {
		return pk_finitem;
	}
	public void setPk_finitem(String pk_finitem) {
		this.pk_finitem = pk_finitem;
	}
	public UFDouble getHkbbje() {
		return hkbbje;
	}
	public void setHkbbje(UFDouble hkbbje) {
		this.hkbbje = hkbbje;
	}
	public UFDouble getHkybje() {
		return hkybje;
	}
	public void setHkybje(UFDouble hkybje) {
		this.hkybje = hkybje;
	}
	public String getCxnd() {
		return cxnd;
	}
	public void setCxnd(String cxnd) {
		this.cxnd = cxnd;
	}
	public String getCxqj() {
		return cxqj;
	}
	public void setCxqj(String cxqj) {
		this.cxqj = cxqj;
	}
	public String getBzbm() {
		return bzbm;
	}
	public void setBzbm(String bzbm) {
		this.bzbm = bzbm;
	}
	/**
	 * 属性groupfybbje的Getter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @return UFDouble
	 */
	public UFDouble getGroupfybbje () {
		return groupfybbje;
	}   
	/**
	 * 属性groupfybbje的Setter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @param newGroupfybbje UFDouble
	 */
	public void setGroupfybbje (UFDouble newGroupfybbje ) {
	 	this.groupfybbje = newGroupfybbje;
	} 	  
	/**
	 * 属性groupbbje的Getter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @return UFDouble
	 */
	public UFDouble getGroupbbje () {
		return groupbbje;
	}   
	/**
	 * 属性groupbbje的Setter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @param newGroupbbje UFDouble
	 */
	public void setGroupbbje (UFDouble newGroupbbje ) {
	 	this.groupbbje = newGroupbbje;
	} 	  
	/**
	 * 属性groupcjkbbje的Getter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @return UFDouble
	 */
	public UFDouble getGroupcjkbbje () {
		return groupcjkbbje;
	}   
	/**
	 * 属性groupcjkbbje的Setter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @param newGroupcjkbbje UFDouble
	 */
	public void setGroupcjkbbje (UFDouble newGroupcjkbbje ) {
	 	this.groupcjkbbje = newGroupcjkbbje;
	} 	  
	/**
	 * 属性globalfybbje的Getter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @return UFDouble
	 */
	public UFDouble getGlobalfybbje () {
		return globalfybbje;
	}   
	/**
	 * 属性globalfybbje的Setter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @param newGlobalfybbje UFDouble
	 */
	public void setGlobalfybbje (UFDouble newGlobalfybbje ) {
	 	this.globalfybbje = newGlobalfybbje;
	} 	  
	/**
	 * 属性globalbbje的Getter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @return UFDouble
	 */
	public UFDouble getGlobalbbje () {
		return globalbbje;
	}   
	/**
	 * 属性globalbbje的Setter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @param newGlobalbbje UFDouble
	 */
	public void setGlobalbbje (UFDouble newGlobalbbje ) {
	 	this.globalbbje = newGlobalbbje;
	} 	  
	/**
	 * 属性globalcjkbbje的Getter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @return UFDouble
	 */
	public UFDouble getGlobalcjkbbje () {
		return globalcjkbbje;
	}   
	/**
	 * 属性globalcjkbbje的Setter方法.
	 * 创建日期:2010-01-18 10:54:56
	 * @param newGlobalcjkbbje UFDouble
	 */
	public void setGlobalcjkbbje (UFDouble newGlobalcjkbbje ) {
	 	this.globalcjkbbje = newGlobalcjkbbje;
	} 

	@Override
	public Object getAttributeValue(String arg0) {
		// TODO Auto-generated method stub
		return super.getAttributeValue(arg0);
	}
	public String getPk_busitem() {
		return pk_busitem;
	}
	public void setPk_busitem(String pk_busitem) {
		this.pk_busitem = pk_busitem;
	}
	public String getPk_payorg() {
		return pk_payorg;
	}
	public void setPk_payorg(String pk_payorg) {
		this.pk_payorg = pk_payorg;
	}
}