/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.er.reimtype;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-03-09 15:42:50
 * @author liansg
 * @version NC Version 6.0
 */
@SuppressWarnings("serial")
public class ReimTypeVO extends SuperVO {
	private java.lang.String pk_reimtype;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String code;
	private nc.vo.pub.lang.UFBoolean inuse;
	private java.lang.String memo;
	private java.lang.String pk_group;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_REIMTYPE = "pk_reimtype";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String NAME4 = "name4";
	public static final String NAME5 = "name5";
	public static final String NAME6 = "name6";
	public static final String CODE = "code";
	public static final String INUSE = "inuse";
	public static final String MEMO = "memo";
	public static final String PK_GROUP = "pk_group";
			
	/**
	 * 属性pk_reimtype的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.String
	 */
	public java.lang.String getPk_reimtype () {
		return pk_reimtype;
	}   
	/**
	 * 属性pk_reimtype的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newPk_reimtype java.lang.String
	 */
	public void setPk_reimtype (java.lang.String newPk_reimtype ) {
	 	this.pk_reimtype = newPk_reimtype;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	
	public java.lang.String getName2() {
		return name2;
	}
	public void setName2(java.lang.String name2) {
		this.name2 = name2;
	}

	public java.lang.String getName3() {
		return name3;
	}
	public void setName3(java.lang.String name3) {
		this.name3 = name3;
	}

	public java.lang.String getName4() {
		return name4;
	}
	public void setName4(java.lang.String name4) {
		this.name4 = name4;
	}

	public java.lang.String getName5() {
		return name5;
	}
	public void setName5(java.lang.String name5) {
		this.name5 = name5;
	}

	public java.lang.String getName6() {
		return name6;
	}
	public void setName6(java.lang.String name6) {
		this.name6 = name6;
	}
	
	/**
	 * 属性code的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性inuse的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getInuse () {
		return inuse;
	}   
	/**
	 * 属性inuse的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newInuse nc.vo.pub.lang.UFBoolean
	 */
	public void setInuse (nc.vo.pub.lang.UFBoolean newInuse ) {
	 	this.inuse = newInuse;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-03-09 15:42:50
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-03-09 15:42:50
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-03-09 15:42:50
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_reimtype";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-03-09 15:42:50
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_reimtype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-03-09 15:42:50
	  */
     public ReimTypeVO() {
		super();	
	}    
} 


