/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
 \***************************************************************/
package nc.vo.er.reimtype;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;

/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2008-7-29
 *
 * @author ${vmObject.author}
 * @version NC6.0
 */
public class ReimTypeHeaderVO extends SuperVO {

	private static final long serialVersionUID = 1L;

	public UFBoolean inuse;

	public String memo;

	public String pk_reimtype;

	public String code;

	public String name;

	public UFDateTime ts;

	public Integer dr;
	
	public String pk_group;

	/**
	 * <p>
	 * 取得对应登陆集团PK.
	 * <p>
	 * 创建日期:2010-01-13
	 * @return java.lang.String
	 */
	public String getPk_group() {
		return pk_group;
	}

	public void setPk_group(String pkGroup) {
		pk_group = pkGroup;
	}

	public static String CODE="code";
	public static String NAME="name";

	public Integer getDr() {
		return dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public UFBoolean getInuse() {
		return inuse;
	}

	public void setInuse(UFBoolean inuse) {
		this.inuse = inuse;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPk_reimtype() {
		return pk_reimtype;
	}

	public void setPk_reimtype(String pk_reimtype) {
		this.pk_reimtype = pk_reimtype;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 *
	 * 创建日期:2008-7-29
	 *
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList<String> errFields = new ArrayList<String>();

		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
		if (pk_reimtype == null) {
			errFields.add("pk_reimtype");
		}

		StringBuffer message = new StringBuffer();
		message.append(nc.vo.ml.NCLangRes4VoTransl.getNCLangRes().getStrByID("2011","UPP2011-000310")/*@res "下列字段不能为空:"*/);
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2008-7-29
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}
	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2008-7-29
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_reimtype";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2008-7-29
	 *
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_reimtype";
	}

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2008-7-29
	 */
	public ReimTypeHeaderVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2008-7-29
	 *
	 * @param newPk_brand
	 *            主键值
	 */
	public ReimTypeHeaderVO(String newpk_reimtype) {
		pk_reimtype = newpk_reimtype;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2008-7-29
	 *
	 * @return String
	 */
	public String getPrimaryKey() {
		return pk_reimtype;
	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 *
	 * 创建日期:2008-7-29
	 *
	 * @param newPk_brand
	 *            String
	 */
	public void setPrimaryKey(String newPk_brand) {
		pk_reimtype = newPk_brand;
	}

	/**
	 * 返回数值对象的显示名称.
	 *
	 * 创建日期:2008-7-29
	 *
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {
		return "er_reimtype";
	}
}