/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.matterappctrl;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MtapppfVO extends SuperVO {
	private java.lang.String pk_mtapp_pf;
	private java.lang.String pk_matterapp;
	private java.lang.String pk_mtapp_detail;
	private java.lang.String ma_tradetype;
	private java.lang.String busisys;
	private java.lang.String pk_djdl;
	private java.lang.String pk_billtype;
	private java.lang.String pk_tradetype;
	private java.lang.String busi_pk;
	private java.lang.String exe_user;
	private nc.vo.pub.lang.UFDateTime exe_time;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private nc.vo.pub.lang.UFDouble fy_amount;
	private nc.vo.pub.lang.UFDouble org_fy_amount;
	private nc.vo.pub.lang.UFDouble group_fy_amount;
	private nc.vo.pub.lang.UFDouble global_fy_amount;
	private nc.vo.pub.lang.UFDouble exe_amount;
	private nc.vo.pub.lang.UFDouble org_exe_amount;
	private nc.vo.pub.lang.UFDouble group_exe_amount;
	private nc.vo.pub.lang.UFDouble global_exe_amount;
	private nc.vo.pub.lang.UFDouble pre_amount;
	private nc.vo.pub.lang.UFDouble org_pre_amount;
	private nc.vo.pub.lang.UFDouble group_pre_amount;
	private nc.vo.pub.lang.UFDouble global_pre_amount;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	
	private String busi_detail_pk;
	private UFBoolean is_adjust;

	public static final String PK_MTAPP_PF = "pk_mtapp_pf";
	public static final String PK_MATTERAPP = "pk_matterapp";
	public static final String PK_MTAPP_DETAIL = "pk_mtapp_detail";
	public static final String BUSISYS = "busisys";
	public static final String PK_DJDL = "pk_djdl";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String PK_TRADETYPE = "pk_tradetype";
	public static final String BUSI_PK = "busi_pk";
	public static final String EXE_USER = "exe_user";
	public static final String EXE_TIME = "exe_time";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String FY_AMOUNT = "fy_amount";
	public static final String ORG_FY_AMOUNT = "org_fy_amount";
	public static final String GROUP_FY_AMOUNT = "group_fy_amount";
	public static final String GLOBAL_FY_AMOUNT = "global_fy_amount";
	public static final String EXE_AMOUNT = "exe_amount";
	public static final String ORG_EXE_AMOUNT = "org_exe_amount";
	public static final String GROUP_EXE_AMOUNT = "group_exe_amount";
	public static final String GLOBAL_EXE_AMOUNT = "global_exe_amount";
	public static final String PRE_AMOUNT = "pre_amount";
	public static final String ORG_PRE_AMOUNT = "org_pre_amount";
	public static final String GROUP_PRE_AMOUNT = "group_pre_amount";
	public static final String GLOBAL_PRE_AMOUNT = "global_pre_amount";
	
	public static final String BUSI_DETAIL_PK = "busi_detail_pk";
	public static final String IS_ADJUST = "is_adjust";
			
	/**
	 * 属性pk_mtapp_pf的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_mtapp_pf () {
		return pk_mtapp_pf;
	}   
	/**
	 * 属性pk_mtapp_pf的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_mtapp_pf java.lang.String
	 */
	public void setPk_mtapp_pf (java.lang.String newPk_mtapp_pf ) {
	 	this.pk_mtapp_pf = newPk_mtapp_pf;
	} 	  
	/**
	 * 属性pk_matterapp的Getter方法.属性名：费用申请单
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_matterapp () {
		return pk_matterapp;
	}   
	/**
	 * 属性pk_matterapp的Setter方法.属性名：费用申请单
	 * 创建日期:
	 * @param newPk_matterapp java.lang.String
	 */
	public void setPk_matterapp (java.lang.String newPk_matterapp ) {
	 	this.pk_matterapp = newPk_matterapp;
	} 	  
	/**
	 * 属性pk_mtapp_detail的Getter方法.属性名：费用申请单明细
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_mtapp_detail () {
		return pk_mtapp_detail;
	}   
	/**
	 * 属性pk_mtapp_detail的Setter方法.属性名：费用申请单明细
	 * 创建日期:
	 * @param newPk_mtapp_detail java.lang.String
	 */
	public void setPk_mtapp_detail (java.lang.String newPk_mtapp_detail ) {
	 	this.pk_mtapp_detail = newPk_mtapp_detail;
	} 	  
	/**
	 * 属性busisys的Getter方法.属性名：业务系统
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusisys () {
		return busisys;
	}   
	/**
	 * 属性busisys的Setter方法.属性名：业务系统
	 * 创建日期:
	 * @param newBusisys java.lang.String
	 */
	public void setBusisys (java.lang.String newBusisys ) {
	 	this.busisys = newBusisys;
	} 	  
	/**
	 * 属性pk_djdl的Getter方法.属性名：业务单据大类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_djdl () {
		return pk_djdl;
	}   
	/**
	 * 属性pk_djdl的Setter方法.属性名：业务单据大类
	 * 创建日期:
	 * @param newPk_djdl java.lang.String
	 */
	public void setPk_djdl (java.lang.String newPk_djdl ) {
	 	this.pk_djdl = newPk_djdl;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.属性名：业务单据类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.属性名：业务单据类型
	 * 创建日期:
	 * @param newPk_billtype java.lang.String
	 */
	public void setPk_billtype (java.lang.String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性pk_tradetype的Getter方法.属性名：业务交易类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_tradetype () {
		return pk_tradetype;
	}   
	/**
	 * 属性pk_tradetype的Setter方法.属性名：业务交易类型
	 * 创建日期:
	 * @param newPk_tradetype java.lang.String
	 */
	public void setPk_tradetype (java.lang.String newPk_tradetype ) {
	 	this.pk_tradetype = newPk_tradetype;
	} 	  
	/**
	 * 属性busi_pk的Getter方法.属性名：业务单据pk
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusi_pk () {
		return busi_pk;
	}   
	/**
	 * 属性busi_pk的Setter方法.属性名：业务单据pk
	 * 创建日期:
	 * @param newBusi_pk java.lang.String
	 */
	public void setBusi_pk (java.lang.String newBusi_pk ) {
	 	this.busi_pk = newBusi_pk;
	} 	  
	/**
	 * 属性exe_user的Getter方法.属性名：最后执行人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExe_user () {
		return exe_user;
	}   
	/**
	 * 属性exe_user的Setter方法.属性名：最后执行人
	 * 创建日期:
	 * @param newExe_user java.lang.String
	 */
	public void setExe_user (java.lang.String newExe_user ) {
	 	this.exe_user = newExe_user;
	} 	  
	/**
	 * 属性exe_time的Getter方法.属性名：最后执行时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getExe_time () {
		return exe_time;
	}   
	/**
	 * 属性exe_time的Setter方法.属性名：最后执行时间
	 * 创建日期:
	 * @param newExe_time nc.vo.pub.lang.UFDateTime
	 */
	public void setExe_time (nc.vo.pub.lang.UFDateTime newExe_time ) {
	 	this.exe_time = newExe_time;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性fy_amount的Getter方法.属性名：费用金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getFy_amount () {
		return fy_amount;
	}   
	/**
	 * 属性fy_amount的Setter方法.属性名：费用金额
	 * 创建日期:
	 * @param newFy_amount nc.vo.pub.lang.UFDouble
	 */
	public void setFy_amount (nc.vo.pub.lang.UFDouble newFy_amount ) {
	 	this.fy_amount = newFy_amount;
	} 	  
	/**
	 * 属性org_fy_amount的Getter方法.属性名：组织本币费用金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_fy_amount () {
		return org_fy_amount;
	}   
	/**
	 * 属性org_fy_amount的Setter方法.属性名：组织本币费用金额
	 * 创建日期:
	 * @param newOrg_fy_amount nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_fy_amount (nc.vo.pub.lang.UFDouble newOrg_fy_amount ) {
	 	this.org_fy_amount = newOrg_fy_amount;
	} 	  
	/**
	 * 属性group_fy_amount的Getter方法.属性名：集团本币费用金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_fy_amount () {
		return group_fy_amount;
	}   
	/**
	 * 属性group_fy_amount的Setter方法.属性名：集团本币费用金额
	 * 创建日期:
	 * @param newGroup_fy_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_fy_amount (nc.vo.pub.lang.UFDouble newGroup_fy_amount ) {
	 	this.group_fy_amount = newGroup_fy_amount;
	} 	  
	/**
	 * 属性global_fy_amount的Getter方法.属性名：全局本币费用金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_fy_amount () {
		return global_fy_amount;
	}   
	/**
	 * 属性global_fy_amount的Setter方法.属性名：全局本币费用金额
	 * 创建日期:
	 * @param newGlobal_fy_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_fy_amount (nc.vo.pub.lang.UFDouble newGlobal_fy_amount ) {
	 	this.global_fy_amount = newGlobal_fy_amount;
	} 	  
	/**
	 * 属性exe_amount的Getter方法.属性名：执行数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getExe_amount () {
		return exe_amount;
	}   
	/**
	 * 属性exe_amount的Setter方法.属性名：执行数
	 * 创建日期:
	 * @param newExe_amount nc.vo.pub.lang.UFDouble
	 */
	public void setExe_amount (nc.vo.pub.lang.UFDouble newExe_amount ) {
	 	this.exe_amount = newExe_amount;
	} 	  
	/**
	 * 属性org_exe_amount的Getter方法.属性名：组织本币执行数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_exe_amount () {
		return org_exe_amount;
	}   
	/**
	 * 属性org_exe_amount的Setter方法.属性名：组织本币执行数
	 * 创建日期:
	 * @param newOrg_exe_amount nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_exe_amount (nc.vo.pub.lang.UFDouble newOrg_exe_amount ) {
	 	this.org_exe_amount = newOrg_exe_amount;
	} 	  
	/**
	 * 属性group_exe_amount的Getter方法.属性名：集团本币执行数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_exe_amount () {
		return group_exe_amount;
	}   
	/**
	 * 属性group_exe_amount的Setter方法.属性名：集团本币执行数
	 * 创建日期:
	 * @param newGroup_exe_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_exe_amount (nc.vo.pub.lang.UFDouble newGroup_exe_amount ) {
	 	this.group_exe_amount = newGroup_exe_amount;
	} 	  
	/**
	 * 属性global_exe_amount的Getter方法.属性名：全局本币执行数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_exe_amount () {
		return global_exe_amount;
	}   
	/**
	 * 属性global_exe_amount的Setter方法.属性名：全局本币执行数
	 * 创建日期:
	 * @param newGlobal_exe_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_exe_amount (nc.vo.pub.lang.UFDouble newGlobal_exe_amount ) {
	 	this.global_exe_amount = newGlobal_exe_amount;
	} 	  
	/**
	 * 属性pre_amount的Getter方法.属性名：预占数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getPre_amount () {
		return pre_amount;
	}   
	/**
	 * 属性pre_amount的Setter方法.属性名：预占数
	 * 创建日期:
	 * @param newPre_amount nc.vo.pub.lang.UFDouble
	 */
	public void setPre_amount (nc.vo.pub.lang.UFDouble newPre_amount ) {
	 	this.pre_amount = newPre_amount;
	} 	  
	/**
	 * 属性org_pre_amount的Getter方法.属性名：组织本币预占数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_pre_amount () {
		return org_pre_amount;
	}   
	/**
	 * 属性org_pre_amount的Setter方法.属性名：组织本币预占数
	 * 创建日期:
	 * @param newOrg_pre_amount nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_pre_amount (nc.vo.pub.lang.UFDouble newOrg_pre_amount ) {
	 	this.org_pre_amount = newOrg_pre_amount;
	} 	  
	/**
	 * 属性group_pre_amount的Getter方法.属性名：集团本币预占数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_pre_amount () {
		return group_pre_amount;
	}   
	/**
	 * 属性group_pre_amount的Setter方法.属性名：集团本币预占数
	 * 创建日期:
	 * @param newGroup_pre_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_pre_amount (nc.vo.pub.lang.UFDouble newGroup_pre_amount ) {
	 	this.group_pre_amount = newGroup_pre_amount;
	} 	  
	/**
	 * 属性global_pre_amount的Getter方法.属性名：全局本币预占数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_pre_amount () {
		return global_pre_amount;
	}   
	/**
	 * 属性global_pre_amount的Setter方法.属性名：全局本币预占数
	 * 创建日期:
	 * @param newGlobal_pre_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_pre_amount (nc.vo.pub.lang.UFDouble newGlobal_pre_amount ) {
	 	this.global_pre_amount = newGlobal_pre_amount;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_mtapp_pf";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_mtapp_pf";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_mtapp_pf";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public MtapppfVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.erm.matterappctrl.MtapppfVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
	public String getBusi_detail_pk() {
		return busi_detail_pk;
	}
	public void setBusi_detail_pk(String busi_detail_pk) {
		this.busi_detail_pk = busi_detail_pk;
	}
	public UFBoolean getIs_adjust() {
		return is_adjust;
	}
	public void setIs_adjust(UFBoolean is_adjust) {
		this.is_adjust = is_adjust;
	}
	public java.lang.String getMa_tradetype() {
		return ma_tradetype;
	}
	public void setMa_tradetype(java.lang.String ma_tradetype) {
		this.ma_tradetype = ma_tradetype;
	}
} 


