/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.matterappctrl;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MtappbillpfVO extends SuperVO {
	private java.lang.String pk_mtapp_billpf;
	private java.lang.String pk_matterapp;
	private java.lang.String pk_mtapp_detail;
	private java.lang.String busisys;
	private java.lang.String pk_djdl;
	private nc.vo.pub.lang.UFDouble exe_amount;
	private nc.vo.pub.lang.UFDouble pre_amount;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_MTAPP_BILLPF = "pk_mtapp_billpf";
	public static final String PK_MATTERAPP = "pk_matterapp";
	public static final String PK_MTAPP_DETAIL = "pk_mtapp_detail";
	public static final String BUSISYS = "busisys";
	public static final String PK_DJDL = "pk_djdl";
	public static final String EXE_AMOUNT = "exe_amount";
	public static final String PRE_AMOUNT = "pre_amount";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
			
	/**
	 * 属性pk_mtapp_billpf的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_mtapp_billpf () {
		return pk_mtapp_billpf;
	}   
	/**
	 * 属性pk_mtapp_billpf的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_mtapp_billpf java.lang.String
	 */
	public void setPk_mtapp_billpf (java.lang.String newPk_mtapp_billpf ) {
	 	this.pk_mtapp_billpf = newPk_mtapp_billpf;
	} 	  
	/**
	 * 属性pk_matterapp的Getter方法.属性名：事项审批单
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_matterapp () {
		return pk_matterapp;
	}   
	/**
	 * 属性pk_matterapp的Setter方法.属性名：事项审批单
	 * 创建日期:
	 * @param newPk_matterapp java.lang.String
	 */
	public void setPk_matterapp (java.lang.String newPk_matterapp ) {
	 	this.pk_matterapp = newPk_matterapp;
	} 	  
	/**
	 * 属性pk_mtapp_detail的Getter方法.属性名：事项审批单明细
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_mtapp_detail () {
		return pk_mtapp_detail;
	}   
	/**
	 * 属性pk_mtapp_detail的Setter方法.属性名：事项审批单明细
	 * 创建日期:
	 * @param newPk_mtapp_detail java.lang.String
	 */
	public void setPk_mtapp_detail (java.lang.String newPk_mtapp_detail ) {
	 	this.pk_mtapp_detail = newPk_mtapp_detail;
	} 	  
	/**
	 * 属性busisys的Getter方法.属性名：业务系统
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusisys () {
		return busisys;
	}   
	/**
	 * 属性busisys的Setter方法.属性名：业务系统
	 * 创建日期:
	 * @param newBusisys java.lang.String
	 */
	public void setBusisys (java.lang.String newBusisys ) {
	 	this.busisys = newBusisys;
	} 	  
	/**
	 * 属性pk_djdl的Getter方法.属性名：业务单据大类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_djdl () {
		return pk_djdl;
	}   
	/**
	 * 属性pk_djdl的Setter方法.属性名：业务单据大类
	 * 创建日期:
	 * @param newPk_djdl java.lang.String
	 */
	public void setPk_djdl (java.lang.String newPk_djdl ) {
	 	this.pk_djdl = newPk_djdl;
	} 	  
	/**
	 * 属性exe_amount的Getter方法.属性名：执行数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getExe_amount () {
		return exe_amount;
	}   
	/**
	 * 属性exe_amount的Setter方法.属性名：执行数
	 * 创建日期:
	 * @param newExe_amount nc.vo.pub.lang.UFDouble
	 */
	public void setExe_amount (nc.vo.pub.lang.UFDouble newExe_amount ) {
	 	this.exe_amount = newExe_amount;
	} 	  
	/**
	 * 属性pre_amount的Getter方法.属性名：预占数
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getPre_amount () {
		return pre_amount;
	}   
	/**
	 * 属性pre_amount的Setter方法.属性名：预占数
	 * 创建日期:
	 * @param newPre_amount nc.vo.pub.lang.UFDouble
	 */
	public void setPre_amount (nc.vo.pub.lang.UFDouble newPre_amount ) {
	 	this.pre_amount = newPre_amount;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_mtapp_billpf";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_mtapp_billpf";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_mtapp_billpf";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public MtappbillpfVO() {
		super();	
	}    
} 


