/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.accruedexpense;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class AccruedVerifyVO extends SuperVO {
	private java.lang.String pk_accrued_bill;
	private java.lang.String pk_accrued_verify;
	private java.lang.String pk_accrued_detail;
	private java.lang.String pk_bxd;
	private nc.vo.pub.lang.UFDouble verify_amount;
	private nc.vo.pub.lang.UFDouble org_verify_amount;
	private nc.vo.pub.lang.UFDouble group_verify_amount;
	private nc.vo.pub.lang.UFDouble global_verify_amount;
	private java.lang.String verify_man;
	private nc.vo.pub.lang.UFDate verify_date;
	private java.lang.Integer effectstatus;
	private nc.vo.pub.lang.UFDate effectdate;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String accrued_billno;
	private java.lang.String bxd_billno;
	private java.lang.String pk_iobsclass;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_ACCRUED_BILL = "pk_accrued_bill";
	public static final String PK_ACCRUED_VERIFY = "pk_accrued_verify";
	public static final String PK_ACCRUED_DETAIL = "pk_accrued_detail";
	public static final String PK_BXD = "pk_bxd";
	public static final String VERIFY_AMOUNT = "verify_amount";
	public static final String ORG_VERIFY_AMOUNT = "org_verify_amount";
	public static final String GROUP_VERIFY_AMOUNT = "group_verify_amount";
	public static final String GLOBAL_VERIFY_AMOUNT = "global_verify_amount";
	public static final String VERIFY_MAN = "verify_man";
	public static final String VERIFY_DATE = "verify_date";
	public static final String EFFECTSTATUS = "effectstatus";
	public static final String EFFECTDATE = "effectdate";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String ACCRUED_BILLNO = "accrued_billno";
	public static final String BXD_BILLNO = "bxd_billno";
	public static final String PK_IOBSCLASS = "pk_iobsclass";
			
	/**
	 * 属性pk_accrued_bill的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_accrued_bill () {
		return pk_accrued_bill;
	}   
	/**
	 * 属性pk_accrued_bill的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_accrued_bill java.lang.String
	 */
	public void setPk_accrued_bill (java.lang.String newPk_accrued_bill ) {
	 	this.pk_accrued_bill = newPk_accrued_bill;
	} 	  
	/**
	 * 属性pk_accrued_verify的Getter方法.属性名：唯一标识
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_accrued_verify () {
		return pk_accrued_verify;
	}   
	/**
	 * 属性pk_accrued_verify的Setter方法.属性名：唯一标识
	 * 创建日期:
	 * @param newPk_accrued_verify java.lang.String
	 */
	public void setPk_accrued_verify (java.lang.String newPk_accrued_verify ) {
	 	this.pk_accrued_verify = newPk_accrued_verify;
	} 	  
	/**
	 * 属性pk_accrued_detail的Getter方法.属性名：预提明细行
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_accrued_detail () {
		return pk_accrued_detail;
	}   
	/**
	 * 属性pk_accrued_detail的Setter方法.属性名：预提明细行
	 * 创建日期:
	 * @param newPk_accrued_detail java.lang.String
	 */
	public void setPk_accrued_detail (java.lang.String newPk_accrued_detail ) {
	 	this.pk_accrued_detail = newPk_accrued_detail;
	} 	  
	/**
	 * 属性pk_bxd的Getter方法.属性名：报销单
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bxd () {
		return pk_bxd;
	}   
	/**
	 * 属性pk_bxd的Setter方法.属性名：报销单
	 * 创建日期:
	 * @param newPk_bxd java.lang.String
	 */
	public void setPk_bxd (java.lang.String newPk_bxd ) {
	 	this.pk_bxd = newPk_bxd;
	} 	  
	/**
	 * 属性verify_amount的Getter方法.属性名：核销金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getVerify_amount () {
		return verify_amount;
	}   
	/**
	 * 属性verify_amount的Setter方法.属性名：核销金额
	 * 创建日期:
	 * @param newVerify_amount nc.vo.pub.lang.UFDouble
	 */
	public void setVerify_amount (nc.vo.pub.lang.UFDouble newVerify_amount ) {
	 	this.verify_amount = newVerify_amount;
	} 	  
	/**
	 * 属性org_verify_amount的Getter方法.属性名：组织本币核销金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_verify_amount () {
		return org_verify_amount;
	}   
	/**
	 * 属性org_verify_amount的Setter方法.属性名：组织本币核销金额
	 * 创建日期:
	 * @param newOrg_verify_amount nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_verify_amount (nc.vo.pub.lang.UFDouble newOrg_verify_amount ) {
	 	this.org_verify_amount = newOrg_verify_amount;
	} 	  
	/**
	 * 属性group_verify_amount的Getter方法.属性名：集团本币核销金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_verify_amount () {
		return group_verify_amount;
	}   
	/**
	 * 属性group_verify_amount的Setter方法.属性名：集团本币核销金额
	 * 创建日期:
	 * @param newGroup_verify_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_verify_amount (nc.vo.pub.lang.UFDouble newGroup_verify_amount ) {
	 	this.group_verify_amount = newGroup_verify_amount;
	} 	  
	/**
	 * 属性global_verify_amount的Getter方法.属性名：全局本币核销金额
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_verify_amount () {
		return global_verify_amount;
	}   
	/**
	 * 属性global_verify_amount的Setter方法.属性名：全局本币核销金额
	 * 创建日期:
	 * @param newGlobal_verify_amount nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_verify_amount (nc.vo.pub.lang.UFDouble newGlobal_verify_amount ) {
	 	this.global_verify_amount = newGlobal_verify_amount;
	} 	  
	/**
	 * 属性verify_man的Getter方法.属性名：核销人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVerify_man () {
		return verify_man;
	}   
	/**
	 * 属性verify_man的Setter方法.属性名：核销人
	 * 创建日期:
	 * @param newVerify_man java.lang.String
	 */
	public void setVerify_man (java.lang.String newVerify_man ) {
	 	this.verify_man = newVerify_man;
	} 	  
	/**
	 * 属性verify_date的Getter方法.属性名：核销日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getVerify_date () {
		return verify_date;
	}   
	/**
	 * 属性verify_date的Setter方法.属性名：核销日期
	 * 创建日期:
	 * @param newVerify_date nc.vo.pub.lang.UFDate
	 */
	public void setVerify_date (nc.vo.pub.lang.UFDate newVerify_date ) {
	 	this.verify_date = newVerify_date;
	} 	  
	/**
	 * 属性effectstatus的Getter方法.属性名：生效状态
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEffectstatus () {
		return effectstatus;
	}   
	/**
	 * 属性effectstatus的Setter方法.属性名：生效状态
	 * 创建日期:
	 * @param newEffectstatus java.lang.Integer
	 */
	public void setEffectstatus (java.lang.Integer newEffectstatus ) {
	 	this.effectstatus = newEffectstatus;
	} 	  
	/**
	 * 属性effectdate的Getter方法.属性名：生效日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getEffectdate () {
		return effectdate;
	}   
	/**
	 * 属性effectdate的Setter方法.属性名：生效日期
	 * 创建日期:
	 * @param newEffectdate nc.vo.pub.lang.UFDate
	 */
	public void setEffectdate (nc.vo.pub.lang.UFDate newEffectdate ) {
	 	this.effectdate = newEffectdate;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性accrued_billno的Getter方法.属性名：预提单据编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAccrued_billno () {
		return accrued_billno;
	}   
	/**
	 * 属性accrued_billno的Setter方法.属性名：预提单据编号
	 * 创建日期:
	 * @param newAccrued_billno java.lang.String
	 */
	public void setAccrued_billno (java.lang.String newAccrued_billno ) {
	 	this.accrued_billno = newAccrued_billno;
	} 	  
	/**
	 * 属性bxd_billno的Getter方法.属性名：报销单据编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBxd_billno () {
		return bxd_billno;
	}   
	/**
	 * 属性bxd_billno的Setter方法.属性名：报销单据编号
	 * 创建日期:
	 * @param newBxd_billno java.lang.String
	 */
	public void setBxd_billno (java.lang.String newBxd_billno ) {
	 	this.bxd_billno = newBxd_billno;
	} 	  
	/**
	 * 属性pk_iobsclass的Getter方法.属性名：收支项目
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_iobsclass () {
		return pk_iobsclass;
	}   
	/**
	 * 属性pk_iobsclass的Setter方法.属性名：收支项目
	 * 创建日期:
	 * @param newPk_iobsclass java.lang.String
	 */
	public void setPk_iobsclass (java.lang.String newPk_iobsclass ) {
	 	this.pk_iobsclass = newPk_iobsclass;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_accrued_bill";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_accrued_verify";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_accrued_verify";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_accrued_verify";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public AccruedVerifyVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.erm.accruedexpense.AccruedVerifyVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


