/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ep.bx;
	
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class BxDetailLinkQueryVO extends SuperVO {
	private java.lang.String pk_detaillinkquery;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String code_org;
	private java.lang.String org;
	private java.lang.String qryobj0pk;
	private java.lang.String qryobj0code;
	private java.lang.String qryobj0;
	private java.lang.String qryobj1pk;
	private java.lang.String qryobj1code;
	private java.lang.String qryobj1;
	private java.lang.String qryobj2pk;
	private java.lang.String qryobj2code;
	private java.lang.String qryobj2;
	private java.lang.String qryobj3pk;
	private java.lang.String qryobj3code;
	private java.lang.String qryobj3;
	private java.lang.String qryobj4pk;
	private java.lang.String qryobj4code;
	private java.lang.String qryobj4;
	private java.lang.String billclass;
	private java.lang.String pk_billtype;
	private java.lang.String pk_currtype;
	private nc.vo.pub.lang.UFDate djrq;
	private nc.vo.pub.lang.UFDate shrq;
	private nc.vo.pub.lang.UFDate effectdate;
	private java.lang.String zy;
	private java.lang.String pk_jkbx;
	private java.lang.String djbh;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	
	//add 633
	private java.lang.String pk_djlx;//单据类型 264X等

	
	public static final String PK_DETAILLINKQUERY = "pk_detaillinkquery";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String CODE_ORG = "code_org";
	public static final String ORG = "org";
	public static final String QRYOBJ_PREFIX = "qryobj";
	public static final String QRYOBJ_SUFFIX = "pk";
	public static final String QRYOBJ0PK = "qryobj0pk";
	public static final String QRYOBJ0CODE = "qryobj0code";
	public static final String QRYOBJ0 = "qryobj0";
	public static final String QRYOBJ1PK = "qryobj1pk";
	public static final String QRYOBJ1CODE = "qryobj1code";
	public static final String QRYOBJ1 = "qryobj1";
	public static final String QRYOBJ2PK = "qryobj2pk";
	public static final String QRYOBJ2CODE = "qryobj2code";
	public static final String QRYOBJ2 = "qryobj2";
	public static final String QRYOBJ3PK = "qryobj3pk";
	public static final String QRYOBJ3CODE = "qryobj3code";
	public static final String QRYOBJ3 = "qryobj3";
	public static final String QRYOBJ4PK = "qryobj4pk";
	public static final String QRYOBJ4CODE = "qryobj4code";
	public static final String QRYOBJ4 = "qryobj4";
	public static final String BILLCLASS = "billclass";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String DJRQ = "djrq";
	public static final String SHRQ = "shrq";
	public static final String EFFECTDATE = "effectdate";
	public static final String ZY = "zy";
	public static final String PK_JKBX = "pk_jkbx";
	public static final String DJBH = "djbh";
//	public static final String JK_ORI = "jk_ori";
//	public static final String JK_LOC = "jk_loc";
//	public static final String GR_JK_LOC = "gr_jk_loc";
//	public static final String GL_JK_LOC = "gl_jk_loc";
//	public static final String HK_ORI = "hk_ori";
//	public static final String HK_LOC = "hk_loc";
//	public static final String GR_HK_LOC = "gr_hk_loc";
//	public static final String GL_HK_LOC = "gl_hk_loc";
//	public static final String BAL_ORI = "bal_ori";
//	public static final String BAL_LOC = "bal_loc";
//	public static final String GR_BAL_LOC = "gr_bal_loc";
//	public static final String GL_BAL_LOC = "gl_bal_loc";
	
	
	/*********************预算金额************************/
	private UFDouble gl_loc;//全局发生
	private UFDouble gr_loc;//集团发生
	private UFDouble loc;//本币发生
	private UFDouble ori;//原币发生
	public static final String GL_LOC = "gl_loc";//全局发生
	public static final String GR_LOC = "gr_loc";//集团发生
	public static final String LOC = "loc";//本币发生
	public static final String ORI = "ori";//原币发生
	/*********************预算金额************************/
	/**
	 * 属性pk_detaillinkquery的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_detaillinkquery () {
		return pk_detaillinkquery;
	}   
	/**
	 * 属性pk_detaillinkquery的Setter方法.
	 * 创建日期:
	 * @param newPk_detaillinkquery java.lang.String
	 */
	public void setPk_detaillinkquery (java.lang.String newPk_detaillinkquery ) {
	 	this.pk_detaillinkquery = newPk_detaillinkquery;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性code_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode_org () {
		return code_org;
	}   
	/**
	 * 属性code_org的Setter方法.
	 * 创建日期:
	 * @param newCode_org java.lang.String
	 */
	public void setCode_org (java.lang.String newCode_org ) {
	 	this.code_org = newCode_org;
	} 	  
	/**
	 * 属性org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrg () {
		return org;
	}   
	/**
	 * 属性org的Setter方法.
	 * 创建日期:
	 * @param newOrg java.lang.String
	 */
	public void setOrg (java.lang.String newOrg ) {
	 	this.org = newOrg;
	} 	  
	/**
	 * 属性qryobj0pk的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj0pk () {
		return qryobj0pk;
	}   
	/**
	 * 属性qryobj0pk的Setter方法.
	 * 创建日期:
	 * @param newQryobj0pk java.lang.String
	 */
	public void setQryobj0pk (java.lang.String newQryobj0pk ) {
	 	this.qryobj0pk = newQryobj0pk;
	} 	  
	/**
	 * 属性qryobj0code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj0code () {
		return qryobj0code;
	}   
	/**
	 * 属性qryobj0code的Setter方法.
	 * 创建日期:
	 * @param newQryobj0code java.lang.String
	 */
	public void setQryobj0code (java.lang.String newQryobj0code ) {
	 	this.qryobj0code = newQryobj0code;
	} 	  
	/**
	 * 属性qryobj0的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj0 () {
		return qryobj0;
	}   
	/**
	 * 属性qryobj0的Setter方法.
	 * 创建日期:
	 * @param newQryobj0 java.lang.String
	 */
	public void setQryobj0 (java.lang.String newQryobj0 ) {
	 	this.qryobj0 = newQryobj0;
	} 	  
	/**
	 * 属性qryobj1pk的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj1pk () {
		return qryobj1pk;
	}   
	/**
	 * 属性qryobj1pk的Setter方法.
	 * 创建日期:
	 * @param newQryobj1pk java.lang.String
	 */
	public void setQryobj1pk (java.lang.String newQryobj1pk ) {
	 	this.qryobj1pk = newQryobj1pk;
	} 	  
	/**
	 * 属性qryobj1code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj1code () {
		return qryobj1code;
	}   
	/**
	 * 属性qryobj1code的Setter方法.
	 * 创建日期:
	 * @param newQryobj1code java.lang.String
	 */
	public void setQryobj1code (java.lang.String newQryobj1code ) {
	 	this.qryobj1code = newQryobj1code;
	} 	  
	/**
	 * 属性qryobj1的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj1 () {
		return qryobj1;
	}   
	/**
	 * 属性qryobj1的Setter方法.
	 * 创建日期:
	 * @param newQryobj1 java.lang.String
	 */
	public void setQryobj1 (java.lang.String newQryobj1 ) {
	 	this.qryobj1 = newQryobj1;
	} 	  
	/**
	 * 属性qryobj2pk的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj2pk () {
		return qryobj2pk;
	}   
	/**
	 * 属性qryobj2pk的Setter方法.
	 * 创建日期:
	 * @param newQryobj2pk java.lang.String
	 */
	public void setQryobj2pk (java.lang.String newQryobj2pk ) {
	 	this.qryobj2pk = newQryobj2pk;
	} 	  
	/**
	 * 属性qryobj2code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj2code () {
		return qryobj2code;
	}   
	/**
	 * 属性qryobj2code的Setter方法.
	 * 创建日期:
	 * @param newQryobj2code java.lang.String
	 */
	public void setQryobj2code (java.lang.String newQryobj2code ) {
	 	this.qryobj2code = newQryobj2code;
	} 	  
	/**
	 * 属性qryobj2的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj2 () {
		return qryobj2;
	}   
	/**
	 * 属性qryobj2的Setter方法.
	 * 创建日期:
	 * @param newQryobj2 java.lang.String
	 */
	public void setQryobj2 (java.lang.String newQryobj2 ) {
	 	this.qryobj2 = newQryobj2;
	} 	  
	/**
	 * 属性qryobj3pk的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj3pk () {
		return qryobj3pk;
	}   
	/**
	 * 属性qryobj3pk的Setter方法.
	 * 创建日期:
	 * @param newQryobj3pk java.lang.String
	 */
	public void setQryobj3pk (java.lang.String newQryobj3pk ) {
	 	this.qryobj3pk = newQryobj3pk;
	} 	  
	/**
	 * 属性qryobj3code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj3code () {
		return qryobj3code;
	}   
	/**
	 * 属性qryobj3code的Setter方法.
	 * 创建日期:
	 * @param newQryobj3code java.lang.String
	 */
	public void setQryobj3code (java.lang.String newQryobj3code ) {
	 	this.qryobj3code = newQryobj3code;
	} 	  
	/**
	 * 属性qryobj3的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj3 () {
		return qryobj3;
	}   
	/**
	 * 属性qryobj3的Setter方法.
	 * 创建日期:
	 * @param newQryobj3 java.lang.String
	 */
	public void setQryobj3 (java.lang.String newQryobj3 ) {
	 	this.qryobj3 = newQryobj3;
	} 	  
	/**
	 * 属性qryobj4pk的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj4pk () {
		return qryobj4pk;
	}   
	/**
	 * 属性qryobj4pk的Setter方法.
	 * 创建日期:
	 * @param newQryobj4pk java.lang.String
	 */
	public void setQryobj4pk (java.lang.String newQryobj4pk ) {
	 	this.qryobj4pk = newQryobj4pk;
	} 	  
	/**
	 * 属性qryobj4code的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj4code () {
		return qryobj4code;
	}   
	/**
	 * 属性qryobj4code的Setter方法.
	 * 创建日期:
	 * @param newQryobj4code java.lang.String
	 */
	public void setQryobj4code (java.lang.String newQryobj4code ) {
	 	this.qryobj4code = newQryobj4code;
	} 	  
	/**
	 * 属性qryobj4的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj4 () {
		return qryobj4;
	}   
	/**
	 * 属性qryobj4的Setter方法.
	 * 创建日期:
	 * @param newQryobj4 java.lang.String
	 */
	public void setQryobj4 (java.lang.String newQryobj4 ) {
	 	this.qryobj4 = newQryobj4;
	} 	  
	/**
	 * 属性billclass的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillclass () {
		return billclass;
	}   
	/**
	 * 属性billclass的Setter方法.
	 * 创建日期:
	 * @param newBillclass java.lang.String
	 */
	public void setBillclass (java.lang.String newBillclass ) {
	 	this.billclass = newBillclass;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:
	 * @param newPk_billtype java.lang.String
	 */
	public void setPk_billtype (java.lang.String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性pk_currtype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_currtype () {
		return pk_currtype;
	}   
	/**
	 * 属性pk_currtype的Setter方法.
	 * 创建日期:
	 * @param newPk_currtype java.lang.String
	 */
	public void setPk_currtype (java.lang.String newPk_currtype ) {
	 	this.pk_currtype = newPk_currtype;
	} 	  
	/**
	 * 属性djrq的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDjrq () {
		return djrq;
	}   
	/**
	 * 属性djrq的Setter方法.
	 * 创建日期:
	 * @param newDjrq nc.vo.pub.lang.UFDate
	 */
	public void setDjrq (nc.vo.pub.lang.UFDate newDjrq ) {
	 	this.djrq = newDjrq;
	} 	  
	/**
	 * 属性shrq的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getShrq () {
		return shrq;
	}   
	/**
	 * 属性shrq的Setter方法.
	 * 创建日期:
	 * @param newShrq nc.vo.pub.lang.UFDate
	 */
	public void setShrq (nc.vo.pub.lang.UFDate newShrq ) {
	 	this.shrq = newShrq;
	} 	  
	/**
	 * 属性effectdate的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getEffectdate () {
		return effectdate;
	}   
	/**
	 * 属性effectdate的Setter方法.
	 * 创建日期:
	 * @param newEffectdate nc.vo.pub.lang.UFDate
	 */
	public void setEffectdate (nc.vo.pub.lang.UFDate newEffectdate ) {
	 	this.effectdate = newEffectdate;
	} 	  
	/**
	 * 属性zy的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getZy () {
		return zy;
	}   
	/**
	 * 属性zy的Setter方法.
	 * 创建日期:
	 * @param newZy java.lang.String
	 */
	public void setZy (java.lang.String newZy ) {
	 	this.zy = newZy;
	} 	  
	/**
	 * 属性pk_jkbx的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_jkbx () {
		return pk_jkbx;
	}   
	/**
	 * 属性pk_jkbx的Setter方法.
	 * 创建日期:
	 * @param newPk_jkbx java.lang.String
	 */
	public void setPk_jkbx (java.lang.String newPk_jkbx ) {
	 	this.pk_jkbx = newPk_jkbx;
	} 	  
	/**
	 * 属性djbh的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDjbh () {
		return djbh;
	}   
	/**
	 * 属性djbh的Setter方法.
	 * 创建日期:
	 * @param newDjbh java.lang.String
	 */
	public void setDjbh (java.lang.String newDjbh ) {
	 	this.djbh = newDjbh;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_detaillinkquery";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "erm_detaillinkquery";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "erm_detaillinkquery";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public BxDetailLinkQueryVO() {
		super();	
	}
	public UFDouble getGl_loc() {
		return gl_loc;
	}
	public void setGl_loc(UFDouble glLoc) {
		gl_loc = glLoc;
	}
	public UFDouble getGr_loc() {
		return gr_loc;
	}
	public void setGr_loc(UFDouble grLoc) {
		gr_loc = grLoc;
	}
	public UFDouble getLoc() {
		return loc;
	}
	public void setLoc(UFDouble loc) {
		this.loc = loc;
	}
	public UFDouble getOri() {
		return ori;
	}
	public void setOri(UFDouble ori) {
		this.ori = ori;
	}
	public java.lang.String getPk_djlx() {
		return pk_djlx;
	}
	public void setPk_djlx(java.lang.String pk_djlx) {
		this.pk_djlx = pk_djlx;
	}
} 


