/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ep.bx;
	

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class JKBusItemVO extends BXBusItemVO {

	public JKBusItemVO() {
		super();
	}

	public JKBusItemVO(String newPk_bxbusitem) {
		super(newPk_bxbusitem);
	} 
	
} 


