insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTB9',1,-1,null,null,0,1,null,-1,'N',null,-1,'iscreatebal',0,'N',1,'N','N',null,0,'iscreatebal','fipub.queryobj.iscreatebal',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,19,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBA',1,-1,null,null,0,0,null,-1,'N',null,-1,'dsp_objfieldname',0,'N',1,'N','N',null,0,'dsp_objfieldname','fipub.queryobj.dsp_objfieldname',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,4,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBC',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_queryobj',0,'N',1,'N','N',null,0,'pk_queryobj','fipub.queryobj.pk_queryobj',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,1,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBD',1,-1,null,null,0,1,null,-1,'N',null,-1,'billfieldname',0,'N',1,'N','N',null,0,'billfieldname','fipub.queryobj.billfieldname',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,20,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBE',1,-1,null,null,0,1,null,-1,'N',null,-1,'bd_codefield',0,'N',1,'N','N',null,0,'bd_codefield','fipub.queryobj.bd_codefield',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,16,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBF',1,-1,null,null,0,1,null,-1,'N',null,-1,'dsp_objname',0,'N',1,'N','Y',null,0,'dsp_objname','fipub.queryobj.dsp_objname',null,'N',1,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',1,8,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBG',1,-1,null,null,0,1,null,-1,'N',null,-1,'resid',0,'N',1,'N','N',null,0,'resid','fipub.queryobj.resid',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,23,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBH',1,-1,null,null,0,1,null,-1,'N',null,-1,'isqryobj',0,'N',1,'N','N',null,0,'isqryobj','fipub.queryobj.isqryobj',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,18,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBI',1,-1,null,null,0,0,null,-1,'N',null,-1,'ownmodule',0,'N',1,'N','Y',null,0,'ownmodule','fipub.queryobj.ownmodule',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',1,2,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'dsp_order',0,'N',1,'N','N',null,0,'dsp_order','fipub.queryobj.dsp_order',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,9,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBK',1,-1,null,null,0,1,null,-1,'N',null,-1,'qry_objdatatype',0,'N',1,'N','Y',null,0,'qry_objdatatype','fipub.queryobj.qry_objdatatype',null,'N',1,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',1,7,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBL',1,-1,null,null,0,1,null,-1,'N',null,-1,'tallyfieldname',0,'N',1,'N','N',null,0,'tallyfieldname','fipub.queryobj.tallyfieldname',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,22,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBN',1,-1,null,null,0,1,null,-1,'N',null,-1,'bd_namefield',0,'N',1,'N','N',null,0,'bd_namefield','fipub.queryobj.bd_namefield',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,17,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBO',1,-1,null,null,0,1,null,-1,'N',null,-1,'bd_pkfield',0,'N',1,'N','N',null,0,'bd_pkfield','fipub.queryobj.bd_pkfield',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,15,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBP',1,-1,null,null,0,1,null,-1,'N',null,-1,'reporttype',0,'N',1,'N','N',null,0,'reporttype','fipub.queryobj.reporttype',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,10,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','fipub.queryobj.ts',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,26,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBR',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','fipub.queryobj.creator',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,25,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBS',1,-1,null,null,0,1,null,-1,'N',null,-1,'bd_refname',0,'N',1,'N','Y',null,0,'bd_refname','fipub.queryobj.bd_refname',null,'N',1,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',1,12,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBT',1,-1,null,null,0,1,null,-1,'N',null,-1,'returntype',0,'N',1,'N','N',null,0,'returntype','fipub.queryobj.returntype',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,11,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBU',1,-1,null,null,0,1,null,-1,'N',null,-1,'qry_objtablename',0,'N',1,'N','N',null,0,'qry_objtablename','fipub.queryobj.qry_objtablename',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,5,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBV',1,-1,null,null,0,1,null,-1,'N',null,-1,'bd_tablename',0,'N',1,'N','N',null,0,'bd_tablename','fipub.queryobj.bd_tablename',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,14,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBW',1,-1,null,null,0,0,null,-1,'N',null,-1,'dsp_objtablename',0,'N',1,'N','N',null,0,'dsp_objtablename','fipub.queryobj.dsp_objtablename',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,3,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBX',1,-1,null,null,0,1,null,-1,'N',null,-1,'description',0,'N',1,'N','Y',null,0,'description','fipub.queryobj.description',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',1,24,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBY',1,-1,null,null,0,1,null,-1,'N',null,-1,'balfieldname',0,'N',1,'N','N',null,0,'balfieldname','fipub.queryobj.balfieldname',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,21,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTBZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'bd_mdid',0,'N',1,'N','Y',null,0,'bd_mdid','fipub.queryobj.bd_mdid',null,'N',1,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',1,13,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001MTC0',1,-1,null,null,0,1,null,-1,'N',null,-1,'qry_objfieldname',0,'N',1,'N','N',null,0,'qry_objfieldname','fipub.queryobj.qry_objfieldname',null,'N',0,null,'1001Z31000000001MTB8','@@@@',1,null,null,null,'N',0,6,'queryobj','报表查询对象',0,'2014-02-24 13:57:34','N',null,null,null,1,1,'N',1,null,100)
go

