insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG3',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbhl',null,'N',1,'N','N',null,0,'globalbbhl','erm.sruledata.globalbbhl',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,14,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG4',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem3',null,'N',1,'N','N',null,0,'defitem3','erm.sruledata.defitem3',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,46,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG5',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem29',null,'N',1,'N','N',null,0,'defitem29','erm.sruledata.defitem29',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,20,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG6',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_checkele',null,'N',1,'N','N',null,0,'pk_checkele','erm.sruledata.pk_checkele',null,'N',0,null,'1001Z31000000000EID3',null,1,'核算要素,code=N',null,null,'N',0,9,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG7',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem23',null,'N',1,'N','N',null,0,'defitem23','erm.sruledata.defitem23',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,26,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG8',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem26',null,'N',1,'N','N',null,0,'defitem26','erm.sruledata.defitem26',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,23,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG9',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem4',null,'N',1,'N','N',null,0,'defitem4','erm.sruledata.defitem4',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,45,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGA',1,-1,null,null,0,1,null,-1,'N',null,-1,'projecttask',null,'N',1,'N','N',null,0,'projecttask','erm.sruledata.projecttask',null,'N',0,null,'1001Z31000000000EID3',null,1,'项目工作分解结构(WBS),code=N',null,null,'N',0,8,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGB',1,-1,null,null,0,1,null,-1,'N',null,-1,'assume_dept',null,'N',1,'N','N',null,0,'assume_dept','erm.sruledata.assume_dept',null,'N',0,null,'1001Z31000000000EID3',null,1,'部门,code=N',null,null,'N',0,3,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGC',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem22',null,'N',1,'N','N',null,0,'defitem22','erm.sruledata.defitem22',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,27,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGD',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem1',null,'N',1,'N','N',null,0,'defitem1','erm.sruledata.defitem1',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,48,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGE',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbje',null,'N',1,'N','N',null,0,'groupbbje','erm.sruledata.groupbbje',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,18,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGF',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem25',null,'N',1,'N','N',null,0,'defitem25','erm.sruledata.defitem25',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,24,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGG',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem7',null,'N',1,'N','N',null,0,'defitem7','erm.sruledata.defitem7',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,42,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGI',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem24',null,'N',1,'N','N',null,0,'defitem24','erm.sruledata.defitem24',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,25,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGK',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem21',null,'N',1,'N','N',null,0,'defitem21','erm.sruledata.defitem21',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,28,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGL',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem12',null,'N',1,'N','N',null,0,'defitem12','erm.sruledata.defitem12',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,37,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGM',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem10',null,'N',1,'N','N',null,0,'defitem10','erm.sruledata.defitem10',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,39,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGN',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_iobsclass',null,'N',1,'N','N',null,0,'pk_iobsclass','erm.sruledata.pk_iobsclass',null,'N',0,null,'1001Z31000000000EID3',null,1,'收支项目,code=N',null,null,'N',0,6,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGO',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbje',null,'N',1,'N','N',null,0,'bbje','erm.sruledata.bbje',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,16,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGP',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem17',null,'N',1,'N','N',null,0,'defitem17','erm.sruledata.defitem17',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,32,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem27',null,'N',1,'N','N',null,0,'defitem27','erm.sruledata.defitem27',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,22,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGR',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem11',null,'N',1,'N','N',null,0,'defitem11','erm.sruledata.defitem11',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,38,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGS',1,-1,null,null,0,1,null,-1,'N',null,-1,'share_ratio',null,'N',1,'N','Y',null,0,'share_ratio','erm.sruledata.share_ratio',null,'N',0,null,'1001Z31000000000EID3',null,1,'2,-10000000.00,10000000.00',null,null,'N',1,53,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGT',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem19',null,'N',1,'N','N',null,0,'defitem19','erm.sruledata.defitem19',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,30,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGU',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem14',null,'N',1,'N','N',null,0,'defitem14','erm.sruledata.defitem14',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,35,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGV',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem28',null,'N',1,'N','N',null,0,'defitem28','erm.sruledata.defitem28',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,21,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGW',1,-1,null,null,0,1,null,-1,'N',null,-1,'assume_org',null,'N',1,'N','N',null,0,'assume_org','erm.sruledata.assume_org',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,2,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGX',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem30',null,'N',1,'N','N',null,0,'defitem30','erm.sruledata.defitem30',null,'N',0,null,'1001Z31000000000EID3',null,1,'b26fa3cb-4087-4027-a3b6-c83ab2a086a9:部门',null,null,'N',0,19,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGY',1,-1,null,null,0,1,null,-1,'N',null,-1,'jobid',null,'N',1,'N','N',null,0,'jobid','erm.sruledata.jobid',null,'N',0,null,'1001Z31000000000EID3',null,1,'项目,code=N',null,null,'N',0,7,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTH5',1,-1,null,'2',0,1,null,-1,'N',null,-1,'rule_type',0,'N',1,'N','Y',null,0,'rule_type','erm.sharerule.rule_type',null,'N',1,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',1,4,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTH6',1,-1,null,null,0,1,null,-1,'N',null,-1,'rule_code',0,'N',1,'N','Y',null,0,'rule_code','erm.sharerule.rule_code',null,'N',1,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',1,1,'rule_code','编码',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTH7',1,-1,null,null,0,1,null,-1,'N',null,-1,'rule_name',0,'N',1,'N','Y',null,0,'rule_name','erm.sharerule.rule_name',null,'N',1,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',1,2,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbhl',null,'N',1,'N','N',null,0,'bbhl','erm.sruledata.bbhl',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,13,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTIR',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','erm.sharerule.pk_group',null,'N',0,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',0,6,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTIS',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','erm.sharerule.pk_org',null,'N',0,null,'1001Z31000000000EID3','@@@@',0,'全局+当前集团+当前集团下的所有组织',null,null,'N',0,5,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTH8',1,-1,null,null,0,1,null,-1,'N',null,-1,'ruleobj_name',0,'N',1,'N','Y',null,0,'ruleobj_name','erm.sharerule.ruleobj_name',null,'N',1,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',1,3,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000NAR6',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_sharerule',0,'N',1,'N','N',null,0,'pk_sharerule','erm.sharerule.pk_sharerule',null,'N',0,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',0,7,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000QAU9',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','N',null,0,'creationtime','erm.sharerule.creationtime',null,'N',0,null,'1001Z31000000000EID3',null,2,null,null,null,'N',0,2,'creator','creator',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000QAUA',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',null,'N',1,'N','N',null,0,'creator','erm.sharerule.creator',null,'N',0,null,'1001Z31000000000EID3',null,2,null,null,null,'N',0,1,'creator','创建人',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000QAUB',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','N',null,0,'modifiedtime','erm.sharerule.modifiedtime',null,'N',0,null,'1001Z31000000000EID3',null,2,null,null,null,'N',0,4,'creator','creator',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EID4',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem8',null,'N',1,'N','N',null,0,'defitem8','erm.sruledata.defitem8',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,41,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EID5',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem20',null,'N',1,'N','N',null,0,'defitem20','erm.sruledata.defitem20',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,29,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EID6',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_pcorg',null,'N',1,'N','N',null,0,'pk_pcorg','erm.sruledata.pk_pcorg',null,'N',0,null,'1001Z31000000000EID3',null,1,'利润中心,code=N',null,null,'N',0,4,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EID7',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem15',null,'N',1,'N','N',null,0,'defitem15','erm.sruledata.defitem15',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,34,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTGH',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_resacostcenter',null,'N',1,'N','N',null,0,'pk_resacostcenter','erm.sruledata.pk_resacostcenter',null,'N',0,null,'1001Z31000000000EID3',null,1,'管会成本中心,code=N',null,null,'N',0,5,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EID8',1,-1,null,null,0,1,null,-1,'N',null,-1,'assume_amount',null,'N',1,'N','N',null,0,'assume_amount','erm.sruledata.assume_amount',null,'N',0,null,'1001Z31000000000EID3',null,1,'2,-100000000000000000000.00,100000000000000000000.00',null,null,'N',0,52,'rule_data',null,0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EID9',1,-1,null,null,0,1,null,-1,'N',null,-1,'hbbm',null,'N',1,'N','N',null,0,'hbbm','erm.sruledata.hbbm',null,'N',0,null,'1001Z31000000000EID3',null,1,'供应商档案,code=N',null,null,'N',0,11,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDA',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem2',null,'N',1,'N','N',null,0,'defitem2','erm.sruledata.defitem2',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,47,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDB',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem13',null,'N',1,'N','N',null,0,'defitem13','erm.sruledata.defitem13',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,36,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDC',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbhl',null,'N',1,'N','N',null,0,'groupbbhl','erm.sruledata.groupbbhl',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,15,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDD',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','erm.sruledata.ts',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,49,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDE',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem5',null,'N',1,'N','N',null,0,'defitem5','erm.sruledata.defitem5',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,44,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDF',1,-1,null,null,0,1,null,-1,'N',null,-1,'customer',null,'N',1,'N','N',null,0,'customer','erm.sruledata.customer',null,'N',0,null,'1001Z31000000000EID3',null,1,'客户档案,code=N',null,null,'N',0,10,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDG',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',null,'N',1,'N','N',null,0,'bzbm','erm.sruledata.bzbm',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,12,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDH',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem9',null,'N',1,'N','N',null,0,'defitem9','erm.sruledata.defitem9',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,40,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDI',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem18',null,'N',1,'N','N',null,0,'defitem18','erm.sruledata.defitem18',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,31,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem6',null,'N',1,'N','N',null,0,'defitem6','erm.sruledata.defitem6',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,43,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000EIDK',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem16',null,'N',1,'N','N',null,0,'defitem16','erm.sruledata.defitem16',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,33,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG1',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbje',null,'N',1,'N','N',null,0,'globalbbje','erm.sruledata.globalbbje',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,17,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000FTG2',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_cshare_detail',null,'N',1,'N','N',null,0,'pk_cshare_detail','erm.sruledata.pk_cshare_detail',null,'N',0,null,'1001Z31000000000EID3',null,1,null,null,null,'N',0,1,'rule_data','分摊数据',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000037OCZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','erm.sharerule.ts',null,'N',0,null,'1001Z31000000000EID3','@@@@',0,null,null,null,'N',0,8,'rule_code','rule_code',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000086R6',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_brand',0,'N',1,'N','N',null,0,'pk_brand','erm.sruledata.pk_brand',null,'N',0,null,'1001Z31000000000EID3','@@@@',1,'品牌档案,code=N,dpc=fi',null,null,'N',0,51,'rule_data','rule_data',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000086R7',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_proline',0,'N',1,'N','N',null,0,'pk_proline','erm.sruledata.pk_proline',null,'N',0,null,'1001Z31000000000EID3','@@@@',1,'产品线,code=N,dpc=fi',null,null,'N',0,50,'rule_data','rule_data',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000QAUC',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',null,'N',1,'N','N',null,0,'modifier','erm.sharerule.modifier',null,'N',0,null,'1001Z31000000000EID3',null,2,null,null,null,'N',0,3,'creator','creator',0,'2013-10-15 14:10:06','N',null,null,null,1,1,'N',1,null,1)
go

