insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJE',1,-1,'报销人部门',null,0,1,null,-1,'N',null,-1,'deptid',0,'N',1,'N','Y',null,0,'deptid','erm.bxzb.deptid',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,7,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJF',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkbxr',0,'N',1,'N','Y',null,0,'jkbxr','erm.bxzb.jkbxr',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,6,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJG',1,-1,'报销单位',null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','erm.bxzb.pk_org',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,8,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJH',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','Y',null,0,'bzbm','erm.bxzb.bzbm',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,4,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJI',1,-1,null,null,0,1,null,-1,'N',null,-1,'cjkybje',0,'N',1,'N','Y',null,0,'cjkybje','erm.bxzb.cjkybje',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,3,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'djrq',0,'N',1,'N','Y',null,0,'djrq','erm.bxzb.djrq',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,1,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJK',1,-1,null,null,0,1,null,-1,'N',null,-1,'zy',0,'N',1,'N','Y',null,0,'zy','erm.bxzb.zy',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,5,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YLJL',1,-1,null,null,0,0,null,-1,'N',null,-1,'djbh',0,'N',1,'N','Y',null,0,'djbh','erm.bxzb.djbh',null,'N',0,null,'1001Z31000000000YLJD','@@@@',0,null,null,null,'N',1,2,'pk_fiorg','pk_fiorg',0,'2013-09-23 13:39:37','N',null,null,null,1,1,'N',1,null,1)
go

