insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000R9L0','-99',3,0,1,'0',null,'DJRQ','单据日期',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'UC000-0000799',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000R9L1','-99',5,1,1,'0',null,'pk_org','借款单位',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA10001',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ1','-99',5,2,1,'0',null,'jkbxr','借款报销人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA10002',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ2','-99',0,3,1,'0',null,'zy','摘要',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'UC000-0002185',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ3','费用交易类型',5,4,1,'0',null,'djlxbm','交易类型',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=','等于@',0,'@@@@','1001Z31000000000R9KZ',null,'2UC000-000035',0,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ4','-99',0,5,1,'0',null,'BILLTYPENAME','单据类型',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'UC000-0000807',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ5','-99',0,6,1,'0',null,'DJBH','单据编号',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'UCMD1-000144',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ6','-99',5,7,1,'0',null,'BZBM','币种',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'UC000-0001755',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ7','-99',0,8,1,'0',null,'CURRTYPENAME','币种名称',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'UC000-0001762',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ8','-99',0,9,1,'0',null,'BBJE','本期借款本币',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0003',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZ9','-99',0,10,1,'0',null,'HKBBJE','本期还款本币',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0004',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZA','-99',0,11,1,'0',null,'BBYE','借款余额本币',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0005',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZB','-99',0,12,1,'0',null,'YBJE','本期借款原币',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0006',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZC','-99',0,13,1,'0',null,'HKYBJE','本期还款原币',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0007',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZD','-99',0,14,1,'0',null,'YBYE','借款金额原币',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0008',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000000RHZE','-99',0,15,1,'0',null,'QZZT','两清状态',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z31000000000R9KZ',null,'120111LLA0009',2,'newloanreport_union','帐表','2013-09-23 13:40:05','N',null)
go

