insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000005ZAA','费用交易类型',5,2,1,'0',null,'djlxbm','交易类型',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001Z310000000005ZA4',null,'2UC000-000035',0,null,null,'2013-09-23 13:39:53','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000001DNTA','集团',5,0,0,'0',0,'pk_group',null,null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',null,null,'=@>@>=@<@<=@like@','等于@大于@大于等于@小于@小于等于@相似@',0,'@@@@','0001Z310000000005ZA4',null,null,2,null,null,'2013-09-23 13:39:53','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000005ZA5','财务组织',5,1,1,null,0,'pk_org','财务组织',null,'N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001Z310000000005ZA4',null,'UCMD1-000006',2,null,null,'2013-09-23 13:39:53','N',null)
go

