/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.fieldcontrast;

import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class FieldcontrastVO extends SuperVO {
	private java.lang.String pk_fieldcontrast;
	private java.lang.Integer app_scene;
	private java.lang.String src_billtype;
	private java.lang.String src_fieldcode;
	private java.lang.String src_fieldname;;
	private java.lang.String des_billtype;
	private java.lang.String des_fieldcode;
	private java.lang.String des_fieldname;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private java.lang.String src_busitype;
	private java.lang.String src_billtypepk;
	private java.lang.String des_billtypepk;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FIELDCONTRAST = "pk_fieldcontrast";
	public static final String APP_SCENE = "app_scene";
	public static final String SRC_BILLTYPE = "src_billtype";
	public static final String SRC_FIELDCODE = "src_fieldcode";
	public static final String SRC_FIELDNAME = "src_fieldname";
	public static final String SRC_FIELDNAME2 = "src_fieldname2";
	public static final String SRC_FIELDNAME3 = "src_fieldname3";
	public static final String SRC_FIELDNAME4 = "src_fieldname4";
	public static final String SRC_FIELDNAME5 = "src_fieldname5";
	public static final String SRC_FIELDNAME6 = "src_fieldname6";
	public static final String DES_BILLTYPE = "des_billtype";
	public static final String DES_FIELDCODE = "des_fieldcode";
	public static final String DES_FIELDNAME = "des_fieldname";
	public static final String DES_FIELDNAME2 = "des_fieldname2";
	public static final String DES_FIELDNAME3 = "des_fieldname3";
	public static final String DES_FIELDNAME4 = "des_fieldname4";
	public static final String DES_FIELDNAME5 = "des_fieldname5";
	public static final String DES_FIELDNAME6 = "des_fieldname6";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String SRC_BUSITYPE = "src_busitype";
	public static final String SRC_BILLTYPEPK = "src_billtypepk";
	public static final String DES_BILLTYPEPK = "des_billtypepk";

	/**
	 * 属性pk_fieldcontrast的Getter方法.属性名：主键 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_fieldcontrast() {
		return pk_fieldcontrast;
	}

	/**
	 * 属性pk_fieldcontrast的Setter方法.属性名：主键 创建日期:
	 * 
	 * @param newPk_fieldcontrast
	 *            java.lang.String
	 */
	public void setPk_fieldcontrast(java.lang.String newPk_fieldcontrast) {
		this.pk_fieldcontrast = newPk_fieldcontrast;
	}

	/**
	 * 属性app_scene的Getter方法.属性名：应用场景 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getApp_scene() {
		return app_scene;
	}

	/**
	 * 属性app_scene的Setter方法.属性名：应用场景 创建日期:
	 * 
	 * @param newApp_scene
	 *            java.lang.Integer
	 */
	public void setApp_scene(java.lang.Integer newApp_scene) {
		this.app_scene = newApp_scene;
	}

	/**
	 * 属性src_billtype的Getter方法.属性名：来源单据类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getSrc_billtype() {
		return src_billtype;
	}

	/**
	 * 属性src_billtype的Setter方法.属性名：来源单据类型 创建日期:
	 * 
	 * @param newSrc_billtype
	 *            java.lang.String
	 */
	public void setSrc_billtype(java.lang.String newSrc_billtype) {
		this.src_billtype = newSrc_billtype;
	}

	/**
	 * 属性src_fieldcode的Getter方法.属性名：来源字段编码 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getSrc_fieldcode() {
		return src_fieldcode;
	}

	/**
	 * 属性src_fieldcode的Setter方法.属性名：来源字段编码 创建日期:
	 * 
	 * @param newSrc_fieldcode
	 *            java.lang.String
	 */
	public void setSrc_fieldcode(java.lang.String newSrc_fieldcode) {
		this.src_fieldcode = newSrc_fieldcode;
	}

	/**
	 * 属性src_fieldname的Getter方法.属性名：$map.displayName 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getSrc_fieldname() {
		return src_fieldname;
	}

	/**
	 * 属性src_fieldname的Setter方法.属性名：$map.displayName 创建日期:
	 * 
	 * @param newSrc_fieldname
	 *            java.lang.String
	 */
	public void setSrc_fieldname(java.lang.String newSrc_fieldname) {
		this.src_fieldname = newSrc_fieldname;
	}

	/**
	 * 属性des_billtype的Getter方法.属性名：目标单据类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDes_billtype() {
		return des_billtype;
	}

	/**
	 * 属性des_billtype的Setter方法.属性名：目标单据类型 创建日期:
	 * 
	 * @param newDes_billtype
	 *            java.lang.String
	 */
	public void setDes_billtype(java.lang.String newDes_billtype) {
		this.des_billtype = newDes_billtype;
	}

	/**
	 * 属性des_fieldcode的Getter方法.属性名：目标字段编码 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDes_fieldcode() {
		return des_fieldcode;
	}

	/**
	 * 属性des_fieldcode的Setter方法.属性名：目标字段编码 创建日期:
	 * 
	 * @param newDes_fieldcode
	 *            java.lang.String
	 */
	public void setDes_fieldcode(java.lang.String newDes_fieldcode) {
		this.des_fieldcode = newDes_fieldcode;
	}

	/**
	 * 属性des_fieldname的Getter方法.属性名：$map.displayName 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDes_fieldname() {
		return des_fieldname;
	}

	/**
	 * 属性des_fieldname的Setter方法.属性名：$map.displayName 创建日期:
	 * 
	 * @param newDes_fieldname
	 *            java.lang.String
	 */
	public void setDes_fieldname(java.lang.String newDes_fieldname) {
		this.des_fieldname = newDes_fieldname;
	}

	/**
	 * 属性creator的Getter方法.属性名：创建人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreator() {
		return creator;
	}

	/**
	 * 属性creator的Setter方法.属性名：创建人 创建日期:
	 * 
	 * @param newCreator
	 *            java.lang.String
	 */
	public void setCreator(java.lang.String newCreator) {
		this.creator = newCreator;
	}

	/**
	 * 属性creationtime的Getter方法.属性名：创建时间 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime() {
		return creationtime;
	}

	/**
	 * 属性creationtime的Setter方法.属性名：创建时间 创建日期:
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
		this.creationtime = newCreationtime;
	}

	/**
	 * 属性modifier的Getter方法.属性名：最后修改人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getModifier() {
		return modifier;
	}

	/**
	 * 属性modifier的Setter方法.属性名：最后修改人 创建日期:
	 * 
	 * @param newModifier
	 *            java.lang.String
	 */
	public void setModifier(java.lang.String newModifier) {
		this.modifier = newModifier;
	}

	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime() {
		return modifiedtime;
	}

	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间 创建日期:
	 * 
	 * @param newModifiedtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
		this.modifiedtime = newModifiedtime;
	}

	/**
	 * 属性pk_org的Getter方法.属性名：所属组织 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.属性名：所属组织 创建日期:
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}

	/**
	 * 属性pk_group的Getter方法.属性名：所属集团 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}

	/**
	 * 属性pk_group的Setter方法.属性名：所属集团 创建日期:
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}

	/**
	 * 属性src_busitype的Getter方法.属性名：来源单据业务类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getSrc_busitype() {
		return src_busitype;
	}

	/**
	 * 属性src_busitype的Setter方法.属性名：来源单据业务类型 创建日期:
	 * 
	 * @param newSrc_busitype
	 *            java.lang.String
	 */
	public void setSrc_busitype(java.lang.String newSrc_busitype) {
		this.src_busitype = newSrc_busitype;
	}

	/**
	 * 属性src_billtypepk的Getter方法.属性名：来源单据类型标识 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getSrc_billtypepk() {
		return src_billtypepk;
	}

	/**
	 * 属性src_billtypepk的Setter方法.属性名：来源单据类型标识 创建日期:
	 * 
	 * @param newSrc_billtypepk
	 *            java.lang.String
	 */
	public void setSrc_billtypepk(java.lang.String newSrc_billtypepk) {
		this.src_billtypepk = newSrc_billtypepk;
	}

	/**
	 * 属性des_billtypepk的Getter方法.属性名：目标单据类型标识 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDes_billtypepk() {
		return des_billtypepk;
	}

	/**
	 * 属性des_billtypepk的Setter方法.属性名：目标单据类型标识 创建日期:
	 * 
	 * @param newDes_billtypepk
	 *            java.lang.String
	 */
	public void setDes_billtypepk(java.lang.String newDes_billtypepk) {
		this.des_billtypepk = newDes_billtypepk;
	}

	/**
	 * 属性dr的Getter方法.属性名：dr 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.属性名：dr 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法.属性名：ts 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.属性名：ts 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_fieldcontrast";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_fieldcontrast";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_fieldcontrast";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public FieldcontrastVO() {
		super();
	}
}
