insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXY','-99',0,71,1,'0',0,'zyx30','自定义项30',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000772',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXZ','-99',0,72,1,'0',0,'zyx29','自定义项29',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000770',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY0','-99',0,73,1,'0',0,'zyx28','自定义项28',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000769',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY1','-99',0,74,1,'0',0,'zyx27','自定义项27',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000768',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY2','-99',0,75,1,'0',0,'zyx26','自定义项26',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000767',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY3','-99',0,76,1,'0',0,'zyx25','自定义项25',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000766',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY4','-99',0,77,1,'0',0,'zyx24','自定义项24',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000765',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY5','-99',0,78,1,'0',0,'zyx23','自定义项23',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000764',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY6','-99',0,79,1,'0',0,'zyx22','自定义项22',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000763',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXQ','-99',0,63,1,'0',0,'zyx1','自定义项1',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000749',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H1','2',2,47,1,'0',0,'globalcjkbbje','全局冲借款本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H2','2',2,48,1,'0',0,'globalhkbbje','全局还款本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H3','2',2,49,1,'0',0,'globalzfbbje','全局支付本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY7','-99',0,80,1,'0',0,'zyx21','自定义项21',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000762',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY8','-99',0,81,1,'0',0,'zyx20','自定义项20',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000761',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WY9','-99',0,82,1,'0',0,'zyx19','自定义项19',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000759',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYA','-99',0,83,1,'0',0,'zyx18','自定义项18',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000758',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYB','-99',0,84,1,'0',0,'zyx17','自定义项17',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000757',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYC','-99',0,85,1,'0',0,'zyx16','自定义项16',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000756',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYD','-99',0,86,1,'0',0,'zyx15','自定义项15',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000755',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYE','-99',0,87,1,'0',0,'zyx14','自定义项14',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000754',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYF','-99',0,88,1,'0',0,'zyx13','自定义项13',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000753',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYG','-99',0,89,1,'0',0,'zyx12','自定义项12',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000752',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYH','-99',0,90,1,'0',0,'zyx11','自定义项11',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000751',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYI','-99',0,91,1,'0',0,'zyx10','自定义项10',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000750',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WYJ','-99',0,92,1,'0',0,'zyx9','自定义项9',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000788',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FQ','财务组织',5,0,1,'0',0,'pk_org','报销单位',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FR','财务组织版本',5,1,1,'0',0,'pk_org_v','报销单位历史版本',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FS','集团',5,2,1,'0',0,'pk_group','集团',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-001007',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FT','财务组织',5,3,1,'0',0,'pk_fiorg','财务组织',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000908',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FU','利润中心',5,4,1,'0',0,'pk_pcorg','利润中心',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000161',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FV','利润中心版本',5,5,1,'0',0,'pk_pcorg_v','利润中心历史版本',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FW','用户',5,6,1,'0',0,'payman','支付人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000433',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FX','资金计划项目',5,7,1,'0',0,'cashproj','资金计划项目',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000941',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FY','业务单元',5,8,1,'0',0,'fydwbm','费用承担单位',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1FZ','行政组织',5,9,1,'0',0,'dwbm','报销人单位',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G0','-99',0,10,1,'0',0,'djdl','单据大类',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000187',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G1','费用交易类型',5,11,1,'0',0,'djlxbm','交易类型',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000035',0,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G3','-99',3,13,1,'0',0,'djrq','单据日期',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000190',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G4','-99',8,14,1,'0',0,'shrq','审批时间',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000275',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G5','-99',3,15,1,'0',0,'jsrq','结算日期',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000713',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G6','部门',5,16,1,'0',0,'deptid','报销人部门',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G7','人员',5,17,1,'0',0,'receiver','收款人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GX','-99',0,43,1,'0',0,'kjnd','会计年度',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000072',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GY','用户',5,44,1,'0',0,'jsr','结算人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GZ','-99',3,45,1,'0',0,'officialprintdate','正式打印日期',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000564',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H0','用户',5,46,1,'0',0,'officialprintuser','正式打印人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000563',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H4','2',2,50,1,'0',0,'globalbbje','全局报销本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H5','2',2,51,1,'0',0,'groupcjkbbje','集团冲借款本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H6','2',2,52,1,'0',0,'grouphkbbje','集团还款本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H7','2',2,53,1,'0',0,'groupzfbbje','集团支付本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H8','2',2,54,1,'0',0,'groupbbje','集团报销本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1H9','2',2,55,1,'0',0,'globalbbhl','全局本币汇率',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000119',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G8','人员',5,18,1,'0',0,'jkbxr','借款报销人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HA','2',2,56,1,'0',0,'groupbbhl','集团本币汇率',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-001016',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HB','-99',8,57,1,'0',0,'modifiedtime','最后修改时间',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000491',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HC','用户',5,58,1,'0',0,'creator','创建人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000155',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HD','客商银行账户',5,59,1,'0',0,'custaccount','客商银行账户',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HE','散户',5,60,1,'0',0,'freecust','散户',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000454',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HF','客户档案',5,61,1,'0',0,'customer','客户',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000283',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1HG','项目工作分解结构(WBS)',5,62,1,'0',0,'projecttask','项目任务',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-001023',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000001AT7C','管会成本中心',5,93,1,'0',0,'pk_resacostcenter','成本中心',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z31000000001AT7D','现金账户',5,94,1,'0',0,'pk_cashaccount','现金帐户',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXR','-99',0,64,1,'0',0,'zyx2','自定义项2',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000760',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXS','-99',0,65,1,'0',0,'zyx3','自定义项3',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000771',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXT','-99',0,66,1,'0',0,'zyx4','自定义项4',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000782',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXU','-99',0,67,1,'0',0,'zyx5','自定义项5',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000784',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXV','-99',0,68,1,'0',0,'zyx6','自定义项6',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000785',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXW','-99',0,69,1,'0',0,'zyx7','自定义项7',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000786',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z310000000047WXX','-99',0,70,1,'0',0,'zyx8','自定义项8',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000787',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G9','用户',5,19,1,'0',0,'operator','录入人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000342',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GA','用户',5,20,1,'0',0,'approver','审批人',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000271',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GB','结算方式',5,21,1,'0',0,'jsfs','结算方式',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000712',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GC','个人银行账户',5,22,1,'0',0,'skyhzh','个人银行账户',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GD','使用权参照',5,23,1,'0',0,'fkyhzh','单位银行账户',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GE','2',2,24,1,'0',0,'cjkybje','冲借款原币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GF','2',2,25,1,'0',0,'cjkbbje','冲借款本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GG','2',2,26,1,'0',0,'hkbbje','还款本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GH','2',2,27,1,'0',0,'zfybje','支付原币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GI','2',2,28,1,'0',0,'zfbbje','支付本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000436',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GK','收支项目',5,30,1,'0',0,'szxmid','收支项目',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000442',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GL','现金流量项目',5,31,1,'0',0,'cashitem','现金流量项目',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000615',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GM','部门',5,32,1,'0',0,'fydeptid','费用承担部门',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GN','币种档案',5,33,1,'0',0,'bzbm','币种',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000315',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GO','2',2,34,1,'0',0,'bbhl','本币汇率',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000511',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GP','2',2,35,1,'0',0,'ybje','报销原币金额',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GQ','2',2,36,1,'0',0,'bbje','报销本币金额',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GR','常用摘要',5,37,1,'0',0,'zy','事由',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,null,2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GS','供应商档案',5,38,1,'0',0,'hbbm','供应商',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000089',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GT','IM,aed2a08a-03a0-4db7-9ab1-c30e1dc1ca17',6,39,1,'0',0,'djzt','单据状态',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000192',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GU','IM,6d3eb44c-db5a-45a5-812a-3a040a3746af',6,40,1,'0',0,'spzt','审批状态',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000276',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GV','-99',4,41,1,'0',0,'qcbz','期初标志',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000499',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GW','-99',0,42,1,'0',0,'kjqj','会计期间',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000074',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1G2','-99',0,12,1,'0',0,'djbh','单据编号',null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'like@=@left like@right like@','包含@等于@左包含@右包含@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-000198',2,null,null,'2013-09-23 13:39:50','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('0001Z31000000001W1GJ','项目',5,29,1,'0',0,'jobid','项目',null,'N','Y','N','N','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z31000000000YRJM',null,'2UC000-001021',2,null,null,'2013-09-23 13:39:50','N',null)
go

