insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000000YRU',1,0,'控制对象字段名称',null,0,1,null,-1,'N',null,20,'src_field',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z3100000000069CS','@@@@',1,null,'12011erm0001',null,'N',1,3,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000015P4',1,0,'费用申请单字段名称',null,0,1,null,-1,'N',null,20,'des_field',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z3100000000069CS',null,1,null,'12011erm0004',null,'N',1,2,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000015PX',1,-1,null,null,0,1,null,-1,'N',null,-1,'src_busitype',0,'N',1,'N','N',null,0,'src_busitype','erm.fieldcontrast.src_busitype',null,'N',0,null,'1001Z3100000000069CS','@@@@',1,null,null,null,'N',0,4,'fieldcontrast','fieldcontrast',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000015UE',1,-1,'费用申请单交易类型',null,0,1,null,-1,'N',null,-1,'des_billtypepk',0,'N',1,'N','Y',null,0,'des_billtypepk','erm.fieldcontrast.des_billtypepk',null,'N',0,null,'1001Z3100000000069CS','@@@@',1,'费用单据类型+交易类型,code=N','12011erm0011',null,'N',1,1,'fieldcontrast','fieldcontrast',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CT',1,-1,null,null,0,1,null,-1,'N',null,-1,'src_fieldcode',null,'N',1,'N','N',null,0,'src_fieldcode','erm.fieldcontrast.src_fieldcode',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,12,'fieldcontrast','费用单据间字段对照',0,'2014-07-15 12:56:09','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CU',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','N',null,0,'modifiedtime','erm.fieldcontrast.modifiedtime',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,15,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CV',1,-1,null,null,0,0,null,-1,'N',null,-1,'des_billtype',null,'N',1,'N','N',null,0,'des_billtype','erm.fieldcontrast.des_billtype',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,10,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CW',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','N',null,0,'creationtime','erm.fieldcontrast.creationtime',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,13,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CX',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',null,'N',1,'N','N',null,0,'creator','erm.fieldcontrast.creator',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,11,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CY',1,-1,null,null,0,1,null,-1,'N',null,-1,'des_fieldcode',null,'N',1,'N','N',null,0,'des_fieldcode','erm.fieldcontrast.des_fieldcode',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,9,'fieldcontrast','费用单据间字段对照',0,'2014-07-15 12:56:09','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069CZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','erm.fieldcontrast.pk_org',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,16,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','erm.fieldcontrast.pk_group',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,17,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D1',1,-1,null,null,0,1,null,-1,'N',null,-1,'src_billtype',null,'N',1,'N','N',null,0,'src_billtype','erm.fieldcontrast.src_billtype',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,7,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D2',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_fieldcontrast',null,'N',1,'N','N',null,0,'pk_fieldcontrast','erm.fieldcontrast.pk_fieldcontrast',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,19,'fieldcontrast',null,0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D3',1,-1,null,null,0,1,null,-1,'N',null,-1,'des_fieldname',null,'N',1,'N','N',null,0,'des_fieldname','erm.fieldcontrast.des_fieldname',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,8,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D4',1,-1,null,'4',0,0,null,-1,'N',null,-1,'app_scene',null,'N',1,'N','N',null,0,'app_scene','erm.fieldcontrast.app_scene',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,6,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D5',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',null,'N',1,'N','N',null,0,'modifier','erm.fieldcontrast.modifier',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,14,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D6',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','erm.fieldcontrast.ts',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,18,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000069D7',1,-1,null,null,0,1,null,-1,'N',null,-1,'src_fieldname',null,'N',1,'N','N',null,0,'src_fieldname','erm.fieldcontrast.src_fieldname',null,'N',0,null,'1001Z3100000000069CS',null,1,null,null,null,'N',0,5,'fieldcontrast','费用单据间字段对照',0,'2013-09-23 13:39:42','N',null,null,null,1,1,'N',1,null,100)
go

