insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZMW','部门',5,1,1,null,0,'assume_dept','承担部门',null,'N','Y','N','N','N','N','N','N','N','Y','N','Y','N','N','Y',null,'Y',9999,null,'=','等于@大于@大于等于@小于@小于等于@相似@',0,'@@@@','1001Z310000000012ZMJ',null,'120110908020002',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZMX','收支项目',5,2,1,null,0,'pk_iobsclass','收支项目',null,'N','Y','N','N','N','N','N','N','N','Y','N','Y','N','N','Y',null,'Y',9999,null,'=','等于@大于@大于等于@小于@小于等于@相似@',0,'@@@@','1001Z310000000012ZMJ',null,'UC000-0002217',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZMY','管会成本中心',5,3,1,null,null,'pk_resacostcenter','成本中心',null,'N','Y','N','Y','N','N','N','N','N','Y','N','Y','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z310000000012ZMJ',null,'120110908020005',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZMZ','2',2,4,1,null,null,'assume_amount','承担金额',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','等于@大于@大于等于@小于@小于等于@包含@',0,'@@@@','1001Z310000000012ZMJ',null,'120110908020006',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZN0','人员',5,5,1,null,0,'bx_jkbxr','报销人',null,'N','Y','N','N','N','N','N','N','N','Y','N','Y','N','N','Y',null,'Y',9999,null,'=','等于@大于@大于等于@小于@小于等于@相似@',0,'@@@@','1001Z310000000012ZMJ',null,'120110908020004',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZN1','业务单元',5,6,1,null,null,'assume_org','承担单位',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z310000000012ZMJ',null,'120110908020001',2,null,null,'2014-03-12 08:52:09','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZN2','利润中心',5,7,1,null,0,'pk_pcorg','利润中心',null,'N','Y','N','N','N','N','N','N','N','Y','N','N','N','N','Y',null,'Y',9999,null,'=','等于@大于@大于等于@小于@小于等于@相似@',0,'@@@@','1001Z310000000012ZMJ',null,'120110908020007',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZN3','币种档案',5,8,1,null,null,'pk_currtype','币种',null,'N','Y','N','N','N','N','N','N','N','Y','N','Y','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z310000000012ZMJ',null,'UC000-0001755',2,null,null,'2014-01-07 09:08:56','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZN4','财务组织',5,9,1,null,null,'pk_org','财务组织',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z310000000012ZMJ',null,'12011050041',2,null,null,'2014-03-11 16:40:59','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z310000000012ZN5','会计年度',5,10,1,null,null,'accyear','会计年度',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001Z310000000012ZMJ',null,'UC000-0000237',1,null,null,'2014-01-07 09:08:56','N',null)
go

