insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002GCK2',1,-1,null,null,0,1,null,-1,'N',null,-1,'paytarget',null,'N',1,'N','N',null,0,'paytarget','erm.jkbxzb.paytarget',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,90,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002GCK4',1,-1,null,null,0,0,null,-1,'N',null,-1,'vouchertag',0,'N',1,'N','N',null,0,'vouchertag','erm.jkbxzb.vouchertag',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,null,null,null,'N',0,91,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000014WE',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_checkele',0,'N',1,'N','N',null,0,'pk_checkele','erm.jkbxzb.pk_checkele',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,'核算要素',null,null,'N',0,87,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NN',1,-1,null,null,0,1,null,-1,'N',null,-1,'fydwbm',0,'N',1,'N','N',null,0,'fydwbm','erm.jkbxzb.fydwbm',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,43,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NP',1,-1,null,null,0,1,null,-1,'N',null,-1,'officialprintuser',0,'N',1,'N','N',null,0,'officialprintuser','erm.jkbxzb.officialprintuser',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,31,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'spzt',0,'N',1,'N','Y',null,0,'spzt','erm.jkbxzb.spzt',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,18,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NR',1,-1,null,null,0,1,null,-1,'N',null,-1,'jobid',0,'N',1,'N','N',null,0,'jobid','erm.jkbxzb.jobid',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,59,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042O1',1,-1,null,null,0,1,null,-1,'N',null,-1,'kjqj',0,'N',1,'N','N',null,0,'kjqj','erm.jkbxzb.kjqj',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,71,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042O4',1,-1,null,null,0,1,null,-1,'N',null,-1,'zy',0,'N',1,'N','N',null,0,'zy','erm.jkbxzb.zy',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,66,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042O5',1,-1,null,null,0,1,null,-1,'N',null,-1,'receiver',0,'N',1,'N','N',null,0,'receiver','erm.jkbxzb.receiver',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,47,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042O7',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','erm.jkbxzb.creationtime',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,76,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042O8',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_pcorg',0,'N',1,'N','N',null,0,'pk_pcorg','erm.jkbxzb.pk_pcorg',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,37,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OB',1,-1,null,null,0,1,null,-1,'N',null,-1,'djzt',0,'N',1,'N','Y',null,0,'djzt','erm.jkbxzb.djzt',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,15,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MX',1,-1,null,null,0,1,null,-1,'N',null,-1,'fkyhzh',0,'N',1,'N','N',null,0,'fkyhzh','erm.jkbxzb.fkyhzh',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,52,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OC',1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','erm.jkbxzb.approver',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,85,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OD',1,-1,null,'0',0,1,null,-1,'N',null,-1,'qzzt',0,'N',1,'N','Y',null,0,'qzzt','erm.jkbxzb.qzzt',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,20,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OF',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_jkbx',0,'N',1,'N','N',null,0,'pk_jkbx','erm.jkbxzb.pk_jkbx',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,44,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OG',1,-1,'交易类型编码',null,0,1,null,-1,'N',null,-1,'djlxbm',0,'N',1,'N','N',null,0,'djlxbm','erm.jkbxzb.djlxbm',null,'N',0,null,'1001Z3100000000042LV',null,0,null,'12011erm0010',null,'N',0,4,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OH',1,-1,null,null,0,1,null,-1,'N',null,-1,'szxmid',0,'N',1,'N','N',null,0,'szxmid','erm.jkbxzb.szxmid',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,60,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalzfbbje',0,'N',1,'N','N',null,0,'globalzfbbje','erm.jkbxzb.globalzfbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,7,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OK',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','erm.jkbxzb.pk_org_v',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,2,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OL',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','erm.jkbxzb.pk_group',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,32,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OM',1,-1,null,null,0,1,null,-1,'N',null,-1,'jsfs',0,'N',1,'N','N',null,0,'jsfs','erm.jkbxzb.jsfs',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,49,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042ON',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','erm.jkbxzb.modifiedtime',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,77,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OO',1,-1,null,null,0,1,null,-1,'N',null,-1,'payman',0,'N',1,'N','N',null,0,'payman','erm.jkbxzb.payman',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,40,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OP',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbhl',0,'N',1,'N','N',null,0,'bbhl','erm.jkbxzb.bbhl',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,63,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalhkbbje',0,'N',1,'N','N',null,0,'globalhkbbje','erm.jkbxzb.globalhkbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,5,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OR',1,-1,null,null,0,1,null,-1,'Y',null,-1,'djbh',0,'N',1,'Y','Y',null,0,'djbh','erm.jkbxzb.djbh',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,8,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OS',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','erm.jkbxzb.ts',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,26,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OU',1,-1,null,null,0,1,null,-1,'N',null,-1,'fydeptid',0,'N',1,'N','N',null,0,'fydeptid','erm.jkbxzb.fydeptid',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,62,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NS',1,-1,null,null,0,1,null,-1,'N',null,-1,'fjzs',0,'N',1,'N','N',null,0,'fjzs','erm.jkbxzb.fjzs',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,68,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NT',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbhl',0,'N',1,'N','N',null,0,'groupbbhl','erm.jkbxzb.groupbbhl',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,22,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NV',1,-1,null,null,0,1,null,-1,'N',null,-1,'jsr',0,'N',1,'N','N',null,0,'jsr','erm.jkbxzb.jsr',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,73,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NX',1,-1,null,null,0,1,null,-1,'N',null,-1,'deptid',0,'N',1,'N','Y',null,0,'deptid','erm.jkbxzb.deptid',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,21,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NY',1,-1,null,'false',0,1,null,-1,'N',null,-1,'isinitgroup',0,'N',1,'N','N',null,0,'isinitgroup','erm.jkbxzb.isinitgroup',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,81,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'operator',0,'N',1,'N','N',null,0,'operator','erm.jkbxzb.operator',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,48,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042O0',1,-1,null,null,0,1,null,-1,'N',null,-1,'cjkybje',0,'N',1,'N','N',null,0,'cjkybje','erm.jkbxzb.cjkybje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,53,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cashitem',0,'N',1,'N','N',null,0,'cashitem','erm.jkbxzb.cashitem',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,61,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042N3',1,-1,null,null,0,1,null,-1,'N',null,-1,'jkbxr',0,'N',1,'N','Y',null,0,'jkbxr','erm.jkbxzb.jkbxr',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,24,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042N4',1,-1,null,null,0,1,null,-1,'N',null,-1,'busitype',0,'N',1,'N','N',null,0,'busitype','erm.jkbxzb.busitype',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,74,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042N5',1,-1,null,null,0,1,null,-1,'N',null,-1,'reimrule',0,'N',1,'N','N',null,0,'reimrule','erm.jkbxzb.reimrule',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,38,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042N7',1,-1,null,null,0,1,null,-1,'N',null,-1,'custaccount',0,'N',1,'N','N',null,0,'custaccount','erm.jkbxzb.custaccount',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,79,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042N9',1,-1,null,null,0,1,null,-1,'N',null,-1,'freecust',0,'N',1,'N','N',null,0,'freecust','erm.jkbxzb.freecust',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,80,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NA',1,-1,null,'false',0,1,null,-1,'N',null,-1,'ischeck',0,'N',1,'N','N',null,0,'ischeck','erm.jkbxzb.ischeck',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,70,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NB',1,-1,null,null,0,1,null,-1,'N',null,-1,'bbje',0,'N',1,'N','N',null,0,'bbje','erm.jkbxzb.bbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,65,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NC',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalcjkbbje',0,'N',1,'N','N',null,0,'globalcjkbbje','erm.jkbxzb.globalcjkbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,3,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042ND',1,-1,'金额',null,0,1,null,-1,'N',null,-1,'total',0,'N',1,'N','Y',null,0,'total','erm.jkbxzb.total',null,'N',0,null,'1001Z3100000000042LV',null,0,null,'UC000-0004112',null,'N',0,13,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NF',1,-1,null,null,0,1,null,-1,'N',null,-1,'pjh',0,'N',1,'N','N',null,0,'pjh','erm.jkbxzb.pjh',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,50,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NG',1,-1,null,null,0,1,null,-1,'N',null,-1,'cashproj',0,'N',1,'N','N',null,0,'cashproj','erm.jkbxzb.cashproj',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,42,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NH',1,-1,null,null,0,1,null,-1,'N',null,-1,'zfbbje',0,'N',1,'N','N',null,0,'zfbbje','erm.jkbxzb.zfbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,58,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NI',1,-1,null,null,0,1,null,-1,'N',null,-1,'hkybje',0,'N',1,'N','N',null,0,'hkybje','erm.jkbxzb.hkybje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,55,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'skyhzh',0,'N',1,'N','N',null,0,'skyhzh','erm.jkbxzb.skyhzh',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,51,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042NK',1,-1,null,null,0,1,null,-1,'N',null,-1,'zfybje',0,'N',1,'N','N',null,0,'zfybje','erm.jkbxzb.zfybje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,57,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OV',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupcjkbbje',0,'N',1,'N','N',null,0,'groupcjkbbje','erm.jkbxzb.groupcjkbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,12,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OW',1,-1,null,null,0,1,null,-1,'N',null,-1,'jsh',0,'N',1,'N','N',null,0,'jsh','erm.jkbxzb.jsh',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,69,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042OX',1,-1,null,null,0,1,null,-1,'N',null,-1,'jsrq',0,'N',1,'N','N',null,0,'jsrq','erm.jkbxzb.jsrq',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,46,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005EIF',1,-1,null,null,0,1,null,-1,'N',null,-1,'checktype',0,'N',1,'N','N',null,0,'checktype','erm.jkbxzb.checktype',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,83,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000AKEP',1,4,'选中','false',0,0,null,-1,'N',null,20,'selected',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1001Z3100000000042LV',null,0,null,'UC000-0004043',null,'N',0,1,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000GI8E',1,-1,null,null,0,1,null,-1,'N',null,-1,'projecttask',0,'N',1,'N','N',null,0,'projecttask','erm.jkbxzb.projecttask',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,84,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042N0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_fiorg',0,'N',1,'N','N',null,0,'pk_fiorg','erm.jkbxzb.pk_fiorg',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,36,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001649I',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','erm.jkbxzb.modifier',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,82,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000WG7O',1,-1,null,null,0,1,null,-1,'N',null,-1,'fydeptid_v',0,'N',1,'N','N',null,0,'fydeptid_v','erm.jkbxzb.fydeptid_v',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,34,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000WG7P',1,-1,null,null,0,1,null,-1,'N',null,-1,'deptid_v',0,'N',1,'N','N',null,0,'deptid_v','erm.jkbxzb.deptid_v',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,35,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000WG7Q',1,-1,null,null,0,1,null,-1,'N',null,-1,'fydwbm_v',0,'N',1,'N','N',null,0,'fydwbm_v','erm.jkbxzb.fydwbm_v',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,33,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042LW',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupbbje',0,'N',1,'N','N',null,0,'groupbbje','erm.jkbxzb.groupbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,17,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042LX',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbje',0,'N',1,'N','N',null,0,'globalbbje','erm.jkbxzb.globalbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,9,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042LZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'sxbz',0,'N',1,'N','N',null,0,'sxbz','erm.jkbxzb.sxbz',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,75,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042M1',1,-1,null,null,0,1,null,-1,'N',null,-1,'hkbbje',0,'N',1,'N','N',null,0,'hkbbje','erm.jkbxzb.hkbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,56,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042M5',1,-1,null,null,0,1,null,-1,'N',null,-1,'groupzfbbje',0,'N',1,'N','N',null,0,'groupzfbbje','erm.jkbxzb.groupzfbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,16,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042M9',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','erm.jkbxzb.creator',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,78,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MA',1,-1,null,null,0,1,null,-1,'N',null,-1,'hbbm',0,'N',1,'N','N',null,0,'hbbm','erm.jkbxzb.hbbm',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,67,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MD',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_item',0,'N',1,'N','N',null,0,'pk_item','erm.jkbxzb.pk_item',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,28,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042ME',1,-1,null,null,0,1,null,-1,'N',null,-1,'ybje',0,'N',1,'N','N',null,0,'ybje','erm.jkbxzb.ybje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,64,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MG',1,-1,null,null,0,1,null,-1,'N',null,-1,'grouphkbbje',0,'N',1,'N','N',null,0,'grouphkbbje','erm.jkbxzb.grouphkbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,14,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MI',1,-1,null,null,0,1,null,-1,'N',null,-1,'paydate',0,'N',1,'N','N',null,0,'paydate','erm.jkbxzb.paydate',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,39,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MK',1,-1,null,null,0,1,null,-1,'N',null,-1,'payflag',0,'N',1,'N','N',null,0,'payflag','erm.jkbxzb.payflag',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,41,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MM',1,-1,null,null,0,1,null,-1,'N',null,-1,'mngaccid',0,'N',1,'N','N',null,0,'mngaccid','erm.jkbxzb.mngaccid',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,27,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MN',1,-1,null,null,0,1,null,-1,'N',null,-1,'djdl',0,'N',1,'N','N',null,0,'djdl','erm.jkbxzb.djdl',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,45,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MO',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','Y',null,0,'bzbm','erm.jkbxzb.bzbm',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,11,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MP',1,-1,null,null,0,1,null,-1,'N',null,-1,'globalbbhl',0,'N',1,'N','N',null,0,'globalbbhl','erm.jkbxzb.globalbbhl',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,19,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'officialprintdate',0,'N',1,'N','N',null,0,'officialprintdate','erm.jkbxzb.officialprintdate',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,30,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MS',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','erm.jkbxzb.pk_org',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,23,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MT',1,-1,null,null,0,1,null,-1,'N',null,-1,'djrq',0,'N',1,'N','Y',null,0,'djrq','erm.jkbxzb.djrq',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,10,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MU',1,-1,null,'false',0,1,null,-1,'N',null,-1,'qcbz',0,'N',1,'N','N',null,0,'qcbz','erm.jkbxzb.qcbz',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,25,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MV',1,-1,null,null,0,1,null,-1,'N',null,-1,'kjnd',0,'N',1,'N','N',null,0,'kjnd','erm.jkbxzb.kjnd',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,72,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000042MB',1,-1,null,null,0,1,null,-1,'N',null,-1,'cjkbbje',0,'N',1,'N','N',null,0,'cjkbbje','erm.jkbxzb.cjkbbje',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,54,'arap_bxzb','arap_bxzb',1,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000002FYR',1,-1,'费用申请单',null,0,0,null,-1,'Y','pk_item',-1,'pk_item.billno',null,'N',1,'Y','Y',null,0,'billno','erm.mtapp_bill.billno',null,'N',0,null,'1001Z3100000000042LV',null,0,null,'2201112-000006',null,'N',0,29,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003MCWJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'shrq',0,'N',1,'N','Y',null,0,'shrq','erm.jkbxzb.shrq',null,'N',0,null,'1001Z3100000000042LV',null,0,null,null,null,'N',0,86,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000046Z6W',1,0,'交易类型',null,0,1,null,-1,'N',null,20,'djlxmc',0,'N',1,'N','Y','djlxmc->getmlcvalue("bd_billtype","billtypename","pk_billtypecode",djlxbm)',0,null,null,null,'N',0,null,'1001Z3100000000042LV',null,0,null,'12011erm0035',null,'N',0,6,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000019WSF',1,-1,null,null,0,0,null,-1,'N',null,-1,'dwbm_v',0,'N',1,'N','N',null,0,'dwbm_v','erm.jkbxzb.dwbm_v',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,null,null,null,'N',0,89,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000019WSG',1,-1,null,null,0,0,null,-1,'N',null,-1,'dwbm',0,'N',1,'N','N',null,0,'dwbm','erm.jkbxzb.dwbm',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,null,null,null,'N',0,88,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000007WQ3',1,-1,null,'false',0,1,null,-1,'N',null,-1,'isneedimag',0,'N',1,'N','N',null,0,'isneedimag','erm.jkbxzb.isneedimag',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,null,null,null,'N',0,93,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000007WQ4',1,-1,null,null,0,0,null,-1,'N',null,-1,'imag_status',0,'N',1,'N','N',null,0,'imag_status','erm.jkbxzb.imag_status',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,null,null,null,'N',0,92,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z3100000000080P9',1,-1,null,'false',0,1,null,-1,'N',null,-1,'isexpedited',0,'N',1,'N','N',null,0,'isexpedited','erm.jkbxzb.isexpedited',null,'N',0,null,'1001Z3100000000042LV','@@@@',0,null,null,null,'N',0,94,'arap_bxzb','arap_bxzb',0,'2014-08-16 13:32:14','N',null,null,null,1,1,'N',1,null,1)
go

