insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000001OYI',1,4,'自动签字','false',0,1,null,-1,'N',null,20,'autosettle',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',1,32,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FZ',1,0,'交易类型编码',null,0,0,null,-1,'N',null,20,'djlxbm',0,'N',1,'N','Y',null,0,null,null,null,'N',1,null,'djlxZ3ertemplet00001','@@@@',0,null,'UCMD1-000172',null,'N',1,2,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',1,null,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039G2',1,4,'是否银行托收','false',0,1,null,-1,'N',null,20,'isbankrecive',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050013',null,'N',0,7,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039ZF',1,4,'保存时是否自动弹出网银信息','false',0,1,null,-1,'N',null,20,'ispreparenetbank',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050014',null,'N',0,6,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039ZZ',1,4,'是否CA身份认证','false',0,1,null,-1,'N',null,20,'isidvalidated',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050015',null,'N',1,17,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er00000000DFSS',1,4,'是否结算中心收付','false',0,1,null,-1,'N',null,20,'isftspay',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050016',null,'N',0,10,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3erA000000039FA',1,4,'是否借款报销','false',0,1,null,-1,'N',null,20,'isloan',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050017',null,'N',0,12,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3ereptpsn0039FA',1,4,'是否根据录入人自动转换成部门和业务员','false',0,1,null,-1,'N',null,20,'ischangedeptpsn',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050018',null,'N',0,29,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FY',1,0,'公司',null,0,1,null,-1,'N',null,100,'dwbm',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'UC000-0000404',null,'N',0,21,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000Y91N',1,0,'所属单据类型',null,0,0,null,-1,'N',null,50,'pk_billtype',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050023',null,'N',0,30,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000Y91I',1,4,'必须申请','true',0,1,null,-1,'N',null,20,'is_mactrl',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050022',null,'N',1,28,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z310000000001EXG',1,4,'是否合并结算信息','false',0,1,null,-1,'N',null,20,'isautocombinse',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050001',null,'N',0,23,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z310000000001EXH',1,4,'结算信息是否显示','false',0,1,null,-1,'N',null,20,'issettleshow',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050002',null,'N',0,25,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z31000000000E9W2',1,4,'是否加载常用单据','false',0,1,null,-1,'N',null,20,'isloadtemplate',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050003',null,'N',1,27,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z31000000000E9W3',1,4,'是否提示冲借款','false',0,1,null,-1,'N',null,20,'iscontrast',null,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050004',null,'N',1,26,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er000000000N5F',1,4,'是否数字签名','false',0,1,null,-1,'N',null,20,'iscasign',null,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050005',null,'N',0,22,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FA',1,4,'单据封存','false',0,1,null,-1,'N',null,20,'fcbz',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050006',null,'N',0,9,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FB',1,4,'是否签字确认','false',0,1,null,-1,'N',null,20,'isqr',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050007',null,'N',1,8,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FC',1,0,'djlxjc_remark',null,0,1,null,-1,'N',null,100,'djlxjc_remark',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,14,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FE',1,4,'末级标志','false',0,1,null,-1,'N',null,20,'mjbz',0,'N',0,'N','N',null,0,null,null,null,'N',1,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050008',null,'N',0,19,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FG',1,0,'交易类型名称',null,0,1,'djlxmc_remark->djlxmc',-1,'N',null,100,'djlxmc',0,'N',1,'N','Y',null,0,null,null,null,'N',1,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050009',null,'N',1,1,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FH',1,1,'dr','0',0,1,null,-1,'N',null,20,'dr',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,20,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FI',1,4,'是否联动','false',0,1,null,-1,'N',null,20,'iscorresp',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050010',null,'N',0,5,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FM',1,0,'备注',null,0,1,null,-1,'N',null,100,'scomment',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,'UC000-0001376',null,'N',1,11,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FO',1,0,'交易类型简称',null,0,1,'djlxjc_remark->djlxjc',-1,'N',null,100,'djlxjc',0,'N',1,'N','Y',null,0,null,null,null,'N',1,null,'djlxZ3ertemplet00001','@@@@',0,null,'1201100050011',null,'N',1,3,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FP',1,0,'sfbz',null,0,1,null,-1,'N',null,20,'sfbz',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,24,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FR',1,5,'默认币种',null,0,1,null,-1,'N',null,20,'defcurrency',0,'N',1,'N','Y',null,0,null,null,null,'Y',0,null,'djlxZ3ertemplet00001','@@@@',0,'币种档案','1201100050012',null,'N',1,4,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FT',1,0,'djlxmc_remark',null,0,1,null,-1,'N',null,100,'djlxmc_remark',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,15,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FU',1,0,'djlxoid',null,0,1,null,-1,'N',null,20,'djlxoid',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,16,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FV',1,0,'djdl',null,0,1,null,-1,'N',null,20,'djdl',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,13,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001Z3er0000000039FX',1,0,'djmboid',null,0,1,null,-1,'N',null,20,'djmboid',0,'N',0,'N','N',null,0,null,null,null,'N',0,null,'djlxZ3ertemplet00001','@@@@',0,null,null,null,'N',0,18,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000017W93',1,6,'报销类型',null,0,1,null,-1,'N',null,20,'bxtype',0,'N',1,'N','Y',null,0,null,null,null,'N',1,null,'djlxZ3ertemplet00001','@@@@',0,'IX,1201100050026=1,1201100050027=2,1201100050029=4',null,null,'N',1,31,'table','table',0,'2014-05-04 09:48:45','N',null,null,null,1,1,'N',1,null,1)
go

