insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z310000000018A69',null,null,null,'bx','264c','报销转固单','报销转固单','报销转固单','报销转固单',null,0,'0001','N','N','N','N','N','N','N','Y','N','N',2,'Y','N','N','N','N',null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-08 14:49:09',null,4)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z310000000018A5L',null,null,null,'bx','264a','费用调整单','费用调整单','费用调整单','费用调整单',null,0,'0001','N','N','N','N','N','N','N','N','N','N',0,'Y','N','N','N','N',null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-08 14:48:30',null,2)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('1001Z310000262X1IF42',null,null,null,'ac','2621','费用预提单','费用预提单','费用预提单','费用预提单',null,0,'GLOBLE00000000000000','N',null,'N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,null,'N',null,'@@@@',null,null,null,null,'2014-01-22 10:20:38',null,null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('A001Z310000000018K66',null,null,null,'cs','265a','费用调整结转单','费用调整结转单','费用调整结转单','费用调整结转单',null,0,'0001','N','N','N','N','N','N','N','N','N','N',2,'N','N','N','N','N',null,null,null,'N',null,'@@@@',null,null,null,null,'2014-01-09 09:10:42',null,null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31CS0000001CAXA',null,null,null,'at','266X','摊销信息','摊销信息','摊销信息','摊销信息',null,0,'0001','N',null,null,'N','N','N','N','N','N','N',0,'N','N','N','N',null,null,null,null,'Y',null,'@@@@',null,null,null,'3','2014-01-07 09:09:53',null,null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('1001Z310000000001QIG',100,null,null,'ma','2611','费用申请单','费用申请单','费用申请单','费用申请单',null,0,'0001','N',null,'N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,1,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:12:05',null,null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('1001Z310000000001QIH',null,null,null,'cs','2651','费用结转单','费用结转单','费用结转单','费用结转单',null,0,'0001','N',null,'N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54',null,null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CA4R',null,null,null,'jk','2631','差旅费借款单','差旅费借款单','差旅费借款单','差旅费借款单',null,0,'0001','N',null,'N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54',null,null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAWJ',null,null,null,'jk','2632','会议费借款单','会议费借款单','会议费借款单','会议费借款单',null,0,'0001','N',null,null,'N','N','N','N','N','N',null,0,'N','N',null,'N',null,null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54','2',null)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAWX',null,null,null,'bx','2641','差旅费报销单','差旅费报销单','差旅费报销单','差旅费报销单',null,0,'0001','N',null,null,'N','N','N','N','N','N',null,0,'N','N',null,'N',null,null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54','2',1)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAXA',null,null,null,'bx','2642','交通费报销单','交通费报销单','交通费报销单','交通费报销单',null,0,'0001','N',null,null,'N','N','N','N','N','Y',null,0,'N','N',null,'N',null,null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54','2',1)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAXN',null,null,null,'bx','2643','通讯费报销单','通讯费报销单','通讯费报销单','通讯费报销单',null,0,'0001','N',null,null,'N','N','N','N','N','N',null,0,'N','N',null,'N',null,null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54','2',1)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAY0',null,null,null,'bx','2644','礼品费报销单','礼品费报销单','礼品费报销单','礼品费报销单',null,0,'0001','N',null,null,'N','N','N','N','N','Y',null,0,'N','N',null,'N',null,null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54','2',1)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAYD',null,null,null,'bx','2645','招待费报销单','招待费报销单','招待费报销单','招待费报销单',null,0,'0001','N',null,'N','N','N','N','N','N','Y','N',2,'Y','N','N','N','N',null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54',null,1)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAYQ',null,null,null,'bx','2646','会议费报销单','会议费报销单','会议费报销单','会议费报销单',null,0,'0001','N',null,'N','N','N','N','N','N','Y','N',2,'N','N','N','N','N',null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54',null,1)
go

insert into er_djlx(djlxoid,bx_percentage,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,is_mactrl,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,matype,mjbz,parent_billtype,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bxtype) values('0001Z31000000000CAZ3',null,null,null,'bx','2647','还款单','还款单','还款单','还款单',null,0,'0001','N',null,null,'N','N','N','N','Y','N',null,0,'N','N',null,'N',null,null,null,null,'Y',null,'@@@@',null,null,null,null,'2014-01-07 09:09:54','2',1)
go

