insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CA4R',null,null,'jk','2631','差旅费借款单','差旅费借款单','差旅费借款单','差旅费借款单',null,0,'0001','N','N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,null,null,null,null,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAWJ',null,null,'jk','2632','会议费借款单','会议费借款单','会议费借款单','会议费借款单',null,0,'0001','N',null,'N','N','N','N','N','N',null,0,'N','N',null,'N',null,null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28','2',null,null,null,null,null,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAWX',null,null,'bx','2641','差旅费报销单','差旅费报销单','差旅费报销单','差旅费报销单',null,0,'0001','N',null,'N','N','N','N','N','N',null,0,'N','N',null,'N',null,null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28','2',null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAXA',null,null,'bx','2642','交通费报销单','交通费报销单','交通费报销单','交通费报销单',null,0,'0001','N',null,'N','N','N','N','N','Y',null,0,'N','N',null,'N',null,null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28','2',null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAXN',null,null,'bx','2643','通讯费报销单','通讯费报销单','通讯费报销单','通讯费报销单',null,0,'0001','N',null,'N','N','N','N','N','N',null,0,'N','N',null,'N',null,null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28','2',null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAY0',null,null,'bx','2644','礼品费报销单','礼品费报销单','礼品费报销单','礼品费报销单',null,0,'0001','N',null,'N','N','N','N','N','Y',null,0,'N','N',null,'N',null,null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28','2',null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAYD',null,null,'bx','2645','招待费报销单','招待费报销单','招待费报销单','招待费报销单',null,0,'0001','N','N','N','N','N','N','N','Y','N',2,'Y','N','N','N','N',null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAYQ',null,null,'bx','2646','会议费报销单','会议费报销单','会议费报销单','会议费报销单',null,0,'0001','N','N','N','N','N','N','N','Y','N',2,'N','N','N','N','N',null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31000000000CAZ3',null,null,'bx','2647','还款单','还款单','还款单','还款单',null,0,'0001','N',null,'N','N','N','N','Y','N',null,0,'N','N',null,'N',null,null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28','2',null,null,null,null,1,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z310000000018A5L',null,null,'bx','264a','费用调整单','费用调整单','费用调整单','费用调整单',null,0,'0001','N','N','N','N','N','N','N','N','N',0,'Y','N','N','N','N',null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,'N',null,null,2,'Y')
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('0001Z31CS0000001CAXA',null,null,'at','266X','摊销信息','摊销信息','摊销信息','摊销信息',null,0,'0001','N',null,'N','N','N','N','N','N','N',0,'N','N','N','N',null,null,null,'Y','@@@@',null,null,null,'3','2014-09-25 10:43:28',null,null,null,null,null,null,null)
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('1001Z310000000001QIG',null,null,'ma','2611','费用申请单','费用申请单','费用申请单','费用申请单',null,0,'0001','N','N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,100,null,1,null,null,null)
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('1001Z310000000001QIH',null,null,'cs','2651','费用结转单','费用结转单','费用结转单','费用结转单',null,0,'0001','N','N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,'Y','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,null,null,null,null,null)
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('1001Z310000262X1IF42',null,null,'ac','2621','费用预提单','费用预提单','费用预提单','费用预提单',null,0,'GLOBLE00000000000000','N','N','N','N','N','N','N','N','N',1,'N','N','N','N','N',null,null,'N','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,null,null,null,null,null)
go

insert into er_djlx(djlxoid,creatcashflows,defcurrency,djdl,djlxbm,djlxjc,djlxjc_remark,djlxmc,djlxmc_remark,djmboid,dr,dwbm,fcbz,isautocombinse,isbankrecive,iscasign,ischangedeptpsn,iscommit,iscontrast,iscorresp,isidvalidated,isjszxzf,isloadtemplate,isloan,ispreparenetbank,isqr,issettleshow,issxbeforewszz,limitcheck,mjbz,pk_group,pk_org,reimbursement,scomment,sfbz,ts,usesystem,bx_percentage,is_mactrl,matype,parent_billtype,bxtype,manualsettle) values('A001Z310000000018K66',null,null,'cs','265a','费用调整结转单','费用调整结转单','费用调整结转单','费用调整结转单',null,0,'0001','N','N','N','N','N','N','N','N','N',2,'N','N','N','N','N',null,null,'N','@@@@',null,null,null,null,'2014-09-25 10:43:28',null,null,'N',null,null,null,null)
go

