/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.erminit;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ErminitVO extends SuperVO {
	private java.lang.String pk_init;
	private java.lang.String pk_org;
	private nc.vo.pub.lang.UFBoolean close_status;
	private java.lang.String closeman;
	private nc.vo.pub.lang.UFDate closedate;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_group;
	private java.lang.String uncloseman;
	private nc.vo.pub.lang.UFDate unclosedate;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_INIT = "pk_init";
	public static final String PK_ORG = "pk_org";
	public static final String CLOSE_STATUS = "close_status";
	public static final String CLOSEMAN = "closeman";
	public static final String CLOSEDATE = "closedate";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_GROUP = "pk_group";
	public static final String UNCLOSEMAN = "uncloseman";
	public static final String UNCLOSEDATE = "unclosedate";
			
	/**
	 * 属性pk_init的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_init () {
		return pk_init;
	}   
	/**
	 * 属性pk_init的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_init java.lang.String
	 */
	public void setPk_init (java.lang.String newPk_init ) {
	 	this.pk_init = newPk_init;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：财务组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：财务组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性close_status的Getter方法.属性名：关闭状态
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getClose_status () {
		return close_status;
	}   
	/**
	 * 属性close_status的Setter方法.属性名：关闭状态
	 * 创建日期:
	 * @param newClose_status nc.vo.pub.lang.UFBoolean
	 */
	public void setClose_status (nc.vo.pub.lang.UFBoolean newClose_status ) {
	 	this.close_status = newClose_status;
	} 	  
	/**
	 * 属性closeman的Getter方法.属性名：关闭人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCloseman () {
		return closeman;
	}   
	/**
	 * 属性closeman的Setter方法.属性名：关闭人
	 * 创建日期:
	 * @param newCloseman java.lang.String
	 */
	public void setCloseman (java.lang.String newCloseman ) {
	 	this.closeman = newCloseman;
	} 	  
	/**
	 * 属性closedate的Getter方法.属性名：关闭日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getClosedate () {
		return closedate;
	}   
	/**
	 * 属性closedate的Setter方法.属性名：关闭日期
	 * 创建日期:
	 * @param newClosedate nc.vo.pub.lang.UFDate
	 */
	public void setClosedate (nc.vo.pub.lang.UFDate newClosedate ) {
	 	this.closedate = newClosedate;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性uncloseman的Getter方法.属性名：反关闭人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getUncloseman () {
		return uncloseman;
	}   
	/**
	 * 属性uncloseman的Setter方法.属性名：反关闭人
	 * 创建日期:
	 * @param newUncloseman java.lang.String
	 */
	public void setUncloseman (java.lang.String newUncloseman ) {
	 	this.uncloseman = newUncloseman;
	} 	  
	/**
	 * 属性unclosedate的Getter方法.属性名：反关闭日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getUnclosedate () {
		return unclosedate;
	}   
	/**
	 * 属性unclosedate的Setter方法.属性名：反关闭日期
	 * 创建日期:
	 * @param newUnclosedate nc.vo.pub.lang.UFDate
	 */
	public void setUnclosedate (nc.vo.pub.lang.UFDate newUnclosedate ) {
	 	this.unclosedate = newUnclosedate;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_init";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_init";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_init";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public ErminitVO() {
		super();	
	}    
} 


