insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YRL0',1,-1,null,null,0,0,null,-1,'N','pk_org',-1,'pk_org.name',null,'N',1,'N','Y',null,0,'name','uap.org.name',null,'N',0,null,'1001Z3100000000283JG',null,0,null,null,null,'N',1,2,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YRL1',1,-1,null,null,0,0,null,-1,'N','pk_org',-1,'pk_org.code',null,'N',1,'N','Y',null,0,'code','uap.org.code',null,'N',0,null,'1001Z3100000000283JG',null,0,null,null,null,'N',1,1,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000YRL4',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','uap.closeaccbook.pk_org',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',0,11,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3X',1,-1,null,null,0,1,null,-1,'N',null,-1,'endacctime',0,'N',1,'N','Y',null,0,'endacctime','uap.closeaccbook.endacctime',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',1,9,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3R',1,-1,null,'false',0,1,null,-1,'N',null,-1,'isendacc',0,'N',1,'N','N',null,0,'isendacc','uap.closeaccbook.isendacc',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',0,6,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3S',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_accperiodmonth',0,'N',1,'N','Y',null,0,'pk_accperiodmonth','uap.closeaccbook.pk_accperiodmonth',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',1,3,'pk_accperiodmonth','会计期间',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3T',1,-1,'取消结账日期',null,0,1,null,-1,'N',null,-1,'unendacctime',0,'N',1,'N','Y',null,0,'unendacctime','uap.closeaccbook.unendacctime',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,'UPP2011-000926',null,'N',1,12,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000006TDH',1,0,'结账状态',null,0,1,null,-1,'N',null,20,'status',0,'N',1,'N','Y','status->iif(isendacc,getlangres("common" ,"UPP2011-000930"),getlangres("common" ,"UPP2011-000929"));',0,null,null,null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,'UPP2011-000928',null,'N',1,7,'pk_accperiodmonth','会计期间',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3U',1,-1,null,null,0,0,null,-1,'N','pk_accperiodmonth',-1,'pk_accperiodmonth.enddate',0,'N',1,'N','Y',null,0,'enddate','uap.accperiodmonth.enddate',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',1,5,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3V',1,-1,null,null,0,0,null,-1,'N','pk_accperiodmonth',-1,'pk_accperiodmonth.begindate',0,'N',1,'N','Y',null,0,'begindate','uap.accperiodmonth.begindate',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',1,4,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3W',1,-1,'取消结账人',null,0,1,null,-1,'N',null,-1,'unendaccuser',0,'N',1,'N','Y',null,0,'unendaccuser','uap.closeaccbook.unendaccuser',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,'UPP2011-000927',null,'N',1,10,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002AO3Q',1,-1,null,null,0,1,null,-1,'N',null,-1,'endaccuser',0,'N',1,'N','Y',null,0,'endaccuser','uap.closeaccbook.endaccuser',null,'N',0,null,'1001Z3100000000283JG','@@@@',0,null,null,null,'N',1,8,'pk_accperiodmonth','pk_accperiodmonth',0,'2013-10-25 15:28:01','N',null,null,null,1,1,'N',1,null,1)
go

