insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D830',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_iobsclass',0,'N',1,'N','Y',null,0,'pk_iobsclass','erm.mtapp_detail.pk_iobsclass',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,'收支项目,dpc=fi',null,null,'N',0,15,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D831',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem6',0,'N',1,'N','N',null,0,'defitem6','erm.mtapp_bill.defitem6',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,82,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D832',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem21',0,'N',1,'N','N',null,0,'defitem21','erm.mtapp_bill.defitem21',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,67,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D833',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem27',0,'N',1,'N','N',null,0,'defitem27','erm.mtapp_bill.defitem27',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,61,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D834',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem26',0,'N',1,'N','N',null,0,'defitem26','erm.mtapp_bill.defitem26',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,62,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D835',1,-1,null,null,0,0,null,-1,'N',null,-1,'org_exe_amount',0,'N',1,'N','N',null,0,'org_exe_amount','erm.mtapp_bill.org_exe_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,50,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D836',1,-1,null,null,0,0,null,-1,'N',null,-1,'closedate',0,'N',1,'N','N',null,0,'closedate','erm.mtapp_bill.closedate',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,35,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D837',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem4',0,'N',1,'N','N',null,0,'defitem4','erm.mtapp_bill.defitem4',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,84,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D838',1,-1,null,null,0,0,null,-1,'N',null,-1,'global_amount',0,'N',1,'N','N',null,0,'global_amount','erm.mtapp_bill.global_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,31,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D839',1,-1,null,null,0,0,null,-1,'N',null,-1,'close_status',0,'N',1,'N','N',null,0,'close_status','erm.mtapp_bill.close_status',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,25,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83A',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_supplier',0,'N',1,'N','N',null,0,'pk_supplier','erm.mtapp_bill.pk_supplier',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,91,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83B',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem25',0,'N',1,'N','N',null,0,'defitem25','erm.mtapp_bill.defitem25',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,63,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83C',1,-1,'财务组织',null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','erm.mtapp_bill.pk_org',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,'财务组织','120110908010004',null,'N',0,1,'pk_org','所属组织',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83D',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem12',0,'N',1,'N','N',null,0,'defitem12','erm.mtapp_bill.defitem12',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,76,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83E',1,-1,null,null,0,0,null,-1,'N',null,-1,'share_ratio',0,'N',1,'N','N',null,0,'share_ratio','erm.mtapp_detail.share_ratio',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,103,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83F',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem14',0,'N',1,'N','N',null,0,'defitem14','erm.mtapp_bill.defitem14',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,74,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83G',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem19',0,'N',1,'N','N',null,0,'defitem19','erm.mtapp_bill.defitem19',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,69,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83H',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_customer',0,'N',1,'N','Y',null,0,'pk_customer','erm.mtapp_detail.pk_customer',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,'客户档案,dpc=fi',null,null,'N',0,14,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83I',1,-1,null,null,0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','erm.mtapp_bill.billmaker',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,9,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83J',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem1',0,'N',1,'N','N',null,0,'defitem1','erm.mtapp_bill.defitem1',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,87,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83K',1,-1,null,null,0,0,null,-1,'N',null,-1,'approvetime',0,'N',1,'N','N',null,0,'approvetime','erm.mtapp_bill.approvetime',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,37,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83L',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem15',0,'N',1,'N','N',null,0,'defitem15','erm.mtapp_bill.defitem15',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,73,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83M',1,-1,null,null,0,0,null,-1,'N',null,-1,'autoclosedate',0,'N',1,'N','N',null,0,'autoclosedate','erm.mtapp_bill.autoclosedate',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,57,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83N',1,-1,null,null,0,0,null,-1,'N',null,-1,'org_currinfo',0,'N',1,'N','N',null,0,'org_currinfo','erm.mtapp_bill.org_currinfo',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,26,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83O',1,-1,null,null,0,0,null,-1,'N',null,-1,'group_pre_amount',0,'N',1,'N','N',null,0,'group_pre_amount','erm.mtapp_bill.group_pre_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,55,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83P',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem16',0,'N',1,'N','N',null,0,'defitem16','erm.mtapp_bill.defitem16',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,72,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000NRPP',1,0,'交易类型',null,0,1,null,-1,'N',null,20,'tradetype2',0,'N',1,'N','Y','getMLCValue("bd_billtype","billtypename","pk_billtypecode",getcolnmv(er_mtapp_bill , pk_tradetype, pk_mtapp_bill, pk_mtapp_bill));',0,null,null,null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,'UCMD1-000053',null,'N',0,3,'pk_org','所属组织',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000001BB5B',1,-1,null,null,0,0,null,-1,'N',null,-1,'apply_org',0,'N',1,'N','Y',null,0,'apply_org','erm.mtapp_bill.apply_org',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,7,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83R',1,-1,null,null,0,0,null,-1,'N',null,-1,'billstatus',0,'N',1,'N','N',null,0,'billstatus','erm.mtapp_bill.billstatus',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,22,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83S',1,-1,null,null,0,0,null,-1,'N',null,-1,'assume_dept',0,'N',1,'N','Y',null,0,'assume_dept','erm.mtapp_detail.assume_dept',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,11,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83T',1,-1,null,null,0,0,null,-1,'N',null,-1,'center_dept',0,'N',1,'N','N',null,0,'center_dept','erm.mtapp_bill.center_dept',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,33,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83U',1,-1,null,null,0,0,null,-1,'N',null,-1,'attach_amount',0,'N',1,'N','N',null,0,'attach_amount','erm.mtapp_bill.attach_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,32,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83V',1,-1,null,null,0,0,null,-1,'N',null,-1,'org_rest_amount',0,'N',1,'N','N',null,0,'org_rest_amount','erm.mtapp_bill.org_rest_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,47,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83W',1,-1,null,null,0,0,null,-1,'N',null,-1,'group_exe_amount',0,'N',1,'N','N',null,0,'group_exe_amount','erm.mtapp_bill.group_exe_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,51,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83Y',1,-1,null,null,0,0,null,-1,'N',null,-1,'global_currinfo',0,'N',1,'N','N',null,0,'global_currinfo','erm.mtapp_bill.global_currinfo',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,28,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_billtype',0,'N',1,'N','N',null,0,'pk_billtype','erm.mtapp_bill.pk_billtype',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,21,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D840',1,-1,null,null,0,0,null,-1,'N',null,-1,'warningmsg',0,'N',1,'N','N',null,0,'warningmsg','erm.mtapp_bill.warningmsg',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,46,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D841',1,-1,null,null,0,0,null,-1,'N',null,-1,'apply_dept',0,'N',1,'N','Y',null,0,'apply_dept','erm.mtapp_bill.apply_dept',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,8,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D842',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem13',0,'N',1,'N','N',null,0,'defitem13','erm.mtapp_bill.defitem13',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,75,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D843',1,-1,null,'false',0,0,null,-1,'N',null,-1,'iscostshare',0,'N',1,'N','N',null,0,'iscostshare','erm.mtapp_bill.iscostshare',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,94,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D844',1,-1,null,'true',0,0,null,-1,'N',null,-1,'is_adjust',0,'N',1,'N','N',null,0,'is_adjust','erm.mtapp_bill.is_adjust',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,92,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D845',1,-1,null,'ma',0,0,null,-1,'N',null,-1,'djdl',0,'N',1,'N','N',null,0,'djdl','erm.mtapp_bill.djdl',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,88,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D846',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_currtype',0,'N',1,'N','Y',null,0,'pk_currtype','erm.mtapp_detail.pk_currtype',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,'币种档案',null,null,'N',0,17,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D847',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_wbs',0,'N',1,'N','N',null,0,'pk_wbs','erm.mtapp_detail.pk_wbs',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,101,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D848',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',null,0,'creationtime','erm.mtapp_bill.creationtime',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,39,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'reason',0,'N',1,'N','Y',null,0,'reason','erm.mtapp_bill.reason',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,6,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D849',1,-1,null,null,0,0,null,-1,'N',null,-1,'global_pre_amount',0,'N',1,'N','N',null,0,'global_pre_amount','erm.mtapp_bill.global_pre_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,56,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84A',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem30',0,'N',1,'N','N',null,0,'defitem30','erm.mtapp_bill.defitem30',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,58,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84B',1,-1,null,null,0,0,null,-1,'N',null,-1,'printdate',0,'N',1,'N','N',null,0,'printdate','erm.mtapp_bill.printdate',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,43,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84C',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',null,0,'creator','erm.mtapp_bill.creator',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,38,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84D',1,-1,null,null,0,0,null,-1,'N',null,-1,'billno',0,'N',1,'N','Y',null,0,'billno','erm.mtapp_bill.billno',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,5,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84E',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem28',0,'N',1,'N','N',null,0,'defitem28','erm.mtapp_bill.defitem28',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,60,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84F',1,-1,null,null,0,0,null,-1,'N',null,-1,'group_amount',0,'N',1,'N','N',null,0,'group_amount','erm.mtapp_bill.group_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,30,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84G',1,-1,null,null,0,0,null,-1,'N',null,-1,'apprstatus',0,'N',1,'N','N',null,0,'apprstatus','erm.mtapp_bill.apprstatus',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,23,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84H',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem11',0,'N',1,'N','N',null,0,'defitem11','erm.mtapp_bill.defitem11',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,77,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84I',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem23',0,'N',1,'N','N',null,0,'defitem23','erm.mtapp_bill.defitem23',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,65,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84J',1,-1,null,null,0,0,null,-1,'N',null,-1,'effectstatus',0,'N',1,'N','N',null,0,'effectstatus','erm.mtapp_bill.effectstatus',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,24,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84K',0,-1,null,null,0,0,null,-1,'N',null,-1,'pk_tradetype',0,'N',0,'N','N',null,0,'pk_tradetype','erm.mtapp_bill.pk_tradetype',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,'交易类型',null,null,'N',0,2,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84L',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem2',0,'N',1,'N','N',null,0,'defitem2','erm.mtapp_bill.defitem2',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,86,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84M',1,-1,null,null,0,0,null,-1,'N',null,-1,'auditman',0,'N',1,'N','N',null,0,'auditman','erm.mtapp_bill.auditman',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,89,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84N',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem10',0,'N',1,'N','N',null,0,'defitem10','erm.mtapp_bill.defitem10',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,78,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84O',1,-1,null,null,0,0,null,-1,'N',null,-1,'orig_amount',0,'N',1,'N','Y',null,0,'orig_amount','erm.mtapp_detail.orig_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,18,'pk_org','pk_org',1,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84P',1,-1,null,null,0,0,null,-1,'N',null,-1,'usable_amout',0,'N',1,'N','Y',null,0,'usable_amout','erm.mtapp_detail.usable_amout',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,107,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem5',0,'N',1,'N','N',null,0,'defitem5','erm.mtapp_bill.defitem5',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,83,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84R',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',null,0,'approver','erm.mtapp_bill.approver',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,36,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D83X',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem20',0,'N',1,'N','N',null,0,'defitem20','erm.mtapp_bill.defitem20',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,68,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84S',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem17',0,'N',1,'N','N',null,0,'defitem17','erm.mtapp_bill.defitem17',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,71,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84T',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_resacostcenter',0,'N',1,'N','Y',null,0,'pk_resacostcenter','erm.mtapp_detail.pk_resacostcenter',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,13,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84U',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_brand',0,'N',1,'N','N',null,0,'pk_brand','erm.mtapp_detail.pk_brand',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,98,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84V',1,-1,null,null,0,0,null,-1,'N',null,-1,'group_rest_amount',0,'N',1,'N','N',null,0,'group_rest_amount','erm.mtapp_bill.group_rest_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,48,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84W',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',null,0,'modifiedtime','erm.mtapp_bill.modifiedtime',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,41,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84X',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem9',0,'N',1,'N','N',null,0,'defitem9','erm.mtapp_bill.defitem9',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,79,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84Y',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',null,0,'modifier','erm.mtapp_bill.modifier',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,40,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D84Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'group_currinfo',0,'N',1,'N','N',null,0,'group_currinfo','erm.mtapp_bill.group_currinfo',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,27,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D850',1,-1,null,'false',0,0,null,-1,'N',null,-1,'hasntbcheck',0,'N',1,'N','N',null,0,'hasntbcheck','erm.mtapp_bill.hasntbcheck',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,45,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D851',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_checkele',0,'N',1,'N','Y',null,0,'pk_checkele','erm.mtapp_detail.pk_checkele',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,16,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D852',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_proline',0,'N',1,'N','N',null,0,'pk_proline','erm.mtapp_detail.pk_proline',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,97,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D853',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_pcorg',0,'N',1,'N','Y',null,0,'pk_pcorg','erm.mtapp_detail.pk_pcorg',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,12,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D854',1,-1,'单据日期',null,0,0,null,-1,'N',null,-1,'billdate',0,'N',1,'N','Y',null,0,'billdate','erm.mtapp_bill.billdate',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,'UC000-0000799',null,'N',0,4,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D855',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','erm.mtapp_bill.pk_org_v',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,90,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D857',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_salesman',0,'N',1,'N','N',null,0,'pk_salesman','erm.mtapp_detail.pk_salesman',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,99,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D858',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_project',0,'N',1,'N','N',null,0,'pk_project','erm.mtapp_detail.pk_project',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,100,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D859',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','erm.mtapp_bill.pk_group',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,44,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85A',1,-1,null,null,0,0,null,-1,'N',null,-1,'assume_org',0,'N',1,'N','Y',null,0,'assume_org','erm.mtapp_detail.assume_org',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,'业务单元,code=N,dpc=fi',null,null,'N',0,10,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85B',1,-1,null,null,0,0,null,-1,'N',null,-1,'customer_ratio',0,'N',1,'N','N',null,0,'customer_ratio','erm.mtapp_detail.customer_ratio',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,105,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85C',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_mtapp_detail',0,'N',1,'N','N',null,0,'pk_mtapp_detail','erm.mtapp_detail.pk_mtapp_detail',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,96,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85D',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem3',0,'N',1,'N','N',null,0,'defitem3','erm.mtapp_bill.defitem3',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,85,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85E',1,-1,null,null,0,0,null,-1,'N',null,-1,'exe_amount',0,'N',1,'N','Y',null,0,'exe_amount','erm.mtapp_detail.exe_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,19,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85F',1,-1,null,null,0,0,null,-1,'N',null,-1,'max_amount',0,'N',1,'N','N',null,0,'max_amount','erm.mtapp_bill.max_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,93,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85G',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem22',0,'N',1,'N','N',null,0,'defitem22','erm.mtapp_bill.defitem22',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,66,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D856',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem8',0,'N',1,'N','N',null,0,'defitem8','erm.mtapp_bill.defitem8',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,80,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85H',1,-1,null,null,0,0,null,-1,'N',null,-1,'closeman',0,'N',1,'N','N',null,0,'closeman','erm.mtapp_bill.closeman',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,34,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85I',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem18',0,'N',1,'N','N',null,0,'defitem18','erm.mtapp_bill.defitem18',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,70,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85J',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','erm.mtapp_bill.ts',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,95,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85K',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem29',0,'N',1,'N','N',null,0,'defitem29','erm.mtapp_bill.defitem29',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,59,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85L',1,-1,null,null,0,0,null,-1,'N',null,-1,'global_exe_amount',0,'N',1,'N','N',null,0,'global_exe_amount','erm.mtapp_bill.global_exe_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,52,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85M',1,-1,null,null,0,0,null,-1,'N',null,-1,'org_amount',0,'N',1,'N','N',null,0,'org_amount','erm.mtapp_bill.org_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,29,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85N',1,-1,null,null,0,0,null,-1,'N',null,-1,'global_rest_amount',0,'N',1,'N','N',null,0,'global_rest_amount','erm.mtapp_bill.global_rest_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,49,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85O',1,-1,null,null,0,0,null,-1,'N',null,-1,'rowno',0,'N',1,'N','N',null,0,'rowno','erm.mtapp_detail.rowno',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,102,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85P',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem24',0,'N',1,'N','N',null,0,'defitem24','erm.mtapp_bill.defitem24',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,64,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'defitem7',0,'N',1,'N','N',null,0,'defitem7','erm.mtapp_bill.defitem7',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,81,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85S',1,-1,null,null,0,0,null,-1,'N',null,-1,'org_pre_amount',0,'N',1,'N','N',null,0,'org_pre_amount','erm.mtapp_bill.org_pre_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,54,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85U',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_mtapp_bill',0,'N',1,'N','N',null,0,'pk_mtapp_bill','erm.mtapp_bill.pk_mtapp_bill',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,20,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85V',1,-1,null,null,0,0,null,-1,'N',null,-1,'rest_amount',0,'N',1,'N','Y',null,0,'rest_amount','erm.mtapp_detail.rest_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,106,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85W',1,-1,null,null,0,0,null,-1,'N',null,-1,'pre_amount',0,'N',1,'N','N',null,0,'pre_amount','erm.mtapp_bill.pre_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,53,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85T',1,-1,null,null,0,0,null,-1,'N',null,-1,'printer',0,'N',1,'N','N',null,0,'printer','erm.mtapp_bill.printer',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,42,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000D85R',1,-1,null,null,0,0,null,-1,'N',null,-1,'apply_amount',0,'N',1,'N','N',null,0,'apply_amount','erm.mtapp_detail.apply_amount',null,'N',0,null,'1001Z31000000000A58W','@@@@',0,null,null,null,'N',0,104,'pk_org','pk_org',0,'2014-01-14 10:25:18','N',null,null,null,1,1,'N',1,null,1)
go

