insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8US',1,-1,null,null,0,1,null,-1,'N',null,-1,'djrq',0,'N',1,'N','Y',0,null,0,'djrq','erm.bxzb.djrq',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',1,1,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UT',1,-1,null,null,0,1,null,-1,'N',null,-1,'zy',0,'N',1,'N','Y',0,null,0,'zy','erm.bxzb.zy',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',1,2,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UU',1,-1,null,null,0,1,null,-1,'N',null,-1,'bzbm',0,'N',1,'N','N',0,null,0,'bzbm','erm.bxzb.bzbm',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,3,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UV',1,-1,'费用项目',null,0,1,null,-1,'N',null,-1,'szxmid',0,'N',1,'N','Y',0,null,0,'szxmid','erm.bxzb.szxmid',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',1,4,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UW',1,-1,'报销单号',null,0,1,null,-1,'N',null,-1,'djbh',0,'N',1,'N','Y',0,null,0,'djbh','erm.bxzb.djbh',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,5,'djbh','单据编号',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UX',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx1',0,'N',1,'N','N',0,null,0,'zyx1','erm.bxzb.zyx1',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,6,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UY',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx2',0,'N',1,'N','N',0,null,0,'zyx2','erm.bxzb.zyx2',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,7,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8UZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx3',0,'N',1,'N','N',0,null,0,'zyx3','erm.bxzb.zyx3',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,8,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V0',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx4',0,'N',1,'N','N',0,null,0,'zyx4','erm.bxzb.zyx4',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,9,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V1',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx5',0,'N',1,'N','N',0,null,0,'zyx5','erm.bxzb.zyx5',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,10,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V2',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx6',0,'N',1,'N','N',0,null,0,'zyx6','erm.bxzb.zyx6',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,11,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V3',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx7',0,'N',1,'N','N',0,null,0,'zyx7','erm.bxzb.zyx7',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,12,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V4',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx8',0,'N',1,'N','N',0,null,0,'zyx8','erm.bxzb.zyx8',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,13,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V5',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx9',0,'N',1,'N','N',0,null,0,'zyx9','erm.bxzb.zyx9',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,14,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V6',1,-1,null,null,0,1,null,-1,'N',null,-1,'zyx10',0,'N',1,'N','N',0,null,0,'zyx10','erm.bxzb.zyx10',null,'N',0,null,'1001Z31000000002V8UR','@@@@',0,null,null,null,'N',0,15,'djbh','djbh',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V7',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_reimtype',0,'N',1,'N','N',0,null,0,'pk_reimtype','erm.er_busitem.pk_reimtype',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,1,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V8',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem50',0,'N',1,'N','N',0,null,0,'defitem50','erm.er_busitem.defitem50',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,2,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8V9',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem49',0,'N',1,'N','N',0,null,0,'defitem49','erm.er_busitem.defitem49',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,3,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VA',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem48',0,'N',1,'N','N',0,null,0,'defitem48','erm.er_busitem.defitem48',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,4,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VB',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem47',0,'N',1,'N','N',0,null,0,'defitem47','erm.er_busitem.defitem47',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,5,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VC',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem46',0,'N',1,'N','N',0,null,0,'defitem46','erm.er_busitem.defitem46',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,6,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VD',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem45',0,'N',1,'N','N',0,null,0,'defitem45','erm.er_busitem.defitem45',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,7,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VE',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem44',0,'N',1,'N','N',0,null,0,'defitem44','erm.er_busitem.defitem44',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,8,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VF',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem43',0,'N',1,'N','N',0,null,0,'defitem43','erm.er_busitem.defitem43',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,9,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VG',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem42',0,'N',1,'N','N',0,null,0,'defitem42','erm.er_busitem.defitem42',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,10,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VH',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem41',0,'N',1,'N','N',0,null,0,'defitem41','erm.er_busitem.defitem41',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,11,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VI',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem40',0,'N',1,'N','N',0,null,0,'defitem40','erm.er_busitem.defitem40',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,12,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem39',0,'N',1,'N','N',0,null,0,'defitem39','erm.er_busitem.defitem39',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,13,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VK',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem38',0,'N',1,'N','N',0,null,0,'defitem38','erm.er_busitem.defitem38',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,14,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VL',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem37',0,'N',1,'N','N',0,null,0,'defitem37','erm.er_busitem.defitem37',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,15,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VM',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem36',0,'N',1,'N','N',0,null,0,'defitem36','erm.er_busitem.defitem36',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,16,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VN',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem35',0,'N',1,'N','N',0,null,0,'defitem35','erm.er_busitem.defitem35',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,17,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VO',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem34',0,'N',1,'N','N',0,null,0,'defitem34','erm.er_busitem.defitem34',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,18,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VP',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem33',0,'N',1,'N','N',0,null,0,'defitem33','erm.er_busitem.defitem33',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,19,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem32',0,'N',1,'N','N',0,null,0,'defitem32','erm.er_busitem.defitem32',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,20,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VR',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem31',0,'N',1,'N','N',0,null,0,'defitem31','erm.er_busitem.defitem31',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,21,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VS',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem30',0,'N',1,'N','N',0,null,0,'defitem30','erm.er_busitem.defitem30',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,22,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VT',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem29',0,'N',1,'N','N',0,null,0,'defitem29','erm.er_busitem.defitem29',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,23,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VU',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem28',0,'N',1,'N','N',0,null,0,'defitem28','erm.er_busitem.defitem28',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,24,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VV',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem27',0,'N',1,'N','N',0,null,0,'defitem27','erm.er_busitem.defitem27',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,25,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VW',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem26',0,'N',1,'N','N',0,null,0,'defitem26','erm.er_busitem.defitem26',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,26,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VX',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem25',0,'N',1,'N','N',0,null,0,'defitem25','erm.er_busitem.defitem25',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,27,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VY',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem24',0,'N',1,'N','N',0,null,0,'defitem24','erm.er_busitem.defitem24',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,28,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8VZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem23',0,'N',1,'N','N',0,null,0,'defitem23','erm.er_busitem.defitem23',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,29,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W0',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem22',0,'N',1,'N','N',0,null,0,'defitem22','erm.er_busitem.defitem22',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,30,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W1',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem21',0,'N',1,'N','N',0,null,0,'defitem21','erm.er_busitem.defitem21',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,31,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W2',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem20',0,'N',1,'N','N',0,null,0,'defitem20','erm.er_busitem.defitem20',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,32,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W3',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem19',0,'N',1,'N','N',0,null,0,'defitem19','erm.er_busitem.defitem19',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,33,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W4',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem18',0,'N',1,'N','N',0,null,0,'defitem18','erm.er_busitem.defitem18',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,34,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W5',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem17',0,'N',1,'N','N',0,null,0,'defitem17','erm.er_busitem.defitem17',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,35,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W6',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem16',0,'N',1,'N','N',0,null,0,'defitem16','erm.er_busitem.defitem16',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,36,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W7',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem15',0,'N',1,'N','N',0,null,0,'defitem15','erm.er_busitem.defitem15',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,37,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W8',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem14',0,'N',1,'N','N',0,null,0,'defitem14','erm.er_busitem.defitem14',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,38,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8W9',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem13',0,'N',1,'N','N',0,null,0,'defitem13','erm.er_busitem.defitem13',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,39,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WA',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem12',0,'N',1,'N','N',0,null,0,'defitem12','erm.er_busitem.defitem12',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,40,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WB',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem11',0,'N',1,'N','N',0,null,0,'defitem11','erm.er_busitem.defitem11',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,41,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WC',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem10',0,'N',1,'N','N',0,null,0,'defitem10','erm.er_busitem.defitem10',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,42,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WD',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem9',0,'N',1,'N','N',0,null,0,'defitem9','erm.er_busitem.defitem9',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,43,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WE',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem8',0,'N',1,'N','N',0,null,0,'defitem8','erm.er_busitem.defitem8',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,44,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WF',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem7',0,'N',1,'N','N',0,null,0,'defitem7','erm.er_busitem.defitem7',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,45,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WG',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem6',0,'N',1,'N','N',0,null,0,'defitem6','erm.er_busitem.defitem6',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,46,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WH',1,-1,null,null,0,1,null,-1,'N',null,-1,'defitem5',0,'N',1,'N','N',0,null,0,'defitem5','erm.er_busitem.defitem5',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,47,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WI',1,-1,'招待时间',null,0,1,null,-1,'N',null,-1,'defitem1',0,'N',1,'N','Y',0,null,0,'defitem1','erm.er_busitem.defitem1',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,'BS000010000100001033',null,null,'N',1,48,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WJ',1,-1,'事由',null,0,1,null,-1,'N',null,-1,'defitem2',0,'N',1,'N','Y',0,null,0,'defitem2','erm.er_busitem.defitem2',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,'BS000010000100001001',null,null,'N',1,49,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WK',1,-1,'客商',null,0,1,null,-1,'N',null,-1,'defitem3',0,'N',1,'N','Y',0,null,0,'defitem3','erm.er_busitem.defitem3',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,'BS000010000100001001',null,null,'N',1,50,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WL',1,-1,'人数',null,0,1,null,-1,'N',null,-1,'defitem4',0,'N',1,'N','Y',0,null,0,'defitem4','erm.er_busitem.defitem4',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,'BS000010000100001004',null,null,'N',1,51,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WM',1,-1,'报销金额',null,0,1,null,-1,'N',null,-1,'amount',0,'N',1,'N','Y',0,null,0,'amount','erm.er_busitem.amount',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',1,52,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WN',1,-1,null,null,0,1,null,-1,'N',null,-1,'szxmid',0,'N',1,'N','N',0,null,0,'szxmid','erm.er_busitem.szxmid',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,53,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WO',1,-1,null,null,0,1,null,-1,'N',null,-1,'jobid',0,'N',1,'N','N',0,null,0,'jobid','erm.er_busitem.jobid',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,54,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WP',1,-1,null,null,0,1,null,-1,'N',null,-1,'hbbm',0,'N',1,'N','N',0,null,0,'hbbm','erm.er_busitem.hbbm',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,55,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'customer',0,'N',1,'N','N',0,null,0,'customer','erm.er_busitem.customer',null,'N',0,null,'1001Z31000000002V8UR','@@@@',1,null,null,null,'N',0,56,'arap_bxbusitem','招待费',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WR',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',0,null,0,'creator','erm.bxzb.creator',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,'用户,dpc=fi',null,null,'N',0,1,'audit',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WS',1,5,'审批人',null,0,0,null,-1,'N',null,20,'approver',0,'N',1,'N','N',0,null,0,'approver','erm.bxzb.approver',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,'用户,dpc=fi',null,null,'N',0,1,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WT',1,-1,null,null,0,0,null,-1,'N',null,-1,'shrq_show',0,'N',1,'N','N',0,null,0,'shrq_show','erm.bxzb.shrq_show',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,2,'tail','tail',0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WU',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',0,null,0,'creationtime','erm.bxzb.creationtime',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,2,'audit',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WV',1,-1,'审批日期',null,0,0,null,-1,'N',null,-1,'shrq',0,'N',1,'N','N',0,null,0,'shrq','erm.bxzb.shrq',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,3,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WW',1,-1,'最后修改人',null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',0,null,0,'modifier','erm.bxzb.modifier',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,3,'audit',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WX',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsr',0,'N',1,'N','N',0,null,0,'jsr','erm.bxzb.jsr',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,4,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WY',1,-1,'最后修改时间',null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',0,null,0,'modifiedtime','erm.bxzb.modifiedtime',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,4,'audit',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8WZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'jsrq',0,'N',1,'N','N',0,null,0,'jsrq','erm.bxzb.jsrq',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,5,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8X0',1,-1,null,null,0,0,null,-1,'N',null,-1,'payman',0,'N',1,'N','N',0,null,0,'payman','erm.bxzb.payman',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,6,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8X1',1,-1,null,null,0,0,null,-1,'N',null,-1,'paydate',0,'N',1,'N','N',0,null,0,'paydate','erm.bxzb.paydate',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,7,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8X2',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintuser',0,'N',1,'N','N',0,null,0,'officialprintuser','erm.bxzb.officialprintuser',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,8,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000002V8X3',1,-1,null,null,0,0,null,-1,'N',null,-1,'officialprintdate',0,'N',1,'N','N',0,null,0,'officialprintdate','erm.bxzb.officialprintdate',null,'N',0,null,'1001Z31000000002V8UR','@@@@',2,null,null,null,'N',0,9,'tail',null,0,'2014-09-04 16:46:13','N',null,null,null,1,1,'N',1,null,1)
go

