/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.erm.matterapp;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MtAppDetailVO extends SuperVO {
	private java.lang.String pk_mtapp_bill;
	private java.lang.String pk_mtapp_detail;
	private java.lang.String pk_pcorg;
	private java.lang.String pk_resacostcenter;
	private java.lang.String pk_checkele;
	private java.lang.String pk_salesman;
	private java.lang.String pk_iobsclass;
	private java.lang.String pk_project;
	private java.lang.String pk_wbs;
	private java.lang.String pk_customer;
	private java.lang.String pk_supplier;
	private java.lang.String reason;
	private java.lang.String pk_currtype;
	private nc.vo.pub.lang.UFDouble orig_amount;
	private java.lang.String billno;
	private java.lang.String pk_billtype;
	private java.lang.String pk_tradetype;
	private nc.vo.pub.lang.UFDate billdate;
	private java.lang.Integer close_status;
	private java.lang.Integer billstatus;
	private java.lang.Integer effectstatus;
	private java.lang.String closeman;
	private nc.vo.pub.lang.UFDate closedate;
	private nc.vo.pub.lang.UFDouble org_currinfo;
	private nc.vo.pub.lang.UFDouble group_currinfo;
	private nc.vo.pub.lang.UFDouble global_currinfo;
	private nc.vo.pub.lang.UFDouble org_amount;
	private nc.vo.pub.lang.UFDouble group_amount;
	private nc.vo.pub.lang.UFDouble global_amount;
	private java.lang.String pk_org;
	private java.lang.String pk_group;
	private nc.vo.pub.lang.UFDouble rest_amount;
	private nc.vo.pub.lang.UFDouble org_rest_amount;
	private nc.vo.pub.lang.UFDouble group_rest_amount;
	private nc.vo.pub.lang.UFDouble global_rest_amount;
	private nc.vo.pub.lang.UFDouble exe_amount;
	private nc.vo.pub.lang.UFDouble org_exe_amount;
	private nc.vo.pub.lang.UFDouble group_exe_amount;
	private nc.vo.pub.lang.UFDouble global_exe_amount;
	private java.lang.Integer rowno;
	private nc.vo.pub.lang.UFDouble pre_amount;
	private nc.vo.pub.lang.UFDouble org_pre_amount;
	private nc.vo.pub.lang.UFDouble group_pre_amount;
	private nc.vo.pub.lang.UFDouble global_pre_amount;
	private java.lang.String billmaker;
	private java.lang.String apply_dept;
	private nc.vo.pub.lang.UFDate approvetime;
	private java.lang.String defitem30;
	private java.lang.String defitem29;
	private java.lang.String defitem28;
	private java.lang.String defitem27;
	private java.lang.String defitem26;
	private java.lang.String defitem25;
	private java.lang.String defitem24;
	private java.lang.String defitem23;
	private java.lang.String defitem22;
	private java.lang.String defitem21;
	private java.lang.String defitem20;
	private java.lang.String defitem19;
	private java.lang.String defitem18;
	private java.lang.String defitem17;
	private java.lang.String defitem16;
	private java.lang.String defitem15;
	private java.lang.String defitem14;
	private java.lang.String defitem13;
	private java.lang.String defitem12;
	private java.lang.String defitem11;
	private java.lang.String defitem10;
	private java.lang.String defitem9;
	private java.lang.String defitem8;
	private java.lang.String defitem7;
	private java.lang.String defitem6;
	private java.lang.String defitem5;
	private java.lang.String defitem4;
	private java.lang.String defitem3;
	private java.lang.String defitem2;
	private java.lang.String defitem1;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private UFDouble usable_amout;

	public static final String PK_MTAPP_BILL = "pk_mtapp_bill";
	public static final String PK_MTAPP_DETAIL = "pk_mtapp_detail";
	public static final String PK_PCORG = "pk_pcorg";
	public static final String PK_RESACOSTCENTER = "pk_resacostcenter";
	public static final String PK_SALESMAN = "pk_salesman";
	public static final String PK_IOBSCLASS = "pk_iobsclass";
	public static final String PK_PROJECT = "pk_project";
	public static final String PK_WBS = "pk_wbs";
	public static final String PK_CUSTOMER = "pk_customer";
	public static final String PK_SUPPLIER = "pk_supplier";
	public static final String REASON = "reason";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String ORIG_AMOUNT = "orig_amount";
	public static final String BILLNO = "billno";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String PK_TRADETYPE = "pk_tradetype";
	public static final String BILLDATE = "billdate";
	public static final String CLOSE_STATUS = "close_status";
	public static final String BILLSTATUS = "billstatus";
	public static final String EFFECTSTATUS = "effectstatus";
	public static final String CLOSEMAN = "closeman";
	public static final String CLOSEDATE = "closedate";
	public static final String ORG_CURRINFO = "org_currinfo";
	public static final String GROUP_CURRINFO = "group_currinfo";
	public static final String GLOBAL_CURRINFO = "global_currinfo";
	public static final String ORG_AMOUNT = "org_amount";
	public static final String GROUP_AMOUNT = "group_amount";
	public static final String GLOBAL_AMOUNT = "global_amount";
	public static final String PK_ORG = "pk_org";
	public static final String PK_GROUP = "pk_group";
	public static final String REST_AMOUNT = "rest_amount";
	public static final String ORG_REST_AMOUNT = "org_rest_amount";
	public static final String GROUP_REST_AMOUNT = "group_rest_amount";
	public static final String GLOBAL_REST_AMOUNT = "global_rest_amount";
	public static final String EXE_AMOUNT = "exe_amount";
	public static final String ORG_EXE_AMOUNT = "org_exe_amount";
	public static final String GROUP_EXE_AMOUNT = "group_exe_amount";
	public static final String GLOBAL_EXE_AMOUNT = "global_exe_amount";
	public static final String ROWNO = "rowno";
	public static final String PRE_AMOUNT = "pre_amount";
	public static final String ORG_PRE_AMOUNT = "org_pre_amount";
	public static final String GROUP_PRE_AMOUNT = "group_pre_amount";
	public static final String GLOBAL_PRE_AMOUNT = "global_pre_amount";
	public static final String BILLMAKER = "billmaker";
	public static final String APPLY_DEPT = "apply_dept";
	public static final String APPROVETIME = "approvetime";
	public static final String DEFITEM30 = "defitem30";
	public static final String DEFITEM29 = "defitem29";
	public static final String DEFITEM28 = "defitem28";
	public static final String DEFITEM27 = "defitem27";
	public static final String DEFITEM26 = "defitem26";
	public static final String DEFITEM25 = "defitem25";
	public static final String DEFITEM24 = "defitem24";
	public static final String DEFITEM23 = "defitem23";
	public static final String DEFITEM22 = "defitem22";
	public static final String DEFITEM21 = "defitem21";
	public static final String DEFITEM20 = "defitem20";
	public static final String DEFITEM19 = "defitem19";
	public static final String DEFITEM18 = "defitem18";
	public static final String DEFITEM17 = "defitem17";
	public static final String DEFITEM16 = "defitem16";
	public static final String DEFITEM15 = "defitem15";
	public static final String DEFITEM14 = "defitem14";
	public static final String DEFITEM13 = "defitem13";
	public static final String DEFITEM12 = "defitem12";
	public static final String DEFITEM11 = "defitem11";
	public static final String DEFITEM10 = "defitem10";
	public static final String DEFITEM9 = "defitem9";
	public static final String DEFITEM8 = "defitem8";
	public static final String DEFITEM7 = "defitem7";
	public static final String DEFITEM6 = "defitem6";
	public static final String DEFITEM5 = "defitem5";
	public static final String DEFITEM4 = "defitem4";
	public static final String DEFITEM3 = "defitem3";
	public static final String DEFITEM2 = "defitem2";
	public static final String DEFITEM1 = "defitem1";
	public static final String PK_CHECKELE = "pk_checkele";
	public static final String USABLE_AMOUT = "usable_amout";
	
	/**
	 * 属性pk_mtapp_bill的Getter方法.属性名：parentPK 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_mtapp_bill() {
		return pk_mtapp_bill;
	}

	/**
	 * 属性pk_mtapp_bill的Setter方法.属性名：parentPK 创建日期:
	 * 
	 * @param newPk_mtapp_bill
	 *            java.lang.String
	 */
	public void setPk_mtapp_bill(java.lang.String newPk_mtapp_bill) {
		this.pk_mtapp_bill = newPk_mtapp_bill;
	}

	/**
	 * 属性pk_mtapp_detail的Getter方法.属性名：主键 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_mtapp_detail() {
		return pk_mtapp_detail;
	}

	/**
	 * 属性pk_mtapp_detail的Setter方法.属性名：主键 创建日期:
	 * 
	 * @param newPk_mtapp_detail
	 *            java.lang.String
	 */
	public void setPk_mtapp_detail(java.lang.String newPk_mtapp_detail) {
		this.pk_mtapp_detail = newPk_mtapp_detail;
	}

	/**
	 * 属性pk_pcorg的Getter方法.属性名：利润中心 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_pcorg() {
		return pk_pcorg;
	}

	/**
	 * 属性pk_pcorg的Setter方法.属性名：利润中心 创建日期:
	 * 
	 * @param newPk_pcorg
	 *            java.lang.String
	 */
	public void setPk_pcorg(java.lang.String newPk_pcorg) {
		this.pk_pcorg = newPk_pcorg;
	}

	/**
	 * 属性pk_resacostcenter的Getter方法.属性名：成本中心 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_resacostcenter() {
		return pk_resacostcenter;
	}

	/**
	 * 属性pk_resacostcenter的Setter方法.属性名：成本中心 创建日期:
	 * 
	 * @param newPk_resacostcenter
	 *            java.lang.String
	 */
	public void setPk_resacostcenter(java.lang.String newPk_resacostcenter) {
		this.pk_resacostcenter = newPk_resacostcenter;
	}

	/**
	 * 属性pk_salesman的Getter方法.属性名：业务员 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_salesman() {
		return pk_salesman;
	}

	/**
	 * 属性pk_salesman的Setter方法.属性名：业务员 创建日期:
	 * 
	 * @param newPk_salesman
	 *            java.lang.String
	 */
	public void setPk_salesman(java.lang.String newPk_salesman) {
		this.pk_salesman = newPk_salesman;
	}

	/**
	 * 属性pk_iobsclass的Getter方法.属性名：收支项目 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_iobsclass() {
		return pk_iobsclass;
	}

	/**
	 * 属性pk_iobsclass的Setter方法.属性名：收支项目 创建日期:
	 * 
	 * @param newPk_iobsclass
	 *            java.lang.String
	 */
	public void setPk_iobsclass(java.lang.String newPk_iobsclass) {
		this.pk_iobsclass = newPk_iobsclass;
	}

	/**
	 * 属性pk_project的Getter方法.属性名：项目 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_project() {
		return pk_project;
	}

	/**
	 * 属性pk_project的Setter方法.属性名：项目 创建日期:
	 * 
	 * @param newPk_project
	 *            java.lang.String
	 */
	public void setPk_project(java.lang.String newPk_project) {
		this.pk_project = newPk_project;
	}

	/**
	 * 属性pk_wbs的Getter方法.属性名：项目任务 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_wbs() {
		return pk_wbs;
	}

	/**
	 * 属性pk_wbs的Setter方法.属性名：项目任务 创建日期:
	 * 
	 * @param newPk_wbs
	 *            java.lang.String
	 */
	public void setPk_wbs(java.lang.String newPk_wbs) {
		this.pk_wbs = newPk_wbs;
	}

	/**
	 * 属性pk_customer的Getter方法.属性名：客户 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_customer() {
		return pk_customer;
	}

	/**
	 * 属性pk_customer的Setter方法.属性名：客户 创建日期:
	 * 
	 * @param newPk_customer
	 *            java.lang.String
	 */
	public void setPk_customer(java.lang.String newPk_customer) {
		this.pk_customer = newPk_customer;
	}

	/**
	 * 属性pk_supplier的Getter方法.属性名：供应商 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_supplier() {
		return pk_supplier;
	}

	/**
	 * 属性pk_supplier的Setter方法.属性名：供应商 创建日期:
	 * 
	 * @param newPk_supplier
	 *            java.lang.String
	 */
	public void setPk_supplier(java.lang.String newPk_supplier) {
		this.pk_supplier = newPk_supplier;
	}

	/**
	 * 属性reason的Getter方法.属性名：事由 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getReason() {
		return reason;
	}

	/**
	 * 属性reason的Setter方法.属性名：事由 创建日期:
	 * 
	 * @param newReason
	 *            java.lang.String
	 */
	public void setReason(java.lang.String newReason) {
		this.reason = newReason;
	}

	/**
	 * 属性pk_currtype的Getter方法.属性名：币种 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_currtype() {
		return pk_currtype;
	}

	/**
	 * 属性pk_currtype的Setter方法.属性名：币种 创建日期:
	 * 
	 * @param newPk_currtype
	 *            java.lang.String
	 */
	public void setPk_currtype(java.lang.String newPk_currtype) {
		this.pk_currtype = newPk_currtype;
	}

	/**
	 * 属性orig_amount的Getter方法.属性名：金额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrig_amount() {
		return orig_amount;
	}

	/**
	 * 属性orig_amount的Setter方法.属性名：金额 创建日期:
	 * 
	 * @param newOrig_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setOrig_amount(nc.vo.pub.lang.UFDouble newOrig_amount) {
		this.orig_amount = newOrig_amount;
	}

	/**
	 * 属性billno的Getter方法.属性名：单据编号 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBillno() {
		return billno;
	}

	/**
	 * 属性billno的Setter方法.属性名：单据编号 创建日期:
	 * 
	 * @param newBillno
	 *            java.lang.String
	 */
	public void setBillno(java.lang.String newBillno) {
		this.billno = newBillno;
	}

	/**
	 * 属性pk_billtype的Getter方法.属性名：单据类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtype() {
		return pk_billtype;
	}

	/**
	 * 属性pk_billtype的Setter方法.属性名：单据类型 创建日期:
	 * 
	 * @param newPk_billtype
	 *            java.lang.String
	 */
	public void setPk_billtype(java.lang.String newPk_billtype) {
		this.pk_billtype = newPk_billtype;
	}

	/**
	 * 属性pk_tradetype的Getter方法.属性名：交易类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_tradetype() {
		return pk_tradetype;
	}

	/**
	 * 属性pk_tradetype的Setter方法.属性名：交易类型 创建日期:
	 * 
	 * @param newPk_tradetype
	 *            java.lang.String
	 */
	public void setPk_tradetype(java.lang.String newPk_tradetype) {
		this.pk_tradetype = newPk_tradetype;
	}

	/**
	 * 属性billdate的Getter方法.属性名：制单日期 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getBilldate() {
		return billdate;
	}

	/**
	 * 属性billdate的Setter方法.属性名：制单日期 创建日期:
	 * 
	 * @param newBilldate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setBilldate(nc.vo.pub.lang.UFDate newBilldate) {
		this.billdate = newBilldate;
	}

	/**
	 * 属性close_status的Getter方法.属性名：关闭状态 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getClose_status() {
		return close_status;
	}

	/**
	 * 属性close_status的Setter方法.属性名：关闭状态 创建日期:
	 * 
	 * @param newClose_status
	 *            java.lang.Integer
	 */
	public void setClose_status(java.lang.Integer newClose_status) {
		this.close_status = newClose_status;
	}

	/**
	 * 属性billstatus的Getter方法.属性名：单据状态 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getBillstatus() {
		return billstatus;
	}

	/**
	 * 属性billstatus的Setter方法.属性名：单据状态 创建日期:
	 * 
	 * @param newBillstatus
	 *            java.lang.Integer
	 */
	public void setBillstatus(java.lang.Integer newBillstatus) {
		this.billstatus = newBillstatus;
	}

	/**
	 * 属性effectstatus的Getter方法.属性名：生效状态 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEffectstatus() {
		return effectstatus;
	}

	/**
	 * 属性effectstatus的Setter方法.属性名：生效状态 创建日期:
	 * 
	 * @param newEffectstatus
	 *            java.lang.Integer
	 */
	public void setEffectstatus(java.lang.Integer newEffectstatus) {
		this.effectstatus = newEffectstatus;
	}

	/**
	 * 属性closeman的Getter方法.属性名：关闭人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCloseman() {
		return closeman;
	}

	/**
	 * 属性closeman的Setter方法.属性名：关闭人 创建日期:
	 * 
	 * @param newCloseman
	 *            java.lang.String
	 */
	public void setCloseman(java.lang.String newCloseman) {
		this.closeman = newCloseman;
	}

	/**
	 * 属性closedate的Getter方法.属性名：关闭日期 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getClosedate() {
		return closedate;
	}

	/**
	 * 属性closedate的Setter方法.属性名：关闭日期 创建日期:
	 * 
	 * @param newClosedate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setClosedate(nc.vo.pub.lang.UFDate newClosedate) {
		this.closedate = newClosedate;
	}

	/**
	 * 属性org_currinfo的Getter方法.属性名：组织本币汇率 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_currinfo() {
		return org_currinfo;
	}

	/**
	 * 属性org_currinfo的Setter方法.属性名：组织本币汇率 创建日期:
	 * 
	 * @param newOrg_currinfo
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_currinfo(nc.vo.pub.lang.UFDouble newOrg_currinfo) {
		this.org_currinfo = newOrg_currinfo;
	}

	/**
	 * 属性group_currinfo的Getter方法.属性名：集团本币汇率 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_currinfo() {
		return group_currinfo;
	}

	/**
	 * 属性group_currinfo的Setter方法.属性名：集团本币汇率 创建日期:
	 * 
	 * @param newGroup_currinfo
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_currinfo(nc.vo.pub.lang.UFDouble newGroup_currinfo) {
		this.group_currinfo = newGroup_currinfo;
	}

	/**
	 * 属性global_currinfo的Getter方法.属性名：全局本币汇率 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_currinfo() {
		return global_currinfo;
	}

	/**
	 * 属性global_currinfo的Setter方法.属性名：全局本币汇率 创建日期:
	 * 
	 * @param newGlobal_currinfo
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_currinfo(nc.vo.pub.lang.UFDouble newGlobal_currinfo) {
		this.global_currinfo = newGlobal_currinfo;
	}

	/**
	 * 属性org_amount的Getter方法.属性名：组织本币金额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_amount() {
		return org_amount;
	}

	/**
	 * 属性org_amount的Setter方法.属性名：组织本币金额 创建日期:
	 * 
	 * @param newOrg_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_amount(nc.vo.pub.lang.UFDouble newOrg_amount) {
		this.org_amount = newOrg_amount;
	}

	/**
	 * 属性group_amount的Getter方法.属性名：集团本币金额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_amount() {
		return group_amount;
	}

	/**
	 * 属性group_amount的Setter方法.属性名：集团本币金额 创建日期:
	 * 
	 * @param newGroup_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_amount(nc.vo.pub.lang.UFDouble newGroup_amount) {
		this.group_amount = newGroup_amount;
	}

	/**
	 * 属性global_amount的Getter方法.属性名：全局本币金额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_amount() {
		return global_amount;
	}

	/**
	 * 属性global_amount的Setter方法.属性名：全局本币金额 创建日期:
	 * 
	 * @param newGlobal_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_amount(nc.vo.pub.lang.UFDouble newGlobal_amount) {
		this.global_amount = newGlobal_amount;
	}

	/**
	 * 属性pk_org的Getter方法.属性名：所属组织 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法.属性名：所属组织 创建日期:
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}

	/**
	 * 属性pk_group的Getter方法.属性名：所属集团 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}

	/**
	 * 属性pk_group的Setter方法.属性名：所属集团 创建日期:
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}

	/**
	 * 属性rest_amount的Getter方法.属性名：余额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getRest_amount() {
		return rest_amount;
	}

	/**
	 * 属性rest_amount的Setter方法.属性名：余额 创建日期:
	 * 
	 * @param newRest_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setRest_amount(nc.vo.pub.lang.UFDouble newRest_amount) {
		this.rest_amount = newRest_amount;
	}

	/**
	 * 属性org_rest_amount的Getter方法.属性名：组织本币余额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_rest_amount() {
		return org_rest_amount;
	}

	/**
	 * 属性org_rest_amount的Setter方法.属性名：组织本币余额 创建日期:
	 * 
	 * @param newOrg_rest_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_rest_amount(nc.vo.pub.lang.UFDouble newOrg_rest_amount) {
		this.org_rest_amount = newOrg_rest_amount;
	}

	/**
	 * 属性group_rest_amount的Getter方法.属性名：集团本币余额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_rest_amount() {
		return group_rest_amount;
	}

	/**
	 * 属性group_rest_amount的Setter方法.属性名：集团本币余额 创建日期:
	 * 
	 * @param newGroup_rest_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_rest_amount(nc.vo.pub.lang.UFDouble newGroup_rest_amount) {
		this.group_rest_amount = newGroup_rest_amount;
	}

	/**
	 * 属性global_rest_amount的Getter方法.属性名：全局本币余额 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_rest_amount() {
		return global_rest_amount;
	}

	/**
	 * 属性global_rest_amount的Setter方法.属性名：全局本币余额 创建日期:
	 * 
	 * @param newGlobal_rest_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_rest_amount(nc.vo.pub.lang.UFDouble newGlobal_rest_amount) {
		this.global_rest_amount = newGlobal_rest_amount;
	}

	/**
	 * 属性exe_amount的Getter方法.属性名：执行数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getExe_amount() {
		return exe_amount;
	}

	/**
	 * 属性exe_amount的Setter方法.属性名：执行数 创建日期:
	 * 
	 * @param newExe_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setExe_amount(nc.vo.pub.lang.UFDouble newExe_amount) {
		this.exe_amount = newExe_amount;
	}

	/**
	 * 属性org_exe_amount的Getter方法.属性名：组织本币执行数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_exe_amount() {
		return org_exe_amount;
	}

	/**
	 * 属性org_exe_amount的Setter方法.属性名：组织本币执行数 创建日期:
	 * 
	 * @param newOrg_exe_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_exe_amount(nc.vo.pub.lang.UFDouble newOrg_exe_amount) {
		this.org_exe_amount = newOrg_exe_amount;
	}

	/**
	 * 属性group_exe_amount的Getter方法.属性名：集团本币执行数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_exe_amount() {
		return group_exe_amount;
	}

	/**
	 * 属性group_exe_amount的Setter方法.属性名：集团本币执行数 创建日期:
	 * 
	 * @param newGroup_exe_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_exe_amount(nc.vo.pub.lang.UFDouble newGroup_exe_amount) {
		this.group_exe_amount = newGroup_exe_amount;
	}

	/**
	 * 属性global_exe_amount的Getter方法.属性名：全局本币执行数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_exe_amount() {
		return global_exe_amount;
	}

	/**
	 * 属性global_exe_amount的Setter方法.属性名：全局本币执行数 创建日期:
	 * 
	 * @param newGlobal_exe_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_exe_amount(nc.vo.pub.lang.UFDouble newGlobal_exe_amount) {
		this.global_exe_amount = newGlobal_exe_amount;
	}

	/**
	 * 属性rowno的Getter方法.属性名：行号 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getRowno() {
		return rowno;
	}

	/**
	 * 属性rowno的Setter方法.属性名：行号 创建日期:
	 * 
	 * @param newRowno
	 *            java.lang.Integer
	 */
	public void setRowno(java.lang.Integer newRowno) {
		this.rowno = newRowno;
	}

	/**
	 * 属性pre_amount的Getter方法.属性名：预占数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getPre_amount() {
		return pre_amount;
	}

	/**
	 * 属性pre_amount的Setter方法.属性名：预占数 创建日期:
	 * 
	 * @param newPre_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setPre_amount(nc.vo.pub.lang.UFDouble newPre_amount) {
		this.pre_amount = newPre_amount;
	}

	/**
	 * 属性org_pre_amount的Getter方法.属性名：组织本币预占数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getOrg_pre_amount() {
		return org_pre_amount;
	}

	/**
	 * 属性org_pre_amount的Setter方法.属性名：组织本币预占数 创建日期:
	 * 
	 * @param newOrg_pre_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setOrg_pre_amount(nc.vo.pub.lang.UFDouble newOrg_pre_amount) {
		this.org_pre_amount = newOrg_pre_amount;
	}

	/**
	 * 属性group_pre_amount的Getter方法.属性名：集团本币预占数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGroup_pre_amount() {
		return group_pre_amount;
	}

	/**
	 * 属性group_pre_amount的Setter方法.属性名：集团本币预占数 创建日期:
	 * 
	 * @param newGroup_pre_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGroup_pre_amount(nc.vo.pub.lang.UFDouble newGroup_pre_amount) {
		this.group_pre_amount = newGroup_pre_amount;
	}

	/**
	 * 属性global_pre_amount的Getter方法.属性名：全局本币预占数 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGlobal_pre_amount() {
		return global_pre_amount;
	}

	/**
	 * 属性global_pre_amount的Setter方法.属性名：全局本币预占数 创建日期:
	 * 
	 * @param newGlobal_pre_amount
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setGlobal_pre_amount(nc.vo.pub.lang.UFDouble newGlobal_pre_amount) {
		this.global_pre_amount = newGlobal_pre_amount;
	}

	/**
	 * 属性billmaker的Getter方法.属性名：申请人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker() {
		return billmaker;
	}

	/**
	 * 属性billmaker的Setter方法.属性名：申请人 创建日期:
	 * 
	 * @param newBillmaker
	 *            java.lang.String
	 */
	public void setBillmaker(java.lang.String newBillmaker) {
		this.billmaker = newBillmaker;
	}

	/**
	 * 属性apply_dept的Getter方法.属性名：申请部门 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getApply_dept() {
		return apply_dept;
	}

	/**
	 * 属性apply_dept的Setter方法.属性名：申请部门 创建日期:
	 * 
	 * @param newApply_dept
	 *            java.lang.String
	 */
	public void setApply_dept(java.lang.String newApply_dept) {
		this.apply_dept = newApply_dept;
	}

	/**
	 * 属性approvetime的Getter方法.属性名：审批时间 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getApprovetime() {
		return approvetime;
	}

	/**
	 * 属性approvetime的Setter方法.属性名：审批时间 创建日期:
	 * 
	 * @param newApprovetime
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setApprovetime(nc.vo.pub.lang.UFDate newApprovetime) {
		this.approvetime = newApprovetime;
	}

	/**
	 * 属性defitem30的Getter方法.属性名：自定义项30 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem30() {
		return defitem30;
	}

	/**
	 * 属性defitem30的Setter方法.属性名：自定义项30 创建日期:
	 * 
	 * @param newDefitem30
	 *            java.lang.String
	 */
	public void setDefitem30(java.lang.String newDefitem30) {
		this.defitem30 = newDefitem30;
	}

	/**
	 * 属性defitem29的Getter方法.属性名：自定义项29 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem29() {
		return defitem29;
	}

	/**
	 * 属性defitem29的Setter方法.属性名：自定义项29 创建日期:
	 * 
	 * @param newDefitem29
	 *            java.lang.String
	 */
	public void setDefitem29(java.lang.String newDefitem29) {
		this.defitem29 = newDefitem29;
	}

	/**
	 * 属性defitem28的Getter方法.属性名：自定义项28 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem28() {
		return defitem28;
	}

	/**
	 * 属性defitem28的Setter方法.属性名：自定义项28 创建日期:
	 * 
	 * @param newDefitem28
	 *            java.lang.String
	 */
	public void setDefitem28(java.lang.String newDefitem28) {
		this.defitem28 = newDefitem28;
	}

	/**
	 * 属性defitem27的Getter方法.属性名：自定义项27 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem27() {
		return defitem27;
	}

	/**
	 * 属性defitem27的Setter方法.属性名：自定义项27 创建日期:
	 * 
	 * @param newDefitem27
	 *            java.lang.String
	 */
	public void setDefitem27(java.lang.String newDefitem27) {
		this.defitem27 = newDefitem27;
	}

	/**
	 * 属性defitem26的Getter方法.属性名：自定义项26 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem26() {
		return defitem26;
	}

	/**
	 * 属性defitem26的Setter方法.属性名：自定义项26 创建日期:
	 * 
	 * @param newDefitem26
	 *            java.lang.String
	 */
	public void setDefitem26(java.lang.String newDefitem26) {
		this.defitem26 = newDefitem26;
	}

	/**
	 * 属性defitem25的Getter方法.属性名：自定义项25 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem25() {
		return defitem25;
	}

	/**
	 * 属性defitem25的Setter方法.属性名：自定义项25 创建日期:
	 * 
	 * @param newDefitem25
	 *            java.lang.String
	 */
	public void setDefitem25(java.lang.String newDefitem25) {
		this.defitem25 = newDefitem25;
	}

	/**
	 * 属性defitem24的Getter方法.属性名：自定义项24 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem24() {
		return defitem24;
	}

	/**
	 * 属性defitem24的Setter方法.属性名：自定义项24 创建日期:
	 * 
	 * @param newDefitem24
	 *            java.lang.String
	 */
	public void setDefitem24(java.lang.String newDefitem24) {
		this.defitem24 = newDefitem24;
	}

	/**
	 * 属性defitem23的Getter方法.属性名：自定义项23 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem23() {
		return defitem23;
	}

	/**
	 * 属性defitem23的Setter方法.属性名：自定义项23 创建日期:
	 * 
	 * @param newDefitem23
	 *            java.lang.String
	 */
	public void setDefitem23(java.lang.String newDefitem23) {
		this.defitem23 = newDefitem23;
	}

	/**
	 * 属性defitem22的Getter方法.属性名：自定义项22 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem22() {
		return defitem22;
	}

	/**
	 * 属性defitem22的Setter方法.属性名：自定义项22 创建日期:
	 * 
	 * @param newDefitem22
	 *            java.lang.String
	 */
	public void setDefitem22(java.lang.String newDefitem22) {
		this.defitem22 = newDefitem22;
	}

	/**
	 * 属性defitem21的Getter方法.属性名：自定义项21 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem21() {
		return defitem21;
	}

	/**
	 * 属性defitem21的Setter方法.属性名：自定义项21 创建日期:
	 * 
	 * @param newDefitem21
	 *            java.lang.String
	 */
	public void setDefitem21(java.lang.String newDefitem21) {
		this.defitem21 = newDefitem21;
	}

	/**
	 * 属性defitem20的Getter方法.属性名：自定义项20 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem20() {
		return defitem20;
	}

	/**
	 * 属性defitem20的Setter方法.属性名：自定义项20 创建日期:
	 * 
	 * @param newDefitem20
	 *            java.lang.String
	 */
	public void setDefitem20(java.lang.String newDefitem20) {
		this.defitem20 = newDefitem20;
	}

	/**
	 * 属性defitem19的Getter方法.属性名：自定义项19 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem19() {
		return defitem19;
	}

	/**
	 * 属性defitem19的Setter方法.属性名：自定义项19 创建日期:
	 * 
	 * @param newDefitem19
	 *            java.lang.String
	 */
	public void setDefitem19(java.lang.String newDefitem19) {
		this.defitem19 = newDefitem19;
	}

	/**
	 * 属性defitem18的Getter方法.属性名：自定义项18 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem18() {
		return defitem18;
	}

	/**
	 * 属性defitem18的Setter方法.属性名：自定义项18 创建日期:
	 * 
	 * @param newDefitem18
	 *            java.lang.String
	 */
	public void setDefitem18(java.lang.String newDefitem18) {
		this.defitem18 = newDefitem18;
	}

	/**
	 * 属性defitem17的Getter方法.属性名：自定义项17 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem17() {
		return defitem17;
	}

	/**
	 * 属性defitem17的Setter方法.属性名：自定义项17 创建日期:
	 * 
	 * @param newDefitem17
	 *            java.lang.String
	 */
	public void setDefitem17(java.lang.String newDefitem17) {
		this.defitem17 = newDefitem17;
	}

	/**
	 * 属性defitem16的Getter方法.属性名：自定义项16 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem16() {
		return defitem16;
	}

	/**
	 * 属性defitem16的Setter方法.属性名：自定义项16 创建日期:
	 * 
	 * @param newDefitem16
	 *            java.lang.String
	 */
	public void setDefitem16(java.lang.String newDefitem16) {
		this.defitem16 = newDefitem16;
	}

	/**
	 * 属性defitem15的Getter方法.属性名：自定义项15 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem15() {
		return defitem15;
	}

	/**
	 * 属性defitem15的Setter方法.属性名：自定义项15 创建日期:
	 * 
	 * @param newDefitem15
	 *            java.lang.String
	 */
	public void setDefitem15(java.lang.String newDefitem15) {
		this.defitem15 = newDefitem15;
	}

	/**
	 * 属性defitem14的Getter方法.属性名：自定义项14 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem14() {
		return defitem14;
	}

	/**
	 * 属性defitem14的Setter方法.属性名：自定义项14 创建日期:
	 * 
	 * @param newDefitem14
	 *            java.lang.String
	 */
	public void setDefitem14(java.lang.String newDefitem14) {
		this.defitem14 = newDefitem14;
	}

	/**
	 * 属性defitem13的Getter方法.属性名：自定义项13 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem13() {
		return defitem13;
	}

	/**
	 * 属性defitem13的Setter方法.属性名：自定义项13 创建日期:
	 * 
	 * @param newDefitem13
	 *            java.lang.String
	 */
	public void setDefitem13(java.lang.String newDefitem13) {
		this.defitem13 = newDefitem13;
	}

	/**
	 * 属性defitem12的Getter方法.属性名：自定义项12 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem12() {
		return defitem12;
	}

	/**
	 * 属性defitem12的Setter方法.属性名：自定义项12 创建日期:
	 * 
	 * @param newDefitem12
	 *            java.lang.String
	 */
	public void setDefitem12(java.lang.String newDefitem12) {
		this.defitem12 = newDefitem12;
	}

	/**
	 * 属性defitem11的Getter方法.属性名：自定义项11 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem11() {
		return defitem11;
	}

	/**
	 * 属性defitem11的Setter方法.属性名：自定义项11 创建日期:
	 * 
	 * @param newDefitem11
	 *            java.lang.String
	 */
	public void setDefitem11(java.lang.String newDefitem11) {
		this.defitem11 = newDefitem11;
	}

	/**
	 * 属性defitem10的Getter方法.属性名：自定义项10 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem10() {
		return defitem10;
	}

	/**
	 * 属性defitem10的Setter方法.属性名：自定义项10 创建日期:
	 * 
	 * @param newDefitem10
	 *            java.lang.String
	 */
	public void setDefitem10(java.lang.String newDefitem10) {
		this.defitem10 = newDefitem10;
	}

	/**
	 * 属性defitem9的Getter方法.属性名：自定义项9 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem9() {
		return defitem9;
	}

	/**
	 * 属性defitem9的Setter方法.属性名：自定义项9 创建日期:
	 * 
	 * @param newDefitem9
	 *            java.lang.String
	 */
	public void setDefitem9(java.lang.String newDefitem9) {
		this.defitem9 = newDefitem9;
	}

	/**
	 * 属性defitem8的Getter方法.属性名：自定义项8 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem8() {
		return defitem8;
	}

	/**
	 * 属性defitem8的Setter方法.属性名：自定义项8 创建日期:
	 * 
	 * @param newDefitem8
	 *            java.lang.String
	 */
	public void setDefitem8(java.lang.String newDefitem8) {
		this.defitem8 = newDefitem8;
	}

	/**
	 * 属性defitem7的Getter方法.属性名：自定义项7 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem7() {
		return defitem7;
	}

	/**
	 * 属性defitem7的Setter方法.属性名：自定义项7 创建日期:
	 * 
	 * @param newDefitem7
	 *            java.lang.String
	 */
	public void setDefitem7(java.lang.String newDefitem7) {
		this.defitem7 = newDefitem7;
	}

	/**
	 * 属性defitem6的Getter方法.属性名：自定义项6 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem6() {
		return defitem6;
	}

	/**
	 * 属性defitem6的Setter方法.属性名：自定义项6 创建日期:
	 * 
	 * @param newDefitem6
	 *            java.lang.String
	 */
	public void setDefitem6(java.lang.String newDefitem6) {
		this.defitem6 = newDefitem6;
	}

	/**
	 * 属性defitem5的Getter方法.属性名：自定义项5 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem5() {
		return defitem5;
	}

	/**
	 * 属性defitem5的Setter方法.属性名：自定义项5 创建日期:
	 * 
	 * @param newDefitem5
	 *            java.lang.String
	 */
	public void setDefitem5(java.lang.String newDefitem5) {
		this.defitem5 = newDefitem5;
	}

	/**
	 * 属性defitem4的Getter方法.属性名：自定义项4 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem4() {
		return defitem4;
	}

	/**
	 * 属性defitem4的Setter方法.属性名：自定义项4 创建日期:
	 * 
	 * @param newDefitem4
	 *            java.lang.String
	 */
	public void setDefitem4(java.lang.String newDefitem4) {
		this.defitem4 = newDefitem4;
	}

	/**
	 * 属性defitem3的Getter方法.属性名：自定义项3 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem3() {
		return defitem3;
	}

	/**
	 * 属性defitem3的Setter方法.属性名：自定义项3 创建日期:
	 * 
	 * @param newDefitem3
	 *            java.lang.String
	 */
	public void setDefitem3(java.lang.String newDefitem3) {
		this.defitem3 = newDefitem3;
	}

	/**
	 * 属性defitem2的Getter方法.属性名：自定义项2 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem2() {
		return defitem2;
	}

	/**
	 * 属性defitem2的Setter方法.属性名：自定义项2 创建日期:
	 * 
	 * @param newDefitem2
	 *            java.lang.String
	 */
	public void setDefitem2(java.lang.String newDefitem2) {
		this.defitem2 = newDefitem2;
	}

	/**
	 * 属性defitem1的Getter方法.属性名：自定义项1 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDefitem1() {
		return defitem1;
	}

	/**
	 * 属性defitem1的Setter方法.属性名：自定义项1 创建日期:
	 * 
	 * @param newDefitem1
	 *            java.lang.String
	 */
	public void setDefitem1(java.lang.String newDefitem1) {
		this.defitem1 = newDefitem1;
	}

	/**
	 * 属性dr的Getter方法.属性名：dr 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.属性名：dr 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法.属性名：ts 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.属性名：ts 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return "pk_mtapp_bill";
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_mtapp_detail";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "er_mtapp_detail";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "er_mtapp_detail";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public MtAppDetailVO() {
		super();
	}

	public IVOMeta getMetaData() {
		IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("erm.mtapp_detail");
		return meta;
	}

	public java.lang.String getPk_checkele() {
		return pk_checkele;
	}

	public void setPk_checkele(java.lang.String pkCheckele) {
		pk_checkele = pkCheckele;
	}

	public UFDouble getUsable_amout() {
		return usable_amout;
	}

	public void setUsable_amout(UFDouble usable_amout) {
		this.usable_amout = usable_amout;
	}
}
