insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKJV',0,-1,null,null,0,0,null,-1,'N',null,-1,'tempcode',null,'N',0,'N','N',0,null,0,'tempcode','uap.msgtemp.tempcode',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'MSGTEMP-000001',null,'N',0,2,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKJW',0,-1,null,null,0,0,null,-1,'N',null,-1,'pk_templet',null,'N',0,'N','N',0,null,0,'pk_templet','uap.msgtemp.pk_templet',null,'N',0,null,'1001Z3100000000118A2',null,0,null,null,null,'N',0,1,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKJX',0,-1,null,null,0,0,null,-1,'N',null,-1,'ts',null,'N',0,'N','N',0,null,0,'ts','uap.msgtemp.ts',null,'N',0,null,'1001Z3100000000118A2',null,0,null,null,null,'N',0,10,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,0,0,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKJY',0,-1,null,null,0,0,null,-1,'N',null,-1,'pk_outtemplet',null,'N',0,'N','N',0,null,0,'pk_outtemplet','uap.msgtemp.pk_outtemplet',null,'N',0,null,'1001Z3100000000118A2',null,0,null,null,null,'N',0,8,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKJZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'tempdscrpt',null,'N',1,'N','Y',0,null,0,'tempdscrpt','uap.msgtemp.tempdscrpt',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'MSGTEMP-000003',null,'N',1,5,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,0,0,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKK0',1,-1,null,null,0,0,null,-1,'N',null,-1,'typecode',null,'N',1,'N','Y',0,null,0,'typecode','uap.msgtemp.typecode',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'2msgtemp-000002',null,'N',1,9,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKK1',1,-1,null,null,0,0,null,-1,'N',null,-1,'langcode',null,'N',1,'N','Y',0,'getcolvalue(pub_multilang,dislpayname,langcode,langcode)',0,'langcode','uap.msgtemp.langcode',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'MSGTEMP-000013',null,'N',1,3,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKK2',1,-1,null,null,0,0,null,-1,'N',null,-1,'textcontent',null,'N',1,'N','Y',0,null,0,'textcontent','uap.msgtemp.textcontent',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'2msgtemp-000003',null,'N',1,7,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKK3',1,-1,null,null,0,0,null,-1,'N',null,-1,'messagetitle',null,'N',1,'N','Y',0,null,0,'messagetitle','uap.msgtemp.messagetitle',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'2msgtemp-000001',null,'N',1,6,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000003AKK4',1,-1,null,null,0,0,null,-1,'N',null,-1,'tempname',null,'N',1,'N','Y',0,null,0,'tempname','uap.msgtemp.tempname',null,'N',0,null,'1001Z3100000000118A2',null,0,null,'MSGTEMP-000002',null,'N',1,4,'msgtemp','消息表体',0,'2012-06-04 14:39:33','N',null,null,null,0,0,'N',0,null,1)
go

